const OWNER_EMAIL="alanloo927@gmail.com",tiers=["Management","Project Manager","Contributor","Reviewer","AI Agent"],MILLA_AGENT_ID="agent:milla-im";
function identity(req:Request){return(req.headers.get("oai-authenticated-user-email")||"").toLowerCase()}
async function dbReady(){const{env}=await import("cloudflare:workers"),db=env.DB,now=new Date().toISOString();await db.prepare("INSERT OR IGNORE INTO members(email,name,tier,status,created_at,member_kind,telegram_chat_id,telegram_status,telegram_username,agent_language,agent_stop_phase) VALUES(?,?,?,?,?,?,?,?,?,?,?)").bind(MILLA_AGENT_ID,"Agent(IM)",4,"Agent profile ready",now,"agent","8009020714","Secure credentials pending","@im_milla_bot","Bilingual","reel-video-production").run();await db.prepare("UPDATE members SET agent_stop_phase='reel-video-production' WHERE email=? AND agent_stop_phase='content-production'").bind(MILLA_AGENT_ID).run();return db}
async function owner(req:Request,db:any){const m=await db.prepare("SELECT tier FROM members WHERE email=?").bind(identity(req)).first<{tier:number}>();return m?.tier===0}
async function management(req:Request,db:any){const m=await db.prepare("SELECT tier FROM members WHERE email=?").bind(identity(req)).first<{tier:number}>();return typeof m?.tier==="number"&&m.tier<=1}

export async function GET(req:Request){
 const db=await dbReady();if(!await management(req,db))return Response.json({error:"Management access required"},{status:403});
 const m=await db.prepare("SELECT m.email,m.name,m.tier,m.status,m.member_kind AS memberKind,m.telegram_chat_id AS telegramChatId,m.telegram_status AS telegramStatus,m.telegram_username AS telegramUsername,m.agent_language AS agentLanguage,m.agent_stop_phase AS agentStopPhase,m.team_id AS teamId,t.name AS teamName,m.created_at AS createdAt,ti.expected_username AS expectedTelegramUsername,ti.telegram_user_id AS telegramUserId,ti.status AS telegramLoginStatus,ti.last_login_at AS telegramLastLoginAt FROM members m LEFT JOIN teams t ON t.id=m.team_id LEFT JOIN member_telegram_identities ti ON ti.member_email=m.email ORDER BY m.tier,m.created_at").all(),teams=await db.prepare("SELECT t.id,t.name,t.lead_email AS leadEmail,COALESCE(m.name,'No Project Manager') AS leadName,(SELECT COUNT(*) FROM members x WHERE x.team_id=t.id) AS memberCount FROM teams t LEFT JOIN members m ON m.email=t.lead_email ORDER BY t.name").all(),login=await db.prepare("SELECT status,config_json AS config FROM integration_connections WHERE provider='telegram-login'").first<any>(),config=login?JSON.parse(login.config||"{}"):{};
 return Response.json({members:m.results,teams:teams.results,tiers,telegramLogin:{ready:Boolean(login),status:login?.status||"Not configured",clientId:config.clientId||"",redirectUri:config.redirectUri||""}});
}

export async function POST(req:Request){
 const db=await dbReady();if(!await owner(req,db))return Response.json({error:"Tier 0 Management access required"},{status:403});const b=await req.json()as any;
 if(b.kind==="team"){if(!b.name?.trim())return Response.json({error:"Team name is required"},{status:400});const result=await db.prepare("INSERT INTO teams(name,lead_email,created_at) VALUES(?,?,?)").bind(b.name.trim(),b.leadEmail||null,new Date().toISOString()).run();if(b.leadEmail)await db.prepare("UPDATE members SET tier=1,team_id=? WHERE email=?").bind(result.meta.last_row_id,b.leadEmail).run();return Response.json({ok:true})}
 if(b.kind==="agent"){const name=String(b.name||"").trim(),username=String(b.telegramUsername||"").trim(),chatId=String(b.telegramChatId||"").trim(),slug=String(b.agentId||name).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),agentId=`agent:${slug}`;if(!name||!username.startsWith("@")||!chatId||!slug)return Response.json({error:"Agent name, Telegram Bot username and Chat ID are required"},{status:400});await db.prepare("INSERT INTO members(email,name,tier,status,created_at,member_kind,telegram_chat_id,telegram_status,telegram_username,agent_language,agent_stop_phase) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(email) DO UPDATE SET name=excluded.name,tier=4,member_kind='agent',telegram_chat_id=excluded.telegram_chat_id,telegram_username=excluded.telegram_username,agent_language=excluded.agent_language,agent_stop_phase=excluded.agent_stop_phase").bind(agentId,name,4,"Agent profile ready",new Date().toISOString(),"agent",chatId,"Secure credentials pending",username,String(b.agentLanguage||"Bilingual"),String(b.agentStopPhase||"reel-video-production")).run();return Response.json({ok:true,agentId})}
 const email=String(b.email||"").trim().toLowerCase(),name=String(b.name||"").trim(),tier=Number(b.tier),telegramUsername=String(b.telegramUsername||"").trim().replace(/^@/,"").toLowerCase(),now=new Date().toISOString();if(!email||!name||!email.includes("@")||tier<1||tier>3)return Response.json({error:"Human members use Tier 1–3. Tier 4 is reserved for AI Agents."},{status:400});
 await db.prepare("INSERT INTO members(email,name,tier,status,team_id,created_at,member_kind) VALUES(?,?,?,?,NULL,?,'human') ON CONFLICT(email) DO UPDATE SET name=excluded.name,tier=excluded.tier,member_kind='human'").bind(email,name,tier,"Pending site access",now).run();
 if(telegramUsername)await db.prepare("INSERT INTO member_telegram_identities(member_email,expected_username,status,created_at,updated_at) VALUES(?,?,'Ready to link',?,?) ON CONFLICT(member_email) DO UPDATE SET expected_username=excluded.expected_username,status=CASE WHEN member_telegram_identities.telegram_user_id IS NULL THEN 'Ready to link' ELSE member_telegram_identities.status END,updated_at=excluded.updated_at").bind(email,telegramUsername,now,now).run();
 return Response.json({ok:true});
}

export async function PATCH(req:Request){const db=await dbReady();if(!await owner(req,db))return Response.json({error:"Tier 0 Management access required"},{status:403});const b=await req.json()as any;if(b.email===OWNER_EMAIL)return Response.json({error:"Management tier cannot be changed"},{status:400});await db.prepare("UPDATE members SET tier=?,team_id=? WHERE email=?").bind(Number(b.tier),b.teamId?Number(b.teamId):null,b.email).run();if(Number(b.tier)===1&&b.teamId)await db.prepare("UPDATE teams SET lead_email=? WHERE id=?").bind(b.email,Number(b.teamId)).run();return Response.json({ok:true})}
export async function DELETE(req:Request){const db=await dbReady();if(!await owner(req,db))return Response.json({error:"Tier 0 Management access required"},{status:403});const b=await req.json()as{email?:string},email=b.email?.toLowerCase();if(!email||email===OWNER_EMAIL)return Response.json({error:"Primary Management account cannot be deleted"},{status:400});await db.batch([db.prepare("UPDATE teams SET lead_email=NULL WHERE lead_email=?").bind(email),db.prepare("DELETE FROM project_members WHERE member_email=?").bind(email),db.prepare("DELETE FROM member_telegram_sessions WHERE member_email=?").bind(email),db.prepare("DELETE FROM member_telegram_identities WHERE member_email=?").bind(email),db.prepare("DELETE FROM members WHERE email=?").bind(email)]);return Response.json({ok:true})}
