import{loadIntegration,saveIntegration}from"../integrations/_lib";
import{readProjectConnection}from"../social-connections/_lib";
import{FACEBOOK_SCOPES}from"./state";
export{FACEBOOK_SCOPES,callbackUrl,cookie,decodeState,encodeState,origin,parseSelectionSecret,projectRedirect,selectionSecret}from"./state";

export async function runtime(){const{env}=await import("cloudflare:workers");return env as any}
export function apiVersion(config:any){return /^v\d+\.\d+$/.test(String(config?.apiVersion||""))?String(config.apiVersion):"v26.0"}

export async function appConnection(db:any,env:any){const app=await loadIntegration(db,env,"facebook-app");if(!app?.secret||!app.config?.appId)throw Object.assign(new Error("Configure the Facebook App in Tier 0 System Connections first."),{status:409,code:"FACEBOOK_APP_NOT_CONFIGURED"});return app}
export async function projectConnection(db:any,env:any,projectId:string,connectionId?:string|null){return readProjectConnection(db,env,projectId,"Facebook Page",connectionId)}

function providerMessage(result:any,status:number){return String(result?.error?.message||result?.error_description||result?.message||`Facebook returned HTTP ${status}`)}
export function oauthErrorResult(result:any,status:number){return{code:String(result?.error?.code||result?.error||`HTTP_${status}`),message:providerMessage(result,status),subcode:result?.error?.error_subcode||null,traceId:String(result?.error?.fbtrace_id||"")}}
export async function recordOAuthError(db:any,projectId:string,actorEmail:string,code:string,message:string,details:Record<string,unknown>={}){const now=new Date().toISOString();await db.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(projectId||null,"facebook_oauth_failed",actorEmail||"system",JSON.stringify({code,message,...details}),now).run()}

export async function inspectPageToken(app:any,pageToken:string){const version=apiVersion(app.config),url=new URL(`https://graph.facebook.com/${version}/debug_token`);url.searchParams.set("input_token",pageToken);const response=await fetch(url,{headers:{authorization:`Bearer ${String(app.config.appId)}|${String(app.secret)}`,"cache-control":"no-store"}}),result:any=await response.json().catch(()=>({}));if(!response.ok||!result?.data?.is_valid)return{isValid:false,status:"INVALID",expiresAt:null,errorCode:result?.error?.code||null};const seconds=Number(result.data.expires_at||0);return{isValid:true,status:"VALID",expiresAt:seconds>0?new Date(seconds*1000).toISOString():null,errorCode:null}}

export async function savePageConnection(db:any,env:any,input:{projectId:string;page:any;grantedScopes:string[];actorEmail:string;requestedConnectionId?:string|null;tokenStatus?:any}){
 const{projectId,page,grantedScopes,actorEmail}=input,accountId=String(page.id||""),pageName=String(page.name||"Facebook Page"),profileUrl=String(page.link||`https://www.facebook.com/${accountId}`),providerKey=`facebook-page:${projectId}:${accountId}`,requestedConnectionId=String(input.requestedConnectionId||""),now=new Date().toISOString();
 if(!accountId||!page.accessToken)throw Object.assign(new Error("Facebook did not return a valid Page ID and Page Access Token."),{status:409,code:"FACEBOOK_PAGE_TOKEN_MISSING"});
 const requested=requestedConnectionId?await db.prepare("SELECT connection_id AS connectionId,provider_key AS providerKey,external_account_id AS accountId,is_default AS isDefault FROM project_social_connections WHERE project_id=? AND platform='Facebook Page' AND connection_id=?").bind(projectId,requestedConnectionId).first<any>():null,byAccount=await db.prepare("SELECT connection_id AS connectionId,provider_key AS providerKey,external_account_id AS accountId,is_default AS isDefault FROM project_social_connections WHERE project_id=? AND platform='Facebook Page' AND external_account_id=?").bind(projectId,accountId).first<any>();
 if(requested&&byAccount&&requested.connectionId!==byAccount.connectionId)throw Object.assign(new Error("This Facebook Page is already connected to this Project."),{status:409,code:"FACEBOOK_PAGE_ALREADY_CONNECTED"});
 const existing=byAccount||requested,defaultRow=await db.prepare("SELECT connection_id FROM project_social_connections WHERE project_id=? AND platform='Facebook Page' AND is_default=1 LIMIT 1").bind(projectId).first<any>(),connectionId=existing?.connectionId||`social_${crypto.randomUUID()}`,isDefault=existing?Number(existing.isDefault||0):defaultRow?0:1,tokenStatus=input.tokenStatus||{isValid:true,status:"VALID",expiresAt:null},tasks=Array.isArray(page.tasks)?page.tasks.map(String):[],capabilities={oauthConnection:true,pageIdentityRead:true,readEngagement:grantedScopes.includes("pages_read_engagement"),readInsights:grantedScopes.includes("read_insights"),autoPublish:false,publishingStatus:"NOT_IMPLEMENTED",personalProfileTarget:false,requestedScopes:FACEBOOK_SCOPES,pageTasks:tasks};
 await saveIntegration(db,env,providerKey,String(page.accessToken),{accountId,pageId:accountId,pageName,profileUrl,category:String(page.category||""),tasks,scopes:grantedScopes,tokenStatus:tokenStatus.status,isValid:Boolean(tokenStatus.isValid),expiresAt:tokenStatus.expiresAt||null},"Connected");
 if(existing)await db.prepare("UPDATE project_social_connections SET provider_key=?,external_account_id=?,profile_url=?,handle=?,account_type='Page',status='Connected',permissions_json=?,capabilities_json=?,token_expires_at=?,connected_by=?,connected_at=?,last_checked_at=?,disconnected_at=NULL,updated_at=? WHERE connection_id=? AND project_id=?").bind(providerKey,accountId,profileUrl,pageName,JSON.stringify(grantedScopes),JSON.stringify(capabilities),tokenStatus.expiresAt||null,actorEmail,now,now,now,connectionId,projectId).run();else await db.prepare("INSERT INTO project_social_connections(connection_id,project_id,platform,provider_key,external_account_id,profile_url,handle,account_type,status,permissions_json,capabilities_json,token_expires_at,connected_by,connected_at,last_checked_at,disconnected_at,is_default,updated_at) VALUES(?,?,'Facebook Page',?,?,?,?,?,'Connected',?,?,?,?,?,?,NULL,?,?) ON CONFLICT(project_id,platform,external_account_id) DO UPDATE SET provider_key=excluded.provider_key,profile_url=excluded.profile_url,handle=excluded.handle,account_type='Page',status='Connected',permissions_json=excluded.permissions_json,capabilities_json=excluded.capabilities_json,token_expires_at=excluded.token_expires_at,connected_by=excluded.connected_by,connected_at=excluded.connected_at,last_checked_at=excluded.last_checked_at,disconnected_at=NULL,updated_at=excluded.updated_at").bind(connectionId,projectId,providerKey,accountId,profileUrl,pageName,"Page",JSON.stringify(grantedScopes),JSON.stringify(capabilities),tokenStatus.expiresAt||null,actorEmail,now,now,isDefault,now).run();
 if(requested?.providerKey&&requested.providerKey!==providerKey)await db.prepare("DELETE FROM integration_connections WHERE provider=?").bind(requested.providerKey).run();
 await db.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(projectId,existing?"facebook_page_reconnected":"facebook_page_connected",actorEmail,JSON.stringify({previousPageId:existing?.accountId||null,pageId:accountId,pageName,profileUrl,scopes:grantedScopes,tasks,tokenStatus:tokenStatus.status,tokenExpiresAt:tokenStatus.expiresAt||null,publishingEnabled:false,personalProfileTarget:false}),now).run();
 return{connectionId,pageId:accountId,pageName,isDefault:Boolean(isDefault)};
}
