import{requestUserEmail}from"../../chatgpt-auth";
const parseJson=(value:any,fallback:any)=>{try{return JSON.parse(value||"")}catch{return fallback}};
async function ctx(req:Request){const{env}=await import("cloudflare:workers");const db=env.DB;await db.prepare(`CREATE TABLE IF NOT EXISTS visual_asset_revisions (id INTEGER PRIMARY KEY AUTOINCREMENT,project_id TEXT NOT NULL,phase TEXT NOT NULL,item_key TEXT NOT NULL,version INTEGER NOT NULL,storage_key TEXT NOT NULL,file_name TEXT NOT NULL,mime_type TEXT NOT NULL,size_bytes INTEGER NOT NULL,uploaded_by TEXT NOT NULL,is_current INTEGER NOT NULL DEFAULT 1,drive_sync_status TEXT NOT NULL DEFAULT 'Pending Drive sync',created_at TEXT NOT NULL)`).run();await db.prepare("CREATE INDEX IF NOT EXISTS visual_asset_lookup ON visual_asset_revisions(project_id,phase,item_key,version)").run();const email=requestUserEmail(req);const member=email?await db.prepare("SELECT email,tier FROM members WHERE email=?").bind(email).first<any>():null;return{env,db,email:email||"",member}}
async function canAccess(db:any,member:any,email:string,projectId:string){if(Number(member?.tier)<=1)return true;return Boolean(await db.prepare("SELECT 1 ok FROM project_members WHERE project_id=? AND member_email=?").bind(projectId,email).first())}
function validUpload(fileName:string,mimeType:string,sizeBytes:number){const allowed=mimeType.startsWith("image/")||mimeType.startsWith("video/")||mimeType.startsWith("audio/")||["application/pdf","application/json","text/plain","application/zip","application/x-zip-compressed"].includes(mimeType)||/\.(png|jpe?g|webp|gif|mp4|mov|webm|mp3|wav|m4a|aac|flac|pdf|txt|json|zip)$/i.test(fileName),limit=mimeType.startsWith("video/")?200:mimeType.startsWith("audio/")?100:25;return{allowed,limit,within:sizeBytes>0&&sizeBytes<=limit*1024*1024}}
function chunkKey(uploadId:string,part:number){return`_upload_chunks/${uploadId}/part-${String(part).padStart(5,"0")}`}
export async function GET(req:Request){const{env,db,email,member}=await ctx(req);if(!member)return Response.json({error:"Workspace membership required"},{status:403});const u=new URL(req.url),projectId=u.searchParams.get("projectId"),phase=u.searchParams.get("phase"),itemKey=u.searchParams.get("itemKey"),itemKeyPrefix=u.searchParams.get("itemKeyPrefix"),storageKey=u.searchParams.get("file");if(storageKey){const row=await db.prepare("SELECT project_id FROM visual_asset_revisions WHERE storage_key=?").bind(storageKey).first<any>();if(!row)return new Response("Not found",{status:404});if(member.tier>1){const ok=await db.prepare("SELECT 1 ok FROM project_members WHERE project_id=? AND member_email=?").bind(row.project_id,email).first();if(!ok)return new Response("Forbidden",{status:403})}const obj=await env.BUCKET.get(storageKey);if(!obj)return new Response("Not found",{status:404});return new Response(obj.body,{headers:{"content-type":obj.httpMetadata?.contentType||"application/octet-stream","cache-control":"private, max-age=300"}})}if(!projectId||!phase)return Response.json({error:"Missing project or phase"},{status:400});if(member.tier>1){const ok=await db.prepare("SELECT 1 ok FROM project_members WHERE project_id=? AND member_email=?").bind(projectId,email).first();if(!ok)return Response.json({error:"Project access denied"},{status:403})}let q="SELECT v.id,v.project_id AS projectId,v.phase,v.item_key AS itemKey,v.version,v.storage_key AS storageKey,v.file_name AS fileName,v.mime_type AS mimeType,v.size_bytes AS sizeBytes,v.uploaded_by AS uploadedBy,v.is_current AS isCurrent,v.drive_sync_status AS driveSyncStatus,v.created_at AS createdAt,u.source_asset_id AS sourceAssetId,u.derived_asset_id AS derivedAssetId,u.runninghub_workflow_id AS runninghubWorkflowId,u.runninghub_task_id AS runninghubTaskId,u.status AS upscaleStatus,u.original_dimensions AS originalDimensions,u.final_dimensions AS finalDimensions,CASE WHEN u.derived_asset_id=v.id THEN u.asset_purpose ELSE NULL END AS assetPurpose,u.last_error AS upscaleError FROM visual_asset_revisions v LEFT JOIN asset_upscale_jobs u ON (u.source_asset_id=v.id OR u.derived_asset_id=v.id) WHERE v.project_id=? AND v.phase=?",args:any[]=[projectId,phase];if(itemKey){q+=" AND v.item_key=?";args.push(itemKey)}else if(itemKeyPrefix){q+=" AND v.item_key LIKE ?";args.push(itemKeyPrefix+"%")}q+=" ORDER BY v.item_key,v.is_current DESC,v.version DESC";const rows=await db.prepare(q).bind(...args).all();return Response.json({assets:(rows.results as any[]).map(row=>({...row,originalDimensions:parseJson(row.originalDimensions,null),finalDimensions:parseJson(row.finalDimensions,null)}))})}
export async function POST(req:Request){
 const{env,db,email,member}=await ctx(req);if(!member)return Response.json({error:"Workspace membership required"},{status:403});
 if(Number(member.tier)===4)return Response.json({error:"Tier 4 AI Agents cannot upload images, video, audio or final production files."},{status:403});
 const url=new URL(req.url),action=url.searchParams.get("action");
 if(action==="chunk"){
  const uploadId=String(url.searchParams.get("uploadId")||""),part=Number(url.searchParams.get("part")),totalParts=Number(url.searchParams.get("totalParts")),projectId=String(url.searchParams.get("projectId")||""),phase=String(url.searchParams.get("phase")||""),itemKey=String(url.searchParams.get("itemKey")||"");
  if(!/^[a-zA-Z0-9-]{8,80}$/.test(uploadId)||!Number.isInteger(part)||part<0||!Number.isInteger(totalParts)||totalParts<1||part>=totalParts||!projectId||!phase||!itemKey)return Response.json({error:"Invalid upload part"},{status:400});
  if(!await canAccess(db,member,email,projectId))return Response.json({error:"Project access denied"},{status:403});
  const length=Number(req.headers.get("content-length")||0);if(length>700*1024)return Response.json({error:"Upload part is too large"},{status:400});if(!req.body)return Response.json({error:"Upload part is empty"},{status:400});
  await env.BUCKET.put(chunkKey(uploadId,part),req.body,{httpMetadata:{contentType:"application/octet-stream"}});return Response.json({ok:true,part});
 }
 if((req.headers.get("content-type")||"").includes("application/json")){
  const body=await req.json() as any;if(body?.action!=="complete-chunked-upload")return Response.json({error:"Unknown upload action"},{status:400});
  const uploadId=String(body.uploadId||""),totalParts=Number(body.totalParts),projectId=String(body.projectId||""),phase=String(body.phase||""),itemKey=String(body.itemKey||""),fileName=String(body.fileName||""),mimeType=String(body.mimeType||"application/octet-stream"),sizeBytes=Number(body.sizeBytes),replaceSet=Boolean(body.replaceSet);
  if(!/^[a-zA-Z0-9-]{8,80}$/.test(uploadId)||!Number.isInteger(totalParts)||totalParts<1||totalParts>500||!projectId||!phase||!itemKey||!fileName)return Response.json({error:"Invalid upload details"},{status:400});
  const validation=validUpload(fileName,mimeType,sizeBytes);if(!validation.allowed)return Response.json({error:"Choose a supported image, video, audio, PDF, text, JSON or ZIP file"},{status:400});if(!validation.within)return Response.json({error:`Each file must be ${validation.limit} MB or smaller`},{status:400});if(phase==="references"&&!mimeType.startsWith("image/")&&!/\.(png|jpe?g|webp)$/i.test(fileName))return Response.json({error:"Project References accept PNG, JPG or WEBP images only"},{status:400});if(!await canAccess(db,member,email,projectId))return Response.json({error:"Project access denied"},{status:403});if(phase==="references"&&!replaceSet){const current=await db.prepare("SELECT COUNT(*) AS count FROM visual_asset_revisions WHERE project_id=? AND phase='references' AND item_key=? AND is_current=1").bind(projectId,itemKey).first<any>();if(Number(current?.count||0)>=4)return Response.json({error:"Each Reference category allows a maximum of 4 images"},{status:409})}
  const partKeys=Array.from({length:totalParts},(_,index)=>chunkKey(uploadId,index)),objects=[] as any[];let received=0;for(const key of partKeys){const object=await env.BUCKET.get(key);if(!object)return Response.json({error:"An upload part is missing. Please retry the file."},{status:409});received+=Number(object.size||0);objects.push(object)}if(received!==sizeBytes)return Response.json({error:"The uploaded file size did not match. Please retry."},{status:409});
  const prev=await db.prepare("SELECT COALESCE(MAX(version),0) version FROM visual_asset_revisions WHERE project_id=? AND phase=? AND item_key=?").bind(projectId,phase,itemKey).first<any>(),version=Number(prev?.version||0)+1,safe=fileName.replace(/[^a-zA-Z0-9._-]/g,"-"),key=`projects/${projectId}/${phase}/${itemKey}/v${version}-${Date.now()}-${safe}`;
  const FixedLengthStreamCtor=(globalThis as any).FixedLengthStream;if(!FixedLengthStreamCtor)return Response.json({error:"Chunked upload storage is temporarily unavailable"},{status:503});const pipe=new FixedLengthStreamCtor(sizeBytes),writer=pipe.writable.getWriter(),store=env.BUCKET.put(key,pipe.readable,{httpMetadata:{contentType:mimeType}});
  try{for(const object of objects){const reader=object.body.getReader();while(true){const next=await reader.read();if(next.done)break;await writer.write(next.value)}}await writer.close();await store}catch(error){try{await writer.abort(error)}catch{}throw error}
  const insert=db.prepare("INSERT INTO visual_asset_revisions(project_id,phase,item_key,version,storage_key,file_name,mime_type,size_bytes,uploaded_by,is_current,drive_sync_status,created_at) VALUES(?,?,?,?,?,?,?,?,?,1,'Pending Drive sync',?)").bind(projectId,phase,itemKey,version,key,fileName,mimeType,sizeBytes,email,new Date().toISOString());if(replaceSet)await db.batch([db.prepare("UPDATE visual_asset_revisions SET is_current=0 WHERE project_id=? AND phase=? AND item_key=?").bind(projectId,phase,itemKey),insert]);else await insert.run();await env.BUCKET.delete(partKeys);
  let driveSynced=false;try{const{syncStoredAssetToDrive,queueProjectDriveRecord}=await import("../google-drive/drive");await syncStoredAssetToDrive(projectId,phase,key,`v${version}_${fileName}`,mimeType);driveSynced=true;await queueProjectDriveRecord(db,{eventKey:`upload:${key}`,projectId,phaseKey:phase,eventType:"media_uploaded",actorEmail:email,payload:{itemKey,version,fileName,mimeType,sizeBytes,storageKey:key,driveSynced:true}})}catch{}return Response.json({ok:true,version,storageKey:key,driveSynced});
 }
 const f=await req.formData(),file=f.get("file"),projectId=String(f.get("projectId")||""),phase=String(f.get("phase")||""),itemKey=String(f.get("itemKey")||""),replaceSet=String(f.get("replaceSet")||"")==="1";
 const allowed=file instanceof File&&(file.type.startsWith("image/")||file.type.startsWith("video/")||file.type.startsWith("audio/")||["application/pdf","application/json","text/plain","application/zip","application/x-zip-compressed"].includes(file.type)||/\.(png|jpe?g|webp|gif|mp4|mov|webm|mp3|wav|m4a|aac|flac|pdf|txt|json|zip)$/i.test(file.name));
 if(!(file instanceof File)||!allowed)return Response.json({error:"Choose a supported image, video, audio, PDF, text, JSON or ZIP file"},{status:400});const limit=file.type.startsWith("video/")?200:file.type.startsWith("audio/")?100:25;if(file.size>limit*1024*1024)return Response.json({error:`Each file must be ${limit} MB or smaller`},{status:400});if(!projectId||!phase||!itemKey)return Response.json({error:"Missing upload details"},{status:400});if(phase==="references"&&!file.type.startsWith("image/")&&!/\.(png|jpe?g|webp)$/i.test(file.name))return Response.json({error:"Project References accept PNG, JPG or WEBP images only"},{status:400});
 if(!await canAccess(db,member,email,projectId))return Response.json({error:"Project access denied"},{status:403});if(phase==="references"&&!replaceSet){const current=await db.prepare("SELECT COUNT(*) AS count FROM visual_asset_revisions WHERE project_id=? AND phase='references' AND item_key=? AND is_current=1").bind(projectId,itemKey).first<any>();if(Number(current?.count||0)>=4)return Response.json({error:"Each Reference category allows a maximum of 4 images"},{status:409})}
 const prev=await db.prepare("SELECT COALESCE(MAX(version),0) version FROM visual_asset_revisions WHERE project_id=? AND phase=? AND item_key=?").bind(projectId,phase,itemKey).first<any>(),version=Number(prev?.version||0)+1,safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-"),key=`projects/${projectId}/${phase}/${itemKey}/v${version}-${Date.now()}-${safe}`;
 await env.BUCKET.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type}});const insert=db.prepare("INSERT INTO visual_asset_revisions(project_id,phase,item_key,version,storage_key,file_name,mime_type,size_bytes,uploaded_by,is_current,drive_sync_status,created_at) VALUES(?,?,?,?,?,?,?,?,?,1,'Pending Drive sync',?)").bind(projectId,phase,itemKey,version,key,file.name,file.type,file.size,email,new Date().toISOString());
 if(replaceSet)await db.batch([db.prepare("UPDATE visual_asset_revisions SET is_current=0 WHERE project_id=? AND phase=? AND item_key=?").bind(projectId,phase,itemKey),insert]);else await insert.run();let driveSynced=false;try{const{syncStoredAssetToDrive,queueProjectDriveRecord}=await import("../google-drive/drive");await syncStoredAssetToDrive(projectId,phase,key,`v${version}_${file.name}`,file.type);driveSynced=true;await queueProjectDriveRecord(db,{eventKey:`upload:${key}`,projectId,phaseKey:phase,eventType:"media_uploaded",actorEmail:email,payload:{itemKey,version,fileName:file.name,mimeType:file.type,sizeBytes:file.size,storageKey:key,driveSynced:true}})}catch{}return Response.json({ok:true,version,storageKey:key,driveSynced})
}
