import test from"node:test";
import assert from"node:assert/strict";
import{aspectRatioFromDimensions,compatibleVideoDimensions,compileI2VPrompt,i2vCreativeSimilarityIssues,i2vProviderPromptIssues,i2vValidationIssues,normalizeI2VPromptItem}from"../app/video-prompt-architecture.ts";
import{inspectRunningHubH3Graph,RUNNINGHUB_H3_ASPECT_RATIO_VALUES,RUNNINGHUB_H3_CONTRACT_VERSION,RUNNINGHUB_H3_INSTANCE_TYPE,RUNNINGHUB_H3_LOCKED_MAPPING,RUNNINGHUB_H3_RECOMMENDED_MEGAPIXELS,RUNNINGHUB_H3_WORKFLOW_ID,runningHubAllocatedInstanceType,runningHubH3AspectRatioValue,runningHubH3MappingIssues,runningHubH3NodeInfo,runningHubH3SubmissionPayload,runningHubWorkflowFingerprint,verifyRunningHubH3Graph}from"../app/api/runninghub/video-contract.ts";
import{approvedReelGenerationRetryData,REEL_STYLES,reelConfigurationIssues,reelRetakeContentIds,unresolvedReelPromptRetake}from"../app/reel-production-architecture.ts";
import{socialBatchAssetKey,socialBatchAssetKeys,socialBatchAssetPrefixFromKey,socialBatchContentId,socialBatchProductionAssetKeys}from"../app/social-batch-assets.ts";
import{selectApprovedReelFirstFrame}from"../app/reel-first-frame.ts";
import{agentPresence,summarizeAgentExecution}from"../app/agent-work-status.ts";
import{freshReelSetup,reelCheckpointEnvelope,reelCheckpointMatchesApproved,reelRetakeMatchesApproved}from"../app/reel-checkpoint-integrity.ts";
import{readFileSync}from"node:fs";

const canonicalGraph={"6":{class_type:"LoadImage",inputs:{image:"first.png"}},"7":{class_type:"MiniMaxH3AudioConditioningT8",inputs:{task_type:"Hybrid",prompt:["28",0],width:["29",0],height:["29",1],length:["30",0],first_frame:["6",0],ref_images:{ref_image_0:["35",0]}}},"13":{class_type:"LearnedLatentUpscale",inputs:{samples:["12",0]}},"14":{class_type:"MiniMaxH3AudioConditioningT8",inputs:{task_type:"Ref2VA",prompt:["28",0],width:["13",1],height:["13",2],length:["30",0],ref_images:{ref_image_0:["6",0]}}},"15":{class_type:"ReconcileLearnedLatent",inputs:{latent:["13",0],conditioning:["14",0]}},"20":{class_type:"VAEDecode",inputs:{samples:["19",0]}},"21":{class_type:"VHS_VideoCombine",inputs:{images:["20",0],save_output:true}},"27":{class_type:"PrimitiveFloat",inputs:{value:10}},"28":{class_type:"Prompt",inputs:{prompt:"move"}},"29":{class_type:"ResolutionSelector",inputs:{aspect_ratio:"4:3 (Standard)",megapixels:1}},"30":{class_type:"Math",inputs:{value:["27",0]}},"35":{class_type:"LoadImage",inputs:{image:"reference.png"}}},verified=verifyRunningHubH3Graph(canonicalGraph),mapping=verified.mapping;

test("Agent presence is based on a recent heartbeat, not enabled Project automation",()=>{const now=Date.parse("2026-09-12T10:00:00.000Z");assert.equal(agentPresence(null,now).state,"offline");assert.equal(agentPresence("2026-09-12T09:50:00.000Z",now).state,"offline");assert.equal(agentPresence("2026-09-12T09:58:00.000Z",now).state,"online")});

test("Agent execution status reports provider truth independently from Agent presence",()=>{const running=summarizeAgentExecution({controlActive:true,controlStatus:"Agent Working · 3 Reel Jobs queued",phaseStatus:"In Progress",children:[{jobType:"VIDEO_GENERATION",status:"RUNNING"},{jobType:"VIDEO_GENERATION",status:"QUEUED"}]});assert.equal(running.state,"provider");assert.equal(running.label,"RunningHub · 2 Reel jobs queued or generating");const failed=summarizeAgentExecution({controlActive:true,phaseStatus:"In Progress",children:[{jobType:"VIDEO_GENERATION",status:"FAILED"}]});assert.equal(failed.needsAttention,true);assert.match(failed.label,/1 Reel generation failed/) });

test("Agent controls have one management surface and Telegram covers start and stop",()=>{const dashboard=readFileSync(new URL("../app/page.tsx",import.meta.url),"utf8"),project=readFileSync(new URL("../app/canonical-project-workspace.tsx",import.meta.url),"utf8"),phase=readFileSync(new URL("../app/canonical-phase-workspace.tsx",import.meta.url),"utf8"),service=readFileSync(new URL("../app/api/agent-runner/service.ts",import.meta.url),"utf8");assert.match(dashboard,/Start Project Automation/);assert.match(dashboard,/Pause Project Automation/);assert.match(dashboard,/Agent connection/);assert.doesNotMatch(project,/onClick=\{command\}/);assert.match(project,/Manage in Workload → Agent Work/);assert.match(phase,/Agent automation is managed in Workload → Agent Work/);assert.doesNotMatch(phase,/✦ Agent Task Start|✦ Resume Image Production/);assert.match(service,/Agent work started/);assert.match(service,/Agent work stopped/) });

test("generation failures are fail-fast, stop queued siblings, and alert management",()=>{const runner=readFileSync(new URL("../app/api/agent-runner/service.ts",import.meta.url),"utf8"),orchestrator=readFileSync(new URL("../app/api/orchestrator/service.ts",import.meta.url),"utf8"),autofill=readFileSync(new URL("../app/api/autofill/engine.ts",import.meta.url),"utf8"),incidents=readFileSync(new URL("../app/api/orchestrator/generation-incidents.ts",import.meta.url),"utf8");assert.doesNotMatch(runner,/jobType:"IMAGE_GENERATION"[\s\S]{0,1600}maxAttempts:3/);assert.match(orchestrator,/FAIL_FAST_GENERATION_JOB_TYPES/);assert.match(incidents,/GENERATION_INCIDENT_NOTIFIED/);assert.match(incidents,/Tier 0–1 \/ Project Lead must review/);assert.match(incidents,/status IN \('QUEUED','SCHEDULED','RETRY_PENDING'\)/);assert.doesNotMatch(autofill,/attempt<3|repairPayload|completionPayload/)});

test("first_frame aspect ratio snaps to the nearest H3 enum with non-zero multiple-of-32 dimensions",()=>{assert.equal(aspectRatioFromDimensions(576,1024),"9:16");assert.deepEqual(compatibleVideoDimensions(576,1024),{width:576,height:1024,aspectRatio:"9:16"});assert.deepEqual(compatibleVideoDimensions(1160,2048),{width:576,height:1024,aspectRatio:"9:16"});assert.deepEqual(compatibleVideoDimensions(1088,1920),{width:576,height:1024,aspectRatio:"9:16"});assert.deepEqual(compatibleVideoDimensions(1024,1536),{width:640,height:960,aspectRatio:"2:3"});assert.deepEqual(compatibleVideoDimensions(1080,1350),{width:768,height:1024,aspectRatio:"3:4"})});

test("Reel prompt recovery restores only a missing current Project Reference and embeds a UI fallback",()=>{const route=readFileSync(new URL("../app/api/projects/route.ts",import.meta.url),"utf8"),workspace=readFileSync(new URL("../app/canonical-phase-workspace.tsx",import.meta.url),"utf8");assert.match(route,/!Number\(item\.referenceAssetId \|\| item\.characterReferenceAssetId\)\s*&&\s*fallbackReference\?\.id/);assert.match(route,/item\.referenceAssetId = Number\(fallbackReference\.id\)/);assert.match(route,/CASE WHEN item_key='character-reference' THEN 0 ELSE 1 END/);assert.match(route,/projectReferences: \(projectReferenceAssets\.results/);assert.match(workspace,/Array\.isArray\(p\.projectReferences\)/);assert.match(workspace,/if \(fetched\.length\) setProjectReferences\(fetched\)/);assert.doesNotMatch(workspace,/catch\(\(\) => setProjectReferences\(\[\]\)\)/)});

test("FF-VIDEO-I2V-01 compiler emits only lean, timed provider direction",()=>{const prompt=compileI2VPrompt({durationSeconds:10,shotCount:2,aspectRatio:"9:16",dialogueMode:"NO_DIALOGUE",musicDirection:"NO_GENERATED_MUSIC",referenceRole:"PRODUCT"},{idea:"A poised morning arrival",hook:"A confident look before the first step"}),words=prompt.split(/\s+/).length;assert.ok(words>=250&&words<=450);assert.match(prompt,/first_frame is the exact opening frame at 0\.00 seconds/);assert.match(prompt,/product identity, geometry, material and finish from ref_image_0/);assert.match(prompt,/From 0\.0–5\.0s/);assert.match(prompt,/During 5\.0–10\.0s/);assert.match(prompt,/30–50 cm/);assert.match(prompt,/only people, products, props and interaction points visibly established in first_frame/);assert.match(prompt,/final state/i);assert.doesNotMatch(prompt,/FRAMEFLOW FORMULA|Reel type:|Content intent:|Tier 0|REFERENCE AUTHORITY|HARD CONSTRAINTS|Sampler/i);assert.doesNotMatch(prompt,/Develop a specific, natural performance|Use one restrained, physically plausible move/);assert.deepEqual(i2vProviderPromptIssues(prompt),[])});

test("all supported IMAGE_TO_VIDEO direction-block counts stay within provider prompt density",()=>{for(const shotCount of[1,2,3]){const prompt=compileI2VPrompt({durationSeconds:13,shotCount,referenceRole:"CHARACTER",dialogueMode:"NO_DIALOGUE",musicDirection:"NO_GENERATED_MUSIC"},{story:"An expressive social reaction"});assert.deepEqual(i2vProviderPromptIssues(prompt),[])}});

test("normalization always lets the OS compiler own provider prose",()=>{const injectedPrompt=compileI2VPrompt({durationSeconds:12,shotCount:1,referenceRole:"CHARACTER",dialogueMode:"NO_DIALOGUE",musicDirection:"NO_GENERATED_MUSIC"},{story:"Unrelated injected direction"}),options={contentId:"content_1",title:"Reel",contentIntent:{story:"Detailed performance"},subjectPresence:"HUMAN_PRESENT",firstFrameAssetId:10,referenceAssetId:11,referenceRole:"PRODUCT",sourceWidth:576,sourceHeight:1024},item=normalizeI2VPromptItem({durationSeconds:12,shotCount:1,compiledVideoPrompt:injectedPrompt},options),legacy=normalizeI2VPromptItem({durationSeconds:12,shotCount:1,compiledVideoPrompt:"FRAMEFLOW FORMULA: FF-VIDEO-I2V-01\nREFERENCE AUTHORITY\nDevelop a specific, natural performance."},options);assert.equal(item.reelType,"IMAGE_TO_VIDEO");assert.equal(item.durationSeconds,12);assert.equal(item.shotCount,1);assert.equal(item.aspectRatio,"9:16");assert.notEqual(item.compiledVideoPrompt,injectedPrompt);assert.match(item.compiledVideoPrompt,/product identity, geometry, material and finish from ref_image_0/);assert.doesNotMatch(legacy.compiledVideoPrompt,/FRAMEFLOW FORMULA|REFERENCE AUTHORITY|Develop a specific/);assert.deepEqual(i2vValidationIssues(item,{workflowMappingExists:true}),[]);assert.deepEqual(i2vValidationIssues({...item,referenceAssetId:null},{workflowMappingExists:false}),["Select a Project Reference for ref_image_0.","Configure the RunningHub MiniMax H3 workflow node mapping in Tier 0 System Connections."])});
test("normalization preserves the locked Reel registry fields for provider retries",()=>{const item=normalizeI2VPromptItem({durationSeconds:10,shotCount:1},{contentId:"content_1",title:"Reel",firstFrameAssetId:10,referenceAssetId:11,sourceWidth:576,sourceHeight:1024});assert.equal(item.reelStyle,"IMAGE_TO_VIDEO");assert.equal(item.workflowId,RUNNINGHUB_H3_WORKFLOW_ID)});

test("OS compiler budgets verbose structured direction into a valid provider prompt",()=>{const verbose="Hana turns toward an already visible friend because that friend reacts first, shifts her weight naturally, loosens both shoulders, changes her hand gesture while preserving contact with the visible object, develops a spontaneous smile, responds with a warm laugh, and settles into an engaged final posture that continues the social moment without posing for camera or introducing anything outside the approved opening frame";for(const shotCount of[1,2,3]){const shots=Array.from({length:shotCount},(_,index)=>({timing:`${index}.0–${index+1}.0s`,purpose:verbose,subjectPerformance:verbose,expressionGaze:verbose,cameraFraming:verbose,cameraMovement:`Camera trucks 30–50 cm slowly to the right with gentle parallax and ends at the same medium subject scale. ${verbose}`,secondaryMotion:verbose})),item=normalizeI2VPromptItem({durationSeconds:13,shotCount,shots,sceneContinuity:verbose,physicalRealism:verbose,compiledVideoPrompt:"Content intent: metadata must never survive"},{contentId:`content_${shotCount}`,title:"Reel",contentIntent:{story:"Social evening"},firstFrameAssetId:10,referenceAssetId:11,referenceRole:"CHARACTER",sourceWidth:576,sourceHeight:1024});assert.deepEqual(i2vProviderPromptIssues(item.compiledVideoPrompt),[]);assert.doesNotMatch(item.compiledVideoPrompt,/Content intent:/)}});

test("normalization fills every requested shot while preserving supplied creative direction",()=>{const item=normalizeI2VPromptItem({durationSeconds:12,shotCount:2,shots:[{purpose:"Opening move",subjectPerformance:"Walk naturally",expressionGaze:"Look ahead",cameraFraming:"Medium",cameraMovement:"Track",secondaryMotion:"Hair movement"}]},{contentId:"content_1",title:"Reel",contentIntent:{story:"Continue naturally"}});assert.equal(item.shots.length,2);assert.equal(item.shots[0].purpose,"Opening move");assert.equal(item.shots[0].timing,"0.0–6.0s");assert.match(item.shots[1].purpose,/Resolve/);assert.equal(item.shots[1].timing,"6.0–12.0s")});

test("legacy abstract performance and camera placeholders normalize before compilation",()=>{const item=normalizeI2VPromptItem({durationSeconds:10,shotCount:1,shots:[{timing:"0.0–10.0s",purpose:"Weekend social energy",subjectPerformance:"Develop a specific, natural performance with motivated eye movement and micro-expression.",expressionGaze:"Natural gaze",cameraFraming:"Medium framing",cameraMovement:"Use one restrained, physically plausible move.",secondaryMotion:"Natural environmental movement remains subtle and continuous."}]},{contentId:"content_1",title:"Reel",contentIntent:{story:"Hana responds warmly to the rooftop gathering"},firstFrameAssetId:10,referenceAssetId:11,referenceRole:"CHARACTER",sourceWidth:576,sourceHeight:1024});assert.doesNotMatch(item.compiledVideoPrompt,/Develop a specific, natural performance|Use one restrained, physically plausible move/);assert.match(item.compiledVideoPrompt,/30–50 cm/);assert.deepEqual(i2vProviderPromptIssues(item.compiledVideoPrompt),[])});

test("specific concise Agent direction survives normalization instead of becoming the shared fallback",()=>{const performance="She notices the visible cyclist ahead, tightens her grip, leans into the turn, then relaxes after passing safely.",camera="Track 40 cm left at bicycle speed, hold her profile, and finish behind the visible handlebar.",item=normalizeI2VPromptItem({durationSeconds:10,shotCount:1,shots:[{purpose:"Turn the near miss into a relieved payoff",subjectPerformance:performance,expressionGaze:"Eyes check the cyclist, then soften with visible relief.",cameraFraming:"Begin on the approved medium profile",cameraMovement:camera,secondaryMotion:"Loose hair and roadside leaves respond to her forward speed."}]},{contentId:"content_1",title:"Ride",contentIntent:{story:"Night bicycle ride"}});assert.equal(item.shots[0].subjectPerformance,performance);assert.equal(item.shots[0].cameraMovement,camera);assert.match(item.compiledVideoPrompt,/notices the visible cyclist ahead/);assert.match(item.compiledVideoPrompt,/Track 40 cm left/)});

test("cross-Reel validator rejects copied creative direction but accepts distinct scene direction",()=>{const copied={shots:[{purpose:"React to a friend",subjectPerformance:"She turns toward the visible friend, shifts her weight, smiles warmly, raises one hand, and settles back into place.",expressionGaze:"Eyes find the friend before a warm smile develops.",cameraMovement:"Track 40 cm right slowly and finish at the same medium scale.",secondaryMotion:"Hair and fabric move gently in the visible breeze."}]},distinct={shots:[{purpose:"Complete the bicycle turn",subjectPerformance:"She checks the path ahead, leans the bicycle through the curve, pedals twice, then straightens into a confident glide.",expressionGaze:"Eyes scan the curve and return to the road exit.",cameraMovement:"Drop 30 cm lower while tracking forward and finish beside the front wheel.",secondaryMotion:"Wheel spokes rotate while roadside leaves trail in her wake."}]};assert.equal(i2vCreativeSimilarityIssues([copied,structuredClone(copied)]).length,1);assert.deepEqual(i2vCreativeSimilarityIssues([copied,distinct]),[])});

test("RunningHub H3 registry sends the recommended megapixel value and leaves frame conversion to Node 30",()=>{assert.deepEqual(runningHubH3MappingIssues(mapping),[]);const nodes=runningHubH3NodeInfo(mapping,{firstFrameFileName:"anchor.png",characterReferenceFileName:"reference.png",compiledVideoPrompt:"prompt",durationSeconds:12,width:576,height:1024,aspectRatio:"9:16"});assert.equal(RUNNINGHUB_H3_RECOMMENDED_MEGAPIXELS,0.5);assert.deepEqual(nodes,[{nodeId:"6",fieldName:"image",fieldValue:"anchor.png"},{nodeId:"35",fieldName:"image",fieldValue:"reference.png"},{nodeId:"28",fieldName:"prompt",fieldValue:"prompt"},{nodeId:"27",fieldName:"value",fieldValue:12},{nodeId:"29",fieldName:"aspect_ratio",fieldValue:"9:16 (Portrait Widescreen)"},{nodeId:"29",fieldName:"megapixels",fieldValue:0.5}]);assert.equal(nodes.some(node=>["width","height","sampler","sigmas","vae","seed","frames"].includes(String(node.fieldName).toLowerCase())),false);assert.deepEqual(RUNNINGHUB_H3_LOCKED_MAPPING.durationConversion,{nodeId:"30",sourceNodeId:"27",ownedByWorkflow:true})});
test("RunningHub H3 submissions lock the API execution profile to Plus 48GB",()=>{const nodes=[{nodeId:"6",fieldName:"image",fieldValue:"anchor.png"}],payload=runningHubH3SubmissionPayload("secret",nodes);assert.equal(RUNNINGHUB_H3_INSTANCE_TYPE,"plus");assert.deepEqual(payload,{apiKey:"secret",workflowId:RUNNINGHUB_H3_WORKFLOW_ID,nodeInfoList:nodes,instanceType:"plus"});assert.equal(runningHubAllocatedInstanceType({data:{allocated_instance_type:"plus"}}),"plus");assert.equal(runningHubAllocatedInstanceType({data:{taskStatus:"RUNNING"}}),"")});

test("Node 29 receives exact ResolutionSelector enum labels without changing the inherited ratio",()=>{assert.equal(runningHubH3AspectRatioValue("9:16"),"9:16 (Portrait Widescreen)");assert.equal(runningHubH3AspectRatioValue("16:9 (Widescreen)"),"16:9 (Widescreen)");assert.deepEqual(Object.keys(RUNNINGHUB_H3_ASPECT_RATIO_VALUES),["1:1","2:3","3:2","3:4","4:3","9:16","16:9","21:9"]);assert.throws(()=>runningHubH3AspectRatioValue("4:5"),/does not support/)});

test("unverified registry state blocks execution without guessing graph semantics",()=>{const issues=runningHubH3MappingIssues({workflowId:RUNNINGHUB_H3_WORKFLOW_ID});assert.ok(issues.some(issue=>issue.includes("immutable H3 contract verifier")));assert.ok(issues.some(issue=>issue.includes("fingerprint")))});

test("workflow inspection records the two-pass contract and fingerprint without secrets",()=>{const inspection=inspectRunningHubH3Graph(canonicalGraph);assert.equal(inspection.nodes[7].inputs.task_type,"Hybrid");assert.equal(inspection.nodes[14].inputs.task_type,"Ref2VA");assert.equal(inspection.nodes[29].inputs.aspect_ratio,"4:3 (Standard)");assert.equal(inspection.verification.workflowContractVerified,true);assert.equal(inspection.verification.workflowContractVersion,RUNNINGHUB_H3_CONTRACT_VERSION);assert.match(inspection.verification.workflowGraphFingerprint,/^fnv1a32:/);assert.equal(JSON.stringify(inspection).includes("apiKey"),false)});

test("graph verification accepts LOW Hybrid and intentional HIGH Ref2VA two-pass semantics",()=>{assert.deepEqual(verified.issues,[]);assert.deepEqual(verified.mapping.resolution,{kind:"aspect_ratio",target:{nodeId:"29",fieldName:"aspect_ratio"},megapixels:{nodeId:"29",fieldName:"megapixels"}});assert.equal(verified.mapping.highConditioning.taskType,"Ref2VA");assert.equal(verified.mapping.highConditioning.referenceNodeId,"6");assert.equal(verified.mapping.finalNodeId,"21");assert.equal(verified.mapping.workflowContractVerified,true);assert.equal(verified.mapping.workflowGraphFingerprint,runningHubWorkflowFingerprint(canonicalGraph))});

test("graph verifier accepts RunningHub dynamic ref_images API serializations",()=>{
 const ordered=structuredClone(canonicalGraph);ordered["7"].inputs.ref_images=[["35",0]];ordered["14"].inputs.ref_images=[["6",0]];assert.deepEqual(verifyRunningHubH3Graph(ordered).issues,[]);
 const flattened=structuredClone(canonicalGraph);delete flattened["7"].inputs.ref_images;delete flattened["14"].inputs.ref_images;flattened["7"].inputs["ref_images.ref_image_0"]=["35",0];flattened["14"].inputs.ref_image_0=["6",0];assert.deepEqual(verifyRunningHubH3Graph(flattened).issues,[]);
 const dynamic=structuredClone(canonicalGraph);delete dynamic["7"].inputs.ref_images;delete dynamic["14"].inputs.ref_images;dynamic["7"].inputs.ref_images__ref_image_0={image:["35",0]};dynamic["14"].inputs.ref_images__ref_image_0={image:["6",0]};assert.deepEqual(verifyRunningHubH3Graph(dynamic).issues,[]);
});

test("contract mismatch reports the exact changed edge",()=>{const changed=structuredClone(canonicalGraph);changed["7"].inputs.width=["36",0];const result=verifyRunningHubH3Graph(changed);assert.equal(result.workflowContractVerified,false);assert.ok(result.issues.includes("Expected Node 7.width <- Node 29.width, but the edge is 36."));assert.notEqual(result.workflowGraphFingerprint,verified.workflowGraphFingerprint)});

test("Social asset identity and production queues are Batch-scoped",()=>{const key=socialBatchAssetKey(7,"content_1-asset-1");assert.equal(key,"batch-7-content_1-asset-1");assert.equal(socialBatchContentId(key),"content_1");assert.equal(socialBatchAssetPrefixFromKey(key),"batch-7-");assert.deepEqual(socialBatchAssetKeys(7,["content_1-asset-1","content_1-asset-1","content_2-asset-1"]),["batch-7-content_1-asset-1","batch-7-content_2-asset-1"]);assert.deepEqual(socialBatchProductionAssetKeys(7,{production_items:[{contentId:"content_1",assets:[{assetNumber:1},{assetNumber:2}]},{content_id:"content_2",assets:[{}]}]}),["batch-7-content_1-asset-1","batch-7-content_1-asset-2","batch-7-content_2-asset-1"])});

test("Reel first_frame resolves an approved replacement or completed upscale only inside its own Batch item",()=>{
 const key="batch-7-content_1-asset-1",approvedAt="2026-09-10T05:21:57.867Z",assets=[
  {id:91,itemKey:key,isCurrent:0,createdAt:"2026-09-07T01:00:00.000Z"},
  {id:97,itemKey:key,isCurrent:1,createdAt:"2026-09-10T05:21:11.000Z"},
  {id:200,itemKey:"batch-7-content_2-asset-1",isCurrent:1,createdAt:"2026-09-10T05:20:00.000Z"}
 ];
 assert.equal(selectApprovedReelFirstFrame({requestedId:200,approvedAnchorId:91,approvedAt,expectedItemKey:key,assets})?.id,97);
 const upscaled=[...assets.map(asset=>({...asset,isCurrent:0})),{id:98,itemKey:key,isCurrent:1,createdAt:"2026-09-11T01:00:00.000Z",sourceAssetId:97,upscaleStatus:"UPSCALE_COMPLETED"}];
 assert.equal(selectApprovedReelFirstFrame({requestedId:98,approvedAnchorId:91,approvedAt,expectedItemKey:key,assets:upscaled})?.id,98);
});

test("Reel first_frame rejects a later unapproved replacement and falls back to the approval root",()=>{
 const key="batch-7-content_1-asset-1",assets=[{id:91,itemKey:key,isCurrent:0,createdAt:"2026-09-07T01:00:00.000Z"},{id:99,itemKey:key,isCurrent:1,createdAt:"2026-09-11T01:00:00.000Z"}];
 assert.equal(selectApprovedReelFirstFrame({requestedId:99,approvedAnchorId:91,approvedAt:"2026-09-10T05:21:57.867Z",expectedItemKey:key,assets})?.id,91);
 assert.equal(selectApprovedReelFirstFrame({requestedId:91,approvedAnchorId:777,approvedAt:"2026-09-10T05:21:57.867Z",expectedItemKey:key,assets}),null);
});
test("legacy approved Content snapshots infer the same-Batch anchor from approval time",()=>{const key="batch-7-content_1-asset-1",assets=[{id:91,itemKey:key,version:3,isCurrent:0,createdAt:"2026-09-07T07:33:41.909Z"},{id:97,itemKey:key,version:4,isCurrent:1,createdAt:"2026-09-10T05:21:11.289Z"}];assert.equal(selectApprovedReelFirstFrame({requestedId:97,approvedAt:"2026-09-10T05:21:57.867Z",expectedItemKey:key,assets})?.id,97);const later=[...assets.map(asset=>({...asset,isCurrent:0})),{id:99,itemKey:key,version:5,isCurrent:1,createdAt:"2026-09-11T01:00:00.000Z"}];assert.equal(selectApprovedReelFirstFrame({requestedId:99,approvedAt:"2026-09-10T05:21:57.867Z",expectedItemKey:key,assets:later})?.id,97);assert.equal(selectApprovedReelFirstFrame({requestedId:97,approvedAt:"2026-09-10T05:21:57.867Z",expectedItemKey:"batch-6-content_1-asset-1",assets}),null)});
test("the first legacy social Batch may resolve its pre-Batch asset key without allowing cross-Batch reuse",()=>{const legacyKey="content_1-asset-1",scopedKey="batch-8-content_1-asset-1",assets=[{id:65,itemKey:legacyKey,version:4,isCurrent:0,createdAt:"2026-09-05T08:04:37.192Z"},{id:67,itemKey:legacyKey,version:5,isCurrent:1,createdAt:"2026-09-05T08:14:30.429Z",sourceAssetId:65,upscaleStatus:"UPSCALE_COMPLETED"}];assert.equal(selectApprovedReelFirstFrame({requestedId:67,approvedAt:"2026-09-06T04:16:27.860Z",expectedItemKey:scopedKey,legacyItemKey:legacyKey,assets})?.id,67);assert.equal(selectApprovedReelFirstFrame({requestedId:67,approvedAt:"2026-09-06T04:16:27.860Z",expectedItemKey:"batch-9-content_1-asset-1",assets}),null)});
test("five Reel Styles share one global registry and only registered workflows execute",()=>{assert.deepEqual(REEL_STYLES.map(style=>style.key),["IMAGE_TO_VIDEO","CINEMATIC_MULTI_SHOT","REFERENCE_MOTION","TALKING_REEL","KINETIC_GRAPHIC"]);assert.deepEqual(reelConfigurationIssues({reelStyle:"IMAGE_TO_VIDEO",workflowId:RUNNINGHUB_H3_WORKFLOW_ID}),[]);assert.match(reelConfigurationIssues({reelStyle:"TALKING_REEL"})[0],/does not have a registered execution workflow/)});

test("Reel prompt approval resolves an earlier Retake even when video submission later fails",()=>{assert.equal(unresolvedReelPromptRetake("2026-09-12T07:32:44.000Z",["2026-09-11T05:00:00.000Z",null,"2026-09-12T07:52:00.000Z"]),false);assert.equal(unresolvedReelPromptRetake("2026-09-12T08:00:00.000Z",["2026-09-12T07:52:00.000Z"]),true);assert.equal(unresolvedReelPromptRetake(null,["2026-09-12T07:52:00.000Z"]),false)});

test("partial generated Reel Retake selects only explicitly returned Content",()=>{const items=[{contentId:"content_1"},{contentId:"content_3"},{contentId:"content_4"}],feedback={"reel_video_items.content_3":"replace the beach transition","unrelated.field":"ignore"};assert.deepEqual(reelRetakeContentIds(feedback,items),["content_3"]);assert.deepEqual(reelRetakeContentIds({"reel_video_items.content_9":"wrong Batch"},items),[])});

test("partial Reel Retake IDs survive prompt revision and review submission is idempotent",()=>{const service=readFileSync(new URL("../app/api/agent-runner/service.ts",import.meta.url),"utf8"),route=readFileSync(new URL("../app/api/projects/route.ts",import.meta.url),"utf8"),workspace=readFileSync(new URL("../app/canonical-phase-workspace.tsx",import.meta.url),"utf8");assert.match(route,/retakeData\._reelRetryContentIds = retakeContentIds/);assert.match(route,/WHERE id=\? AND status='Reviewing'/);assert.match(route,/This Review decision was already submitted/);assert.match(service,/parts\[0\]==="reel_video_items"/);assert.match(service,/reelRetryContentIds=phase\.phaseKey==="reel-video-production"/);assert.match(service,/retryContentIds\.size&&!retryContentIds\.has\(contentId\)/);assert.match(workspace,/reviewSubmitting/);assert.match(workspace,/await submitReview/)});

test("provider failure retry preserves the approved Reel package and never sends it back to the LLM",()=>{const source={_reelStage:"generation",_workingDraftStatus:"Needs Correction",_validationIssues:["stale"],reviewNote:"old prompt Retake",reviewFeedback:{content_1:"old"},_videoGenerationJobIds:["job-1"],reel_video_items:[{contentId:"content_1",compiledVideoPrompt:"approved prompt",firstFrameAssetId:10,referenceAssetId:11,generationStatus:"Generation failed"}]},retry=approvedReelGenerationRetryData(source);assert.equal(retry?._reelStage,"generation");assert.equal(retry?._workingDraftStatus,undefined);assert.equal(retry?.reviewFeedback,undefined);assert.equal(retry?._videoGenerationJobIds,undefined);assert.equal(retry?.reel_video_items[0].compiledVideoPrompt,"approved prompt");assert.equal(retry?.reel_video_items[0].generationStatus,undefined);assert.equal(source._workingDraftStatus,"Needs Correction");assert.equal(approvedReelGenerationRetryData({reel_video_items:[{compiledVideoPrompt:"",firstFrameAssetId:10,referenceAssetId:11}]}),null)});

test("Reel provider completion is idempotent, retries only failed items, and Review shows current files",()=>{const service=readFileSync(new URL("../app/api/agent-runner/service.ts",import.meta.url),"utf8"),video=readFileSync(new URL("../app/api/runninghub/video.ts",import.meta.url),"utf8"),route=readFileSync(new URL("../app/api/projects/route.ts",import.meta.url),"utf8"),workspace=readFileSync(new URL("../app/canonical-phase-workspace.tsx",import.meta.url),"utf8");assert.match(video,/claimFinalization/);assert.match(video,/completedOutputForJob/);assert.match(video,/finalizationClaimedAt/);assert.match(service,/_reelRetryContentIds=failedJobs\.map/);assert.match(service,/retryContentIds\.size&&!retryContentIds\.has\(contentId\)/);assert.match(route,/empty_generated_reel_review_recovered/);assert.match(route,/status IN \('QUEUED','RUNNING','WAITING_PROVIDER','RETRY_PENDING'\)/);assert.match(workspace,/file\.itemKey === itemKey && Number\(file\.isCurrent\) !== 0/)});

test("Reel checkpoints are isolated by Batch, title and approved Anchor lineage",()=>{
 const approved={_productionBatchId:10,production_items:[{contentId:"content_1",contentType:"Reel",title:"Sunday Yoga",assets:[{assetNumber:1,visualPrompt:{approvedAnchorImage:{itemKey:"batch-10-content_1-asset-1"}}}]}]},valid={_productionBatchId:10,reel_video_items:[{contentId:"content_1",title:"Sunday Yoga",firstFrame:{itemKey:"batch-10-content_1-asset-1"}}]},oldBatch={_productionBatchId:7,reel_video_items:[{contentId:"content_1",title:"Sunday Yoga",firstFrame:{itemKey:"batch-7-content_1-asset-1"}}]},oldTitle={_productionBatchId:10,reel_video_items:[{contentId:"content_1",title:"Sunset Bicycle",firstFrame:{itemKey:"batch-10-content_1-asset-1"}}]},wrongAnchor={_productionBatchId:10,reel_video_items:[{contentId:"content_1",title:"Sunday Yoga",firstFrame:{itemKey:"batch-7-content_1-asset-1"}}]};
 assert.equal(reelCheckpointMatchesApproved(valid,approved),true);
 assert.equal(reelCheckpointMatchesApproved(oldBatch,approved),false);
 assert.equal(reelCheckpointMatchesApproved(oldTitle,approved),false);
 assert.equal(reelCheckpointMatchesApproved(wrongAnchor,approved),false);
 assert.equal(reelCheckpointMatchesApproved({_productionBatchId:10,reel_video_items:[{contentId:"content_1",title:"Sunday Yoga"}]},approved),false);
 const envelope=reelCheckpointEnvelope(valid,approved);assert.equal(envelope.productionBatchId,10);assert.equal(envelope.content._productionBatchId,10);assert.equal(reelCheckpointMatchesApproved(envelope,approved),true);
 assert.equal(reelRetakeMatchesApproved({productionBatchId:10},approved),true);assert.equal(reelRetakeMatchesApproved({productionBatchId:7},approved),false);assert.equal(reelRetakeMatchesApproved({},approved),false);
 assert.deepEqual(freshReelSetup(approved),{_productionBatchId:10,_reelStage:"style_configured",reel_video_items:[]});
});

test("approved Reel generation recovers a paused Agent instead of looping to Style Review",()=>{
 const service=readFileSync(new URL("../app/api/agent-runner/service.ts",import.meta.url),"utf8"),route=readFileSync(new URL("../app/api/projects/route.ts",import.meta.url),"utf8"),workspace=readFileSync(new URL("../app/canonical-phase-workspace.tsx",import.meta.url),"utf8"),engine=readFileSync(new URL("../app/api/autofill/engine.ts",import.meta.url),"utf8"),snapshots=readFileSync(new URL("../app/api/projects/autofill-architecture.ts",import.meta.url),"utf8");
 assert.match(service,/decision==="approve"&&reelStage==="generation"/);
 assert.match(service,/await activateAgent\(db,projectId\)/);
 assert.match(service,/reelData\._reelStage="style_configured"/);
 assert.match(service,/if\(decision==="retake"\)/);
 assert.match(route,/if\s*\(reelStage\s*===\s*"generation"\)/);
 assert.match(route,/message:\s*"Approved Reel generation resumed\."/);
 assert.match(route,/unresolvedPromptRetake/);
 assert.match(route,/reel_prompt_approved/);
 assert.match(route,/savedReelData\.promptApprovedAt/);
 assert.match(route,/approved_reel_anchor_lineage_failure_recovered/);
 assert.match(route,/reel_aspect_ratio_validation_failure_recovered/);
 assert.match(route,/approved_reel_provider_failure_recovered/);
 assert.match(service,/retryUsesApprovedPrompt:true/);
 assert.match(service,/executingApprovedReels/);
 assert.match(service,/production\._productionBatchId/);
 assert.match(snapshots,/content\._productionBatchId=batchId/);
 assert.match(snapshots,/approvedAnchorImage/);
 assert.match(service,/hasProductionDraft\|\|executingApprovedReels\?null:await generatePhaseDraft/);
 assert.match(route,/The latest Reel Prompt Retake was restored before generation/);
 assert.match(route,/Agent Standing By · Awaiting Reel Prompt Review/);
 assert.match(service,/delete reelData\.reviewFeedback/);
 assert.match(workspace,/Continue Reel Prompt Revision/);
 assert.match(workspace,/Continue Approved Reel Generation/);
 assert.match(workspace,/Approved prompt · Ready for provider/);
 assert.match(service,/Resume interrupted Agent task/);
 assert.match(workspace,/Continue Prompt Correction/);
 assert.doesNotMatch(engine,/i2vProviderPromptIssues\(prompt\)/);
 assert.match(engine,/_reelStage:"style_configured"/);
 assert.match(service,/REEL_REVISION_ITEM_LOSS_PREVENTED/);
 assert.match(route,/recoverEmptyReelWorkingDrafts/);
 assert.match(route,/empty_reel_working_draft_recovered/);
 assert.match(route,/reel_prompt_review_checkpoint/);
 assert.match(route,/cross_batch_reel_draft_quarantined/);
 assert.match(route,/quarantineCrossBatchReelDrafts/);
 assert.match(route,/const ready = promptComplete && data\._reelStage === ["']style_configured["']/);
 assert.match(engine,/current\.reel_video_items/);
});
