import{requestUserEmail}from"../../chatgpt-auth";
const socialTypes=new Set(["Internal Social Account","Client Social Account","AI Reels"]);
const parse=(value:any,fallback:any={})=>{try{return JSON.parse(value||"")}catch{return fallback}};
const titleFromFile=(name:string)=>String(name||"Final output").replace(/^v\d+[_-]/i,"").replace(/\.[^.]+$/,"").replaceAll("-"," ");

export async function GET(req:Request){
 const{env}=await import("cloudflare:workers"),db=env.DB,email=requestUserEmail(req);
 const member=await db.prepare("SELECT tier FROM members WHERE email=?").bind(email).first<any>();
 if(!member||Number(member.tier)>1)return Response.json({error:"Management access required"},{status:403});
 const [publishedResult,assetResult,snapshotResult]=await Promise.all([
  db.prepare("SELECT r.id,r.project_id AS projectId,p.client AS projectName,p.project_type_code AS projectType,p.type AS legacyType,r.platform,r.published_at AS publishedAt,r.post_url AS postUrl,r.result,r.created_at AS createdAt,c.title AS contentTitle,c.data AS contentData FROM publishing_records r JOIN projects p ON p.id=r.project_id LEFT JOIN content_items c ON c.id=r.content_item_id ORDER BY COALESCE(r.published_at,r.created_at) DESC").all(),
  db.prepare("SELECT a.id,a.project_id AS projectId,p.client AS projectName,p.project_type_code AS projectType,p.type AS legacyType,a.phase,a.item_key AS itemKey,a.version,a.storage_key AS storageKey,a.file_name AS fileName,a.mime_type AS mimeType,a.created_at AS createdAt,pr.status AS phaseStatus,pr.approved_at AS approvedAt FROM visual_asset_revisions a JOIN projects p ON p.id=a.project_id LEFT JOIN phase_records pr ON pr.project_id=a.project_id AND pr.phase_key=a.phase WHERE a.is_current=1 AND pr.status='Approved' AND ((p.project_type_code IN ('Internal Social Account','Client Social Account','AI Reels') AND a.phase IN ('content-production','reel-video-production')) OR (p.project_type_code NOT IN ('Internal Social Account','Client Social Account','AI Reels') AND a.phase='final-delivery')) ORDER BY COALESCE(pr.approved_at,a.created_at) DESC").all(),
  db.prepare("SELECT project_id AS projectId,phase_key AS phaseKey,approved_content AS content FROM approved_phase_snapshots WHERE phase_key IN ('content-production','reel-video-production','final-delivery') ORDER BY id").all()
 ]);
 const snapshots:Record<string,any>={};for(const row of snapshotResult.results as any[])snapshots[row.projectId+":"+row.phaseKey]=parse(row.content,{});
 const published=(publishedResult.results as any[]).map(row=>{const result=parse(row.result,{}),content=parse(row.contentData,{}),url=row.postUrl||result.postUrl||"";return{id:"published-"+row.id,date:row.publishedAt||row.createdAt,projectId:row.projectId,projectName:row.projectName,projectType:row.projectType||row.legacyType||"Unknown",title:row.contentTitle||content.title||result.title||"Published social content",platform:row.platform||"Social",status:"Published",version:Number(result.version||content.version||1),url,files:url?[{id:"post-"+row.id,fileName:row.platform+" post",mimeType:"text/uri-list",version:Number(result.version||content.version||1),url}]:[],outputKind:"post",fileCount:url?1:0}}).filter(row=>Boolean(row.url));
 const groups=new Map<string,any>();for(const row of assetResult.results as any[]){const contentId=String(row.itemKey||"").replace(/-asset-\d+$/,"").replace(/-video$/,"").trim(),key=row.projectId+":"+row.phase+":"+contentId,snapshot=snapshots[row.projectId+":"+row.phase]||{},items=Array.isArray(snapshot.production_items)?snapshot.production_items:Array.isArray(snapshot.reel_video_items)?snapshot.reel_video_items:[],item=items.find((candidate:any)=>String(candidate.contentId||candidate.content_id)===contentId)||{},existing=groups.get(key),file={id:"file-"+row.id,fileName:row.fileName,mimeType:row.mimeType,version:Number(row.version||1),url:"/api/uploads?file="+encodeURIComponent(row.storageKey)},entry=existing||{id:"asset-"+row.projectId+"-"+row.phase+"-"+(contentId||row.id),date:row.approvedAt||row.createdAt,projectId:row.projectId,projectName:row.projectName,projectType:row.projectType||row.legacyType||"Unknown",title:item.title||titleFromFile(row.fileName),platform:socialTypes.has(row.projectType)?"Not published":"Final delivery",status:socialTypes.has(row.projectType)?"Final Approved":"Completed",version:Number(row.version||1),url:file.url,files:[],outputKind:String(row.mimeType||"").startsWith("video/")?"video":"media",fileCount:0};entry.files.push(file);entry.fileCount=entry.files.length;entry.version=Math.max(entry.version,Number(row.version||1));if(String(row.mimeType||"").startsWith("video/")){entry.url=file.url;entry.outputKind="video"}groups.set(key,entry)}
 const publishedKeys=new Set(published.map((row:any)=>row.projectId+":"+String(row.title||"").trim().toLowerCase())),finalAssets=[...groups.values()].filter((row:any)=>row.fileCount>0&&!publishedKeys.has(row.projectId+":"+String(row.title||"").trim().toLowerCase())),outputs=[...published,...finalAssets].sort((a:any,b:any)=>String(b.date||"").localeCompare(String(a.date||"")));
 const [events,approvals,publishedCount,lastActivity]=await Promise.all([
  db.prepare("SELECT COUNT(*) AS count FROM production_events").first<any>(),
  db.prepare("SELECT COUNT(*) AS count FROM approved_phase_snapshots").first<any>(),
  db.prepare("SELECT COUNT(*) AS count FROM publishing_records").first<any>(),
  db.prepare("SELECT MAX(stamp) AS stamp FROM (SELECT MAX(created_at) AS stamp FROM production_events UNION ALL SELECT MAX(approved_at) AS stamp FROM approved_phase_snapshots UNION ALL SELECT MAX(created_at) AS stamp FROM visual_asset_revisions UNION ALL SELECT MAX(COALESCE(published_at,created_at)) AS stamp FROM publishing_records)").first<any>()
 ]);
 return Response.json({generatedAt:new Date().toISOString(),memory:{status:"Policy active",lastUpdated:lastActivity?.stamp||null,activityRecords:Number(events?.count||0),approvedRecords:Number(approvals?.count||0),publishedRecords:Number(publishedCount?.count||0),learningRule:"Approved authority, verified evidence and valid learned memory only",logBoundary:"Observability events are not generation memory"},outputs});
}
