import{referenceTypesFromSwitches}from"../../visual-prompt-architecture";

export const AGENT_FILE_RULES={
 name:"FrameFlow Agent File Grant",
 version:"1.0",
 grantTtlMinutes:120,
 referencePermission:"REFERENCE_READ",
 outputPermission:"OUTPUT_VERSION_CREATE",
 finalPermission:"MANAGEMENT_ONLY",
 stopRule:"STOP_REVOKES_ACTIVE_GRANTS",
 storageRule:"R2_VERSIONED_THEN_DRIVE_SYNC"
} as const;

const parse=(value:any,fallback:any={})=>{try{return JSON.parse(value||"")}catch{return fallback}};
async function hashToken(token:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(token));return Array.from(new Uint8Array(bytes)).map(value=>value.toString(16).padStart(2,"0")).join("")}
function bearer(req:Request){const authorization=req.headers.get("authorization")||"",header=req.headers.get("x-frameflow-agent-grant")||"";return authorization.toLowerCase().startsWith("bearer ")?authorization.slice(7).trim():header.trim()}
async function event(db:any,grantId:string,eventType:string,itemKey:string|null,eventData:any){await db.prepare("INSERT INTO agent_file_grant_events(grant_id,event_type,item_key,event_data,created_at) VALUES(?,?,?,?,?)").bind(grantId,eventType,itemKey,JSON.stringify(eventData||{}),new Date().toISOString()).run()}

export function routedContentReferenceTypes(content:any){const assets=Array.isArray(content?.assets)?content.assets:[],routed=new Set<string>();for(const asset of assets){const switches=asset?.visualPrompt?.referenceSwitches||asset?.referenceSwitches||asset?.reference_switches;if(switches&&typeof switches==="object")for(const type of referenceTypesFromSwitches(switches))routed.add(type);else for(const type of Array.isArray(asset?.referenceTypes)?asset.referenceTypes:Array.isArray(asset?.reference_types)?asset.reference_types:[])routed.add(String(type))}if(!assets.length)for(const type of Array.isArray(content?.referenceTypes)?content.referenceTypes:Array.isArray(content?.reference_types)?content.reference_types:[])routed.add(String(type));return[...routed]}
export function assertGrantContentScope(grant:any,requestedContentId:string|null){if(requestedContentId&&requestedContentId!==String(grant.contentId||""))throw Object.assign(new Error("This Agent Grant belongs to a different Content Item."),{status:403})}

export async function issueAgentFileGrant(db:any,input:{agentId:string;projectId:string;phaseKey:string;contentId:string;jobId?:string;ttlMinutes?:number;referenceTypes?:string[]}){
 if(!["content-production","reel-video-production"].includes(input.phaseKey)||!input.contentId)throw Object.assign(new Error("Agent File Grants require an exact Social production phase and Content ID."),{status:400});
 const project=await db.prepare("SELECT project_type_code AS projectType FROM projects WHERE id=?").bind(input.projectId).first<any>();
 if(!project||!["Internal Social Account","Client Social Account"].includes(project.projectType))throw Object.assign(new Error("Agent File Grants are currently limited to Social Projects."),{status:403});
 const assigned=await db.prepare("SELECT 1 AS ok FROM project_members WHERE project_id=? AND member_email=?").bind(input.projectId,input.agentId).first();if(!assigned)throw Object.assign(new Error("This Agent is not assigned to the Project."),{status:403});
 const phase=await db.prepare("SELECT data,status FROM phase_records WHERE project_id=? AND phase_key=?").bind(input.projectId,input.phaseKey).first<any>();if(!phase)throw Object.assign(new Error("Target production phase was not found."),{status:404});if(["Approved","Reviewing","Client Reviewing","Locked"].includes(phase.status))throw Object.assign(new Error("Agent file access is only available while production is active."),{status:409});
 const phaseData=parse(phase.data,{}),phaseItems=input.phaseKey==="content-production"?phaseData.production_items:phaseData.reel_video_items,content=(Array.isArray(phaseItems)?phaseItems:[]).find((item:any)=>String(item.contentId||item.content_id)===input.contentId);if(!content)throw Object.assign(new Error("Target Content was not found in this production phase."),{status:404});
 const enabledTypes=routedContentReferenceTypes(content),requested=Array.isArray(input.referenceTypes)?input.referenceTypes.map(String):enabledTypes,referenceTypes=requested.filter(type=>enabledTypes.includes(type)),assets=await db.prepare("SELECT id,item_key AS itemKey FROM visual_asset_revisions WHERE project_id=? AND phase='references' AND is_current=1").bind(input.projectId).all(),readAssetIds=(assets.results as any[]).filter(asset=>referenceTypes.includes(String(asset.itemKey||"").replace(/-reference$/,""))).map(asset=>Number(asset.id)),writeItemKeys=input.phaseKey==="content-production"?(Array.isArray(content.assets)?content.assets:[]).map((asset:any,index:number)=>input.contentId+"-asset-"+Number(asset.assetNumber||asset.asset_number||index+1)):[input.contentId+"-video"];
 if(input.phaseKey==="reel-video-production"){const upscaled=await db.prepare("SELECT v.id FROM visual_asset_revisions v JOIN asset_upscale_jobs u ON u.derived_asset_id=v.id AND u.status='UPSCALE_COMPLETED' WHERE v.project_id=? AND v.phase='content-production' AND v.item_key LIKE ? AND v.is_current=1 ORDER BY v.item_key").bind(input.projectId,input.contentId+"-asset-%").all();readAssetIds.push(...(upscaled.results as any[]).map(row=>Number(row.id)).filter(Boolean))}
 if(!writeItemKeys.length)throw Object.assign(new Error("This Content has no approved output slots."),{status:409});
 const now=new Date(),ttl=Math.max(15,Math.min(240,Number(input.ttlMinutes||AGENT_FILE_RULES.grantTtlMinutes))),expiresAt=new Date(now.getTime()+ttl*60000).toISOString(),id="grant_"+crypto.randomUUID(),jobId=input.jobId||"job_"+crypto.randomUUID(),token="ffg_"+crypto.randomUUID().replaceAll("-","")+crypto.randomUUID().replaceAll("-",""),tokenHash=await hashToken(token);
 await db.prepare("UPDATE agent_file_grants SET status='Revoked',revoked_at=? WHERE project_id=? AND phase_key=? AND content_id=? AND status='Active'").bind(now.toISOString(),input.projectId,input.phaseKey,input.contentId).run();
 await db.prepare("INSERT INTO agent_file_grants(id,token_hash,job_id,agent_id,project_id,phase_key,content_id,read_asset_ids,write_item_keys,status,expires_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,'Active',?,?)").bind(id,tokenHash,jobId,input.agentId,input.projectId,input.phaseKey,input.contentId,JSON.stringify(readAssetIds),JSON.stringify(writeItemKeys),expiresAt,now.toISOString()).run();
 await event(db,id,"GRANT_ISSUED",null,{rules:AGENT_FILE_RULES,referenceTypes,readAssetIds,writeItemKeys,expiresAt});
 return{grantId:id,jobId,token,expiresAt,rules:AGENT_FILE_RULES,referenceTypes,readAssetIds,writeItemKeys};
}

export async function authorizeAgentFileGrant(db:any,req:Request){
 const token=bearer(req);if(!token)throw Object.assign(new Error("Agent File Grant is required."),{status:401});const tokenHash=await hashToken(token),grant=await db.prepare("SELECT id,job_id AS jobId,agent_id AS agentId,project_id AS projectId,phase_key AS phaseKey,content_id AS contentId,read_asset_ids AS readAssetIds,write_item_keys AS writeItemKeys,status,expires_at AS expiresAt FROM agent_file_grants WHERE token_hash=?").bind(tokenHash).first<any>();if(!grant)throw Object.assign(new Error("Agent File Grant is invalid."),{status:401});if(grant.status!=="Active")throw Object.assign(new Error("Agent File Grant is not active."),{status:403});if(Date.parse(grant.expiresAt)<=Date.now()){await db.prepare("UPDATE agent_file_grants SET status='Expired' WHERE id=?").bind(grant.id).run();throw Object.assign(new Error("Agent File Grant expired."),{status:403})}grant.readAssetIds=parse(grant.readAssetIds,[]);grant.writeItemKeys=parse(grant.writeItemKeys,[]);await db.prepare("UPDATE agent_file_grants SET last_used_at=? WHERE id=?").bind(new Date().toISOString(),grant.id).run();return grant
}

export async function grantManifest(db:any,grant:any){const ids=(grant.readAssetIds||[]).map(Number).filter(Boolean);let references:any[]=[];if(ids.length){const marks=ids.map(()=>"?").join(","),rows=await db.prepare("SELECT v.id,v.phase,v.item_key AS itemKey,v.version,v.file_name AS fileName,v.mime_type AS mimeType,v.size_bytes AS sizeBytes,v.drive_sync_status AS driveSyncStatus,CASE WHEN u.derived_asset_id=v.id THEN 'UPSCALED_MASTER' ELSE 'PROJECT_REFERENCE' END AS assetPurpose FROM visual_asset_revisions v LEFT JOIN asset_upscale_jobs u ON u.derived_asset_id=v.id AND u.status='UPSCALE_COMPLETED' WHERE v.id IN ("+marks+") AND v.project_id=? AND v.is_current=1 AND (v.phase='references' OR (v.phase='content-production' AND u.content_id=?)) ORDER BY v.phase,v.item_key,v.id").bind(...ids,grant.projectId,grant.contentId).all();references=rows.results as any[]}return{schema:"frameflow.agent-file-manifest.v1",grant:{id:grant.id,jobId:grant.jobId,agentId:grant.agentId,projectId:grant.projectId,phaseKey:grant.phaseKey,contentId:grant.contentId,expiresAt:grant.expiresAt},rules:AGENT_FILE_RULES,references:references.map(asset=>({...asset,referenceRole:asset.assetPurpose==="UPSCALED_MASTER"?"approved-upscaled-source":"project-reference",download:{method:"GET",path:"/api/agent-files?action=download&assetId="+asset.id+"&contentId="+encodeURIComponent(grant.contentId),authorization:"Bearer <grant token>"}})),writeTargets:(grant.writeItemKeys||[]).map((itemKey:string)=>({itemKey,folderRule:grant.phaseKey+"/"+grant.contentId+"/"+itemKey+"/v{version}",upload:"chunked",authorization:"Bearer <grant token>"}))}}

export async function recordGrantEvent(db:any,grantId:string,eventType:string,itemKey:string|null,eventData:any){return event(db,grantId,eventType,itemKey,eventData)}
export async function revokeProjectAgentFileGrants(db:any,projectId:string,reason:string){const now=new Date().toISOString(),rows=await db.prepare("SELECT id FROM agent_file_grants WHERE project_id=? AND status='Active'").bind(projectId).all();await db.prepare("UPDATE agent_file_grants SET status='Revoked',revoked_at=? WHERE project_id=? AND status='Active'").bind(now,projectId).run();for(const row of rows.results as any[])await event(db,row.id,"GRANT_REVOKED",null,{reason});return Number(rows.results.length)}
export async function completePhaseAgentFileGrants(db:any,projectId:string,phaseKey:string){const now=new Date().toISOString();await db.prepare("UPDATE agent_file_grants SET status='Completed',revoked_at=? WHERE project_id=? AND phase_key=? AND status='Active'").bind(now,projectId,phaseKey).run()}
