export const RUNNINGHUB_QWEN_IMAGE_WORKFLOW_ID="2102592525269012481" as const;
export const RUNNINGHUB_QWEN_IMAGE_MODEL="Qwen Image 2.1" as const;
export const RUNNINGHUB_QWEN_IMAGE_CONTRACT_VERSION="RH-QWEN-I2I-2102592525269012481-V2" as const;
export const RUNNINGHUB_QWEN_MAX_REFERENCES=6 as const;

export type RunningHubImageTarget={nodeId:string;fieldName:string};
export type RunningHubImageSlot={slot:number;encoderFieldName:string;target:RunningHubImageTarget};
export type RunningHubImageMapping={
 workflowId:typeof RUNNINGHUB_QWEN_IMAGE_WORKFLOW_ID;
 workflowContractVerified:boolean;
 workflowContractVersion:string;
 workflowGraphFingerprint:string;
 prompt:RunningHubImageTarget;
 promptEnhancer:{nodeId:string;systemPrompt:RunningHubImageTarget;extraInstructions:RunningHubImageTarget;temperature:RunningHubImageTarget}|null;
 aspectRatio:RunningHubImageTarget;
 imageSlots:RunningHubImageSlot[];
 finalNodeId:string;
};

const normalize=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]/g,"");
const isLink=(value:any)=>Array.isArray(value)&&value.length>1&&["string","number"].includes(typeof value[0])&&["string","number"].includes(typeof value[1]);
const stable=(value:any):string=>Array.isArray(value)?`[${value.map(stable).join(",")}]`:value&&typeof value==="object"?`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`:JSON.stringify(value);
export function runningHubImageWorkflowFingerprint(graph:any){const value=stable(graph);let hash=2166136261;for(let index=0;index<value.length;index++){hash^=value.charCodeAt(index);hash=Math.imul(hash,16777619)}return`fnv1a32:${(hash>>>0).toString(16).padStart(8,"0")}:${value.length}`}

export function parseRunningHubImageWorkflowPrompt(result:any){const raw=result?.data?.prompt??result?.prompt??result?.data;if(raw&&typeof raw==="object")return raw;if(typeof raw!=="string")throw new Error("RunningHub Qwen workflow inspection returned no API-format prompt.");try{return JSON.parse(raw)}catch{throw new Error("RunningHub Qwen workflow inspection returned invalid API-format JSON.")}}

export function inspectRunningHubQwenImageGraph(graph:any){
 const issues:string[]=[],entries=Object.entries(graph||{}) as [string,any][];
 const encoder=entries.find(([,node])=>/TextEncodeQwenImage21/i.test(String(node?.class_type||"")));
 const promptNode=entries.find(([,node])=>/PrimitiveStringMultiline/i.test(String(node?.class_type||""))&&Object.prototype.hasOwnProperty.call(node?.inputs||{},"value"));
 const resolutionNode=entries.find(([,node])=>/ResolutionSelector/i.test(String(node?.class_type||""))&&Object.prototype.hasOwnProperty.call(node?.inputs||{},"aspect_ratio"));
 const outputNode=entries.find(([,node])=>/SaveImage/i.test(String(node?.class_type||"")));
 const enhancerNode=entries.find(([,node])=>/QwenPromptEnhancer/i.test(String(node?.class_type||"")));
 if(!encoder)issues.push("TextEncodeQwenImage21 is missing.");
 if(!promptNode)issues.push("Editable PrimitiveStringMultiline prompt node is missing.");
 if(!resolutionNode)issues.push("Editable ResolutionSelector.aspect_ratio is missing.");
 if(!outputNode)issues.push("SaveImage output node is missing.");
 if(enhancerNode){const inputs=enhancerNode[1]?.inputs||{};for(const field of["system_prompt","extra_instructions","temperature"])if(!Object.prototype.hasOwnProperty.call(inputs,field))issues.push(`Prompt enhancer ${enhancerNode[0]}.${field} is not editable.`);if(!isLink(inputs.user_idea)||String(inputs.user_idea[0])!==String(promptNode?.[0]||""))issues.push("Prompt enhancer user_idea is not linked to the editable FrameFlow prompt node.");if(encoder&&!isLink(encoder[1]?.inputs?.prompt))issues.push("Qwen encoder prompt is not linked to the prompt enhancer output.")}
 const slots:RunningHubImageSlot[]=[];
 for(const[field,value]of Object.entries(encoder?.[1]?.inputs||{})){
  const match=normalize(field).match(/^imagesimage([1-6])$/);if(!match||!isLink(value))continue;
  const slot=Number(match[1]),nodeId=String((value as any[])[0]),loader=graph?.[nodeId];
  if(String(loader?.class_type||"")!=="LoadImage"||!Object.prototype.hasOwnProperty.call(loader?.inputs||{},"image")){issues.push(`Qwen <image${slot}> does not resolve to an editable LoadImage.image node.`);continue}
  slots.push({slot,encoderFieldName:field,target:{nodeId,fieldName:"image"}});
 }
 slots.sort((a,b)=>a.slot-b.slot);
 if(!slots.length)issues.push("No connected Qwen reference-image slots were found.");
 if(slots.length>RUNNINGHUB_QWEN_MAX_REFERENCES)issues.push(`Workflow exposes ${slots.length} image slots; FrameFlow supports at most ${RUNNINGHUB_QWEN_MAX_REFERENCES}.`);
 const fingerprint=runningHubImageWorkflowFingerprint(graph),mapping:RunningHubImageMapping={workflowId:RUNNINGHUB_QWEN_IMAGE_WORKFLOW_ID,workflowContractVerified:issues.length===0,workflowContractVersion:RUNNINGHUB_QWEN_IMAGE_CONTRACT_VERSION,workflowGraphFingerprint:fingerprint,prompt:{nodeId:String(promptNode?.[0]||""),fieldName:"value"},promptEnhancer:enhancerNode?{nodeId:String(enhancerNode[0]),systemPrompt:{nodeId:String(enhancerNode[0]),fieldName:"system_prompt"},extraInstructions:{nodeId:String(enhancerNode[0]),fieldName:"extra_instructions"},temperature:{nodeId:String(enhancerNode[0]),fieldName:"temperature"}}:null,aspectRatio:{nodeId:String(resolutionNode?.[0]||""),fieldName:"aspect_ratio"},imageSlots:slots.slice(0,RUNNINGHUB_QWEN_MAX_REFERENCES),finalNodeId:String(outputNode?.[0]||"")};
 return{mapping,issues,workflowId:RUNNINGHUB_QWEN_IMAGE_WORKFLOW_ID,configuredImageSlots:[1,2,3,4,5,6],configuredReferenceCapacity:RUNNINGHUB_QWEN_MAX_REFERENCES,activeImageSlots:slots.map(slot=>slot.slot),activeReferenceCapacity:slots.length,connectedImageSlots:slots.map(slot=>slot.slot),referenceCapacity:RUNNINGHUB_QWEN_MAX_REFERENCES,workflowContractVerified:issues.length===0,workflowContractVersion:RUNNINGHUB_QWEN_IMAGE_CONTRACT_VERSION,workflowGraphFingerprint:fingerprint};
}

export function normalizeRunningHubImageMapping(value:any):RunningHubImageMapping{const raw=value&&typeof value==="object"?value:{},slots=Array.isArray(raw.imageSlots)?raw.imageSlots.filter((slot:any)=>Number(slot?.slot)>=1&&Number(slot?.slot)<=6&&slot?.target?.nodeId).map((slot:any)=>({slot:Number(slot.slot),encoderFieldName:String(slot.encoderFieldName||`images.image_${slot.slot}`),target:{nodeId:String(slot.target.nodeId),fieldName:String(slot.target.fieldName||"image")}})).sort((a:any,b:any)=>a.slot-b.slot):[],enhancer=raw.promptEnhancer?.nodeId?{nodeId:String(raw.promptEnhancer.nodeId),systemPrompt:{nodeId:String(raw.promptEnhancer.nodeId),fieldName:"system_prompt"},extraInstructions:{nodeId:String(raw.promptEnhancer.nodeId),fieldName:"extra_instructions"},temperature:{nodeId:String(raw.promptEnhancer.nodeId),fieldName:"temperature"}}:null;return{workflowId:RUNNINGHUB_QWEN_IMAGE_WORKFLOW_ID,workflowContractVerified:raw.workflowContractVerified===true,workflowContractVersion:String(raw.workflowContractVersion||""),workflowGraphFingerprint:String(raw.workflowGraphFingerprint||""),prompt:{nodeId:String(raw.prompt?.nodeId||""),fieldName:String(raw.prompt?.fieldName||"value")},promptEnhancer:enhancer,aspectRatio:{nodeId:String(raw.aspectRatio?.nodeId||""),fieldName:String(raw.aspectRatio?.fieldName||"aspect_ratio")},imageSlots:slots.slice(0,6),finalNodeId:String(raw.finalNodeId||"")}}
export function runningHubImageMappingIssues(value:any){const mapping=normalizeRunningHubImageMapping(value),issues:string[]=[];if(!mapping.workflowContractVerified)issues.push(`Workflow ${RUNNINGHUB_QWEN_IMAGE_WORKFLOW_ID} has not passed its graph verifier.`);if(mapping.workflowContractVersion!==RUNNINGHUB_QWEN_IMAGE_CONTRACT_VERSION)issues.push(`Expected contract ${RUNNINGHUB_QWEN_IMAGE_CONTRACT_VERSION}.`);if(!mapping.workflowGraphFingerprint)issues.push("Verified workflow fingerprint is missing.");if(!mapping.prompt.nodeId)issues.push("Prompt mapping is missing.");if(!mapping.aspectRatio.nodeId)issues.push("Aspect-ratio mapping is missing.");if(!mapping.finalNodeId)issues.push("Final SaveImage mapping is missing.");if(!mapping.imageSlots.length)issues.push("No verified image slots are available.");return issues}

const roleKey=(value:any)=>String(value||"PROJECT_REFERENCE").replace(/-reference$/i,"").replaceAll("-","_").toUpperCase();
export function referenceUse(role:any){const key=roleKey(role);if(key==="APPROVED_FIRST_IMAGE"||key==="APPROVED_ANCHOR")return{role:"Approved content anchor",use:"preserve the approved subject, product, wardrobe, environment and continuity that are visible",avoid:"do not copy its camera angle or pose unless the shot direction explicitly requires it"};if(key.includes("CHARACTER"))return{role:"Character identity",use:"preserve the same person's facial identity, age range, skin tone and defining features",avoid:"do not inherit pose, crop, wardrobe, lighting or background unless separately requested"};if(key.includes("PRODUCT"))return{role:"Product identity",use:"preserve exact geometry, proportions, material, color, construction and approved variant",avoid:"do not redesign the product or import the reference staging"};if(key.includes("LOGO")||key.includes("BRAND")||key.includes("PACKAG"))return{role:"Logo and brand",use:"preserve exact approved logo geometry, spelling, color, label and placement",avoid:"do not invent, paraphrase or duplicate brand text"};if(key.includes("PROP")||key.includes("OBJECT"))return{role:"Prop identity",use:"preserve the exact object identity, scale, geometry and material",avoid:"do not import unrelated subjects or background"};if(key.includes("ENVIRONMENT")||key.includes("LOCATION")||key.includes("SCENE"))return{role:"Environment",use:"preserve the approved location identity, spatial layout, architecture and material palette",avoid:"do not import people, pose or wardrobe from this image"};return{role:"Selected project reference",use:"preserve only the explicitly relevant approved visual facts",avoid:"do not import unrelated pose, crop, lighting, background, people or objects"}}

export function compileQwenReferencePrompt(basePrompt:string,assets:any[],slots:RunningHubImageSlot[]){if(assets.length>RUNNINGHUB_QWEN_MAX_REFERENCES)throw new Error(`Qwen image generation accepts at most ${RUNNINGHUB_QWEN_MAX_REFERENCES} references.`);if(assets.length>slots.length)throw Object.assign(new Error(`Workflow ${RUNNINGHUB_QWEN_IMAGE_WORKFLOW_ID} is designed for six references, but its current API-format graph has only ${slots.length} reference switch${slots.length===1?"":"es"} enabled. Turn on enough 图片1…图片6 switches in RunningHub, save the workflow, verify it again, then retry.`),{code:"RUNNINGHUB_QWEN_REFERENCE_SWITCH_DISABLED"});const manifest=assets.map((asset,index)=>{const slot=slots[index],explicit=asset?.referenceUse,rule=explicit&&typeof explicit==="object"&&explicit.role&&explicit.use&&explicit.avoid?{role:String(explicit.role),use:String(explicit.use),avoid:String(explicit.avoid)}:referenceUse(asset.referenceRole||asset.itemKey);return`<image${slot.slot}> — ${rule.role}. USE ONLY TO: ${rule.use}. DO NOT: ${rule.avoid}.`});return["REFERENCE IMAGE MAP (each image has one explicit purpose; never blend or swap roles):",...manifest,"","FINAL IMAGE DIRECTION:",String(basePrompt||"").trim()].join("\n")}

export function runningHubQwenAspectRatio(value:any){const raw=String(value||"1:1").trim(),labels:Record<string,string>={"1:1":"1:1 (Square)","2:3":"2:3 (Portrait Photo)","3:2":"3:2 (Photo)","3:4":"3:4 (Portrait Standard)","4:3":"4:3 (Standard)","9:16":"9:16 (Portrait Widescreen)","16:9":"16:9 (Widescreen)","21:9":"21:9 (Ultrawide)"};return labels[raw]||raw}
export function runningHubQwenNodeInfo(mappingInput:any,input:{fileNames:string[];prompt:string;aspectRatio:string}){const mapping=normalizeRunningHubImageMapping(mappingInput),issues=runningHubImageMappingIssues(mapping);if(issues.length)throw new Error(issues.join(" "));if(input.fileNames.length>mapping.imageSlots.length)throw Object.assign(new Error(`Verified Qwen workflow capacity is ${mapping.imageSlots.length}; received ${input.fileNames.length} references.`),{code:"RUNNINGHUB_QWEN_REFERENCE_CAPACITY"});const enhancer=mapping.promptEnhancer?[{nodeId:mapping.promptEnhancer.systemPrompt.nodeId,fieldName:mapping.promptEnhancer.systemPrompt.fieldName,fieldValue:"You are FrameFlow's reference-aware Qwen Image 2.1 prompt compiler. Preserve every <imageN> label and its USE ONLY TO / DO NOT instruction. Never merge, renumber, swap, omit or broaden reference roles. Improve only the FINAL IMAGE DIRECTION into precise professional English covering subject, action, composition, lens, lighting, materials and realism. Keep all identity, product, logo, continuity and negative constraints. Output only the final prompt, maximum 350 words."},{nodeId:mapping.promptEnhancer.extraInstructions.nodeId,fieldName:mapping.promptEnhancer.extraInstructions.fieldName,fieldValue:"Reference-role lines are authoritative P0 constraints and must remain explicit in the output."},{nodeId:mapping.promptEnhancer.temperature.nodeId,fieldName:mapping.promptEnhancer.temperature.fieldName,fieldValue:0.3}]:[];return[...input.fileNames.map((fileName,index)=>({nodeId:mapping.imageSlots[index].target.nodeId,fieldName:mapping.imageSlots[index].target.fieldName,fieldValue:fileName})),{nodeId:mapping.prompt.nodeId,fieldName:mapping.prompt.fieldName,fieldValue:input.prompt},...enhancer,{nodeId:mapping.aspectRatio.nodeId,fieldName:mapping.aspectRatio.fieldName,fieldValue:runningHubQwenAspectRatio(input.aspectRatio)}]}
