import{RUNNINGHUB_BASE_URL}from"./service";
import{compileQwenReferencePrompt,runningHubQwenNodeInfo,RUNNINGHUB_QWEN_IMAGE_MODEL,RUNNINGHUB_QWEN_IMAGE_WORKFLOW_ID}from"./image-contract";
import{ensureRunningHubImageContract}from"./image-registry";

const now=()=>new Date().toISOString(),safe=(error:any)=>String(error?.message||error||"RunningHub Qwen image generation failed.").slice(0,1200);
const providerStatus=(value:any)=>String(value?.taskStatus||value?.status||value?.task_status||value||"").trim().toUpperCase();
const succeeded=(value:string)=>["SUCCESS","SUCCEEDED","COMPLETED","COMPLETE","FINISHED"].includes(value),failed=(value:string)=>["FAILED","FAILURE","ERROR","CANCELLED","CANCELED"].includes(value);
const extension=(mime:string)=>mime==="image/jpeg"?"jpg":mime==="image/webp"?"webp":"png";
async function providerJson(url:string,init:RequestInit){const response=await fetch(url,init),result:any=await response.json().catch(()=>({}));if(!response.ok||Number(result?.code||0)!==0)throw Object.assign(new Error(String(result?.msg||result?.message||`RunningHub returned HTTP ${response.status}.`)),{code:String(result?.code||response.status)});return result}
async function uploadAsset(env:any,asset:any,apiKey:string){if(!asset?.storageKey||!String(asset?.mimeType||"").startsWith("image/"))throw new Error(`Reference ${asset?.fileName||asset?.id||"image"} is not a valid stored image.`);const object=await env.BUCKET.get(String(asset.storageKey));if(!object)throw new Error(`Reference image ${asset.fileName||asset.id} is missing from private storage.`);const bytes=new Uint8Array(await object.arrayBuffer()),form=new FormData();form.append("file",new Blob([bytes],{type:asset.mimeType}),String(asset.fileName||"reference.png"));const result=await providerJson(`${RUNNINGHUB_BASE_URL}/openapi/v2/media/upload/binary`,{method:"POST",headers:{authorization:`Bearer ${apiKey}`},body:form}),fileName=String(result?.data?.fileName||result?.data?.file_name||result?.fileName||"");if(!fileName)throw new Error("RunningHub reference upload returned no fileName.");return fileName}

export async function dispatchRunningHubQwenImage(db:any,env:any,job:any,update:any){
 let executionMeta:any={...(job.outputPayload||{}),workflowId:RUNNINGHUB_QWEN_IMAGE_WORKFLOW_ID};
 try{
  const contract=await ensureRunningHubImageContract(db,env),apiKey=String(contract.saved.secret||"").trim(),mapping=contract.mapping,prior=job.outputPayload||{},assets=(Array.isArray(job.inputAssets)?job.inputAssets:[]).slice(0,6);
  if(!String(job.inputPayload.prompt||"").trim())throw new Error("Qwen image generation requires a compiled FrameFlow prompt.");
  if(assets.length>mapping.imageSlots.length)throw Object.assign(new Error(`This six-reference Qwen workflow currently has only ${mapping.imageSlots.length} reference switch${mapping.imageSlots.length===1?"":"es"} enabled in its API-format graph (${mapping.imageSlots.map((slot:any)=>`image_${slot.slot}`).join(", ")||"none"}). The job selected ${assets.length}; turn on enough 图片1…图片6 switches in RunningHub, save the workflow, verify it again, then retry.`),{code:"RUNNINGHUB_QWEN_REFERENCE_SWITCH_DISABLED"});
  if(!prior.taskId){
   await update(db,job.id,"RUNNING","system:runninghub",{provider:"runninghub",model:RUNNINGHUB_QWEN_IMAGE_MODEL,outputPayload:executionMeta});
   const fileNames=[];for(const asset of assets)fileNames.push(await uploadAsset(env,asset,apiKey));
   const compiledPrompt=compileQwenReferencePrompt(String(job.inputPayload.prompt||""),assets,mapping.imageSlots),nodeInfoList=runningHubQwenNodeInfo(mapping,{fileNames,prompt:compiledPrompt,aspectRatio:String(job.inputPayload.aspect_ratio||"1:1")}),created=await providerJson(`${RUNNINGHUB_BASE_URL}/task/openapi/create`,{method:"POST",headers:{authorization:`Bearer ${apiKey}`,"content-type":"application/json"},body:JSON.stringify({apiKey,workflowId:RUNNINGHUB_QWEN_IMAGE_WORKFLOW_ID,nodeInfoList})}),taskId=String(created?.data?.taskId||created?.data?.task_id||created?.taskId||"");if(!taskId)throw new Error("RunningHub Qwen workflow submission returned no taskId.");
   const submittedAt=now(),referenceManifest=assets.map((asset:any,index:number)=>({slot:mapping.imageSlots[index].slot,assetId:asset.id||null,fileName:asset.fileName||null,role:asset.referenceRole||asset.itemKey||"PROJECT_REFERENCE"}));executionMeta={workflowId:RUNNINGHUB_QWEN_IMAGE_WORKFLOW_ID,taskId,providerStatus:"SUBMITTED",pollCount:0,submittedAt,referenceManifest,referenceCount:assets.length,connectedImageSlots:mapping.imageSlots.map((slot:any)=>slot.slot)};await db.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(job.projectId,"image_generation_started","system:runninghub",JSON.stringify({jobId:job.id,contentId:job.contentId,workflowId:RUNNINGHUB_QWEN_IMAGE_WORKFLOW_ID,taskId,submittedAt,aspectRatio:job.inputPayload.aspect_ratio||"1:1",referenceManifest,nodeInfoList:nodeInfoList.map((node:any)=>({nodeId:node.nodeId,fieldName:node.fieldName,fieldValue:node.nodeId===mapping.prompt.nodeId?"[compiledPromptWithReferenceMap]":node.fieldValue}))}),submittedAt).run();return update(db,job.id,"WAITING_PROVIDER","system:runninghub",{provider:"runninghub",model:RUNNINGHUB_QWEN_IMAGE_MODEL,outputPayload:executionMeta,error:null})
  }
  let statusResult:any;try{statusResult=await providerJson(`${RUNNINGHUB_BASE_URL}/task/openapi/status`,{method:"POST",headers:{authorization:`Bearer ${apiKey}`,"content-type":"application/json"},body:JSON.stringify({apiKey,taskId:prior.taskId})})}catch(error:any){return update(db,job.id,"WAITING_PROVIDER","system:runninghub",{provider:"runninghub",model:RUNNINGHUB_QWEN_IMAGE_MODEL,outputPayload:{...executionMeta,providerStatus:"STATUS_CHECK_RETRY",statusCheckError:safe(error),pollCount:Number(prior.pollCount||0)+1},error:null})}
  const status=providerStatus(statusResult?.data??statusResult);if(failed(status))throw new Error(String(statusResult?.data?.error||statusResult?.data?.failedReason||statusResult?.error?.message||`RunningHub Qwen task ended with ${status}.`));if(!succeeded(status))return update(db,job.id,"WAITING_PROVIDER","system:runninghub",{provider:"runninghub",model:RUNNINGHUB_QWEN_IMAGE_MODEL,outputPayload:{...executionMeta,providerStatus:status||"GENERATING",pollCount:Number(prior.pollCount||0)+1},error:null});
  let outputResult:any;try{outputResult=await providerJson(`${RUNNINGHUB_BASE_URL}/task/openapi/outputs`,{method:"POST",headers:{authorization:`Bearer ${apiKey}`,"content-type":"application/json"},body:JSON.stringify({apiKey,taskId:prior.taskId})})}catch(error:any){return update(db,job.id,"WAITING_PROVIDER","system:runninghub",{provider:"runninghub",model:RUNNINGHUB_QWEN_IMAGE_MODEL,outputPayload:{...executionMeta,providerStatus:"FINISHED_OUTPUT_RETRY",outputCheckError:safe(error)},error:null})}
  const outputs=Array.isArray(outputResult?.data)?outputResult.data:[],final=outputs.find((item:any)=>String(item?.nodeId||item?.node_id||"")===mapping.finalNodeId)||outputs.find((item:any)=>String(item?.fileType||item?.file_type||"").toLowerCase().includes("image")),fileUrl=String(final?.fileUrl||final?.file_url||"");if(!fileUrl)return update(db,job.id,"WAITING_PROVIDER","system:runninghub",{provider:"runninghub",model:RUNNINGHUB_QWEN_IMAGE_MODEL,outputPayload:{...executionMeta,providerStatus:"FINISHED_OUTPUT_PENDING",finalNodeId:mapping.finalNodeId},error:null});
  const response=await fetch(fileUrl);if(!response.ok)return update(db,job.id,"WAITING_PROVIDER","system:runninghub",{provider:"runninghub",model:RUNNINGHUB_QWEN_IMAGE_MODEL,outputPayload:{...executionMeta,providerStatus:"FINAL_IMAGE_DOWNLOAD_RETRY",downloadStatus:response.status},error:null});const bytes=new Uint8Array(await response.arrayBuffer()),reported=String(response.headers.get("content-type")||final?.fileType||"image/png").split(";")[0].toLowerCase(),mime=reported.startsWith("image/")?reported:"image/png",phase=String(job.inputPayload.phase||"content-production"),itemKey=String(job.inputPayload.item_key||job.inputPayload.itemKey||job.contentId||"generated-image"),versionRow=await db.prepare("SELECT COALESCE(MAX(version),0) AS version FROM visual_asset_revisions WHERE project_id=? AND phase=? AND item_key=?").bind(job.projectId,phase,itemKey).first<any>(),version=Number(versionRow?.version||0)+1,ext=extension(mime),storageKey=`projects/${job.projectId}/${phase}/${itemKey}/v${version}-${Date.now()}-runninghub-qwen21.${ext}`,fileName=`${itemKey}_v${version}.${ext}`,stamp=now();await env.BUCKET.put(storageKey,bytes,{httpMetadata:{contentType:mime}});await db.batch([db.prepare("UPDATE visual_asset_revisions SET is_current=0 WHERE project_id=? AND phase=? AND item_key=?").bind(job.projectId,phase,itemKey),db.prepare("INSERT INTO visual_asset_revisions(project_id,phase,item_key,version,storage_key,file_name,mime_type,size_bytes,uploaded_by,is_current,drive_sync_status,created_at) VALUES(?,?,?,?,?,?,?,?,?,1,'Pending Drive sync',?)").bind(job.projectId,phase,itemKey,version,storageKey,fileName,mime,bytes.byteLength,"system:runninghub",stamp),db.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(job.projectId,"image_generation_completed","system:runninghub",JSON.stringify({jobId:job.id,contentId:job.contentId,workflowId:RUNNINGHUB_QWEN_IMAGE_WORKFLOW_ID,taskId:prior.taskId,finalNodeId:mapping.finalNodeId,version,referenceManifest:prior.referenceManifest||[]}),stamp)]);
  let driveSynced=false;try{const{syncStoredAssetToDrive}=await import("../google-drive/drive");await syncStoredAssetToDrive(job.projectId,phase,storageKey,`v${version}_${fileName}`,mime);driveSynced=true;await db.prepare("UPDATE visual_asset_revisions SET drive_sync_status='Synced to Drive' WHERE storage_key=?").bind(storageKey).run()}catch(error:any){await db.prepare("UPDATE visual_asset_revisions SET drive_sync_status=? WHERE storage_key=?").bind(`Drive retry needed: ${safe(error)}`,storageKey).run()}const output={storageKey,fileName,mimeType:mime,version,url:"/api/uploads?file="+encodeURIComponent(storageKey),driveSynced};return update(db,job.id,"SUCCEEDED","system:runninghub",{provider:"runninghub",model:RUNNINGHUB_QWEN_IMAGE_MODEL,outputAssets:[output],outputPayload:{...executionMeta,providerStatus:"SUCCEEDED",finalNodeId:mapping.finalNodeId,version,driveSynced},error:null})
 }catch(error:any){return update(db,job.id,"FAILED","system:runninghub",{provider:"runninghub",model:RUNNINGHUB_QWEN_IMAGE_MODEL,outputPayload:executionMeta,error:safe(error)})}
}
