import{loadIntegration}from"../integrations/_lib";
import{RUNNINGHUB_BASE_URL}from"./service";
import{imageDimensions,RUNNINGHUB_FINAL_NODE_ID,RUNNINGHUB_UPSCALE_WORKFLOW_ID,runningHubNodeInfo}from"./contract";
export{RUNNINGHUB_UPSCALE_WORKFLOW_ID}from"./contract";

const now=()=>new Date().toISOString();
const safeMessage=(error:any)=>String(error?.message||error||"RunningHub Upscaler failed.").slice(0,1000);
const extension=(mime:string)=>mime==="image/jpeg"?"jpg":mime==="image/webp"?"webp":"png";
const normalizeStatus=(value:any)=>String(value?.taskStatus||value?.status||value?.task_status||value||"").trim().toUpperCase();
const successful=(value:string)=>["SUCCESS","SUCCEEDED","COMPLETED","COMPLETE","FINISHED"].includes(value);
const failed=(value:string)=>["FAILED","FAILURE","ERROR","CANCELLED","CANCELED"].includes(value);

async function providerJson(url:string,init:RequestInit){const response=await fetch(url,init),result:any=await response.json().catch(()=>({}));if(!response.ok||Number(result?.code||0)!==0)throw Object.assign(new Error(String(result?.msg||result?.message||`RunningHub returned HTTP ${response.status}.`)),{code:String(result?.code||response.status)});return result}

async function markFailed(db:any,job:any,update:any,error:any){const stamp=now(),message=safeMessage(error);await db.prepare("UPDATE asset_upscale_jobs SET status='UPSCALE_FAILED',last_error=?,updated_at=?,completed_at=? WHERE job_id=?").bind(message,stamp,stamp,job.id).run();await db.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(job.projectId,"asset_upscale_failed","system:runninghub",JSON.stringify({jobId:job.id,sourceAssetId:job.inputPayload.sourceAssetId,workflowId:RUNNINGHUB_UPSCALE_WORKFLOW_ID,message}),stamp).run();return update(db,job.id,"FAILED","system:runninghub",{provider:"runninghub",error:message})}

export async function dispatchRunningHubUpscale(db:any,env:any,job:any,update:any){
 const record=await db.prepare("SELECT * FROM asset_upscale_jobs WHERE job_id=?").bind(job.id).first<any>();if(!record)return update(db,job.id,"FAILED","system:runninghub",{error:"Upscale metadata record is missing."});if(record.status==="UPSCALE_COMPLETED")return update(db,job.id,"SUCCEEDED","system:runninghub",{provider:"runninghub"});
 try{
  const integration=await loadIntegration(db,env,"runninghub"),apiKey=String(integration?.secret||"").trim();if(!apiKey)return update(db,job.id,"WAITING_PROVIDER","system:runninghub",{provider:"runninghub",error:"Connect RunningHub in Tier 0 System Connections before approving images."});
  if(!record.runninghub_task_id){
   await update(db,job.id,"RUNNING","system:runninghub",{provider:"runninghub"});
   const source=await db.prepare("SELECT id,project_id AS projectId,phase,item_key AS itemKey,storage_key AS storageKey,file_name AS fileName,mime_type AS mimeType,size_bytes AS sizeBytes,is_current AS isCurrent FROM visual_asset_revisions WHERE id=? AND project_id=?").bind(record.source_asset_id,job.projectId).first<any>();if(!source)throw new Error("Approved source image was not found.");if(!String(source.mimeType||"").startsWith("image/"))throw new Error("RunningHub Upscaler accepts approved image assets only.");
   const object=await env.BUCKET.get(source.storageKey);if(!object)throw new Error("Approved source image is missing from private storage.");const bytes=new Uint8Array(await object.arrayBuffer()),form=new FormData();form.append("file",new Blob([bytes],{type:source.mimeType}),source.fileName);
   const upload=await providerJson(`${RUNNINGHUB_BASE_URL}/openapi/v2/media/upload/binary`,{method:"POST",headers:{authorization:`Bearer ${apiKey}`},body:form}),fileName=String(upload?.data?.fileName||upload?.data?.file_name||upload?.fileName||"");if(!fileName)throw new Error("RunningHub upload returned no fileName.");
   const creation=await providerJson(`${RUNNINGHUB_BASE_URL}/task/openapi/create`,{method:"POST",headers:{authorization:`Bearer ${apiKey}`,"content-type":"application/json"},body:JSON.stringify({apiKey,workflowId:RUNNINGHUB_UPSCALE_WORKFLOW_ID,nodeInfoList:runningHubNodeInfo(fileName)})}),taskId=String(creation?.data?.taskId||creation?.data?.task_id||creation?.taskId||"");if(!taskId)throw new Error("RunningHub workflow submission returned no taskId.");
   const stamp=now();await db.prepare("UPDATE asset_upscale_jobs SET runninghub_task_id=?,runninghub_file_name=?,status='UPSCALE_PROCESSING',original_dimensions=?,last_error=NULL,poll_count=0,updated_at=? WHERE job_id=?").bind(taskId,fileName,JSON.stringify(imageDimensions(bytes,source.mimeType)),stamp,job.id).run();await db.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(job.projectId,"asset_upscale_started","system:runninghub",JSON.stringify({jobId:job.id,sourceAssetId:source.id,workflowId:RUNNINGHUB_UPSCALE_WORKFLOW_ID,taskId}),stamp).run();return update(db,job.id,"WAITING_PROVIDER","system:runninghub",{provider:"runninghub",outputPayload:{upscaleStatus:"UPSCALE_PROCESSING",workflowId:RUNNINGHUB_UPSCALE_WORKFLOW_ID,taskId},error:null});
  }
  const statusResult=await providerJson(`${RUNNINGHUB_BASE_URL}/task/openapi/status`,{method:"POST",headers:{authorization:`Bearer ${apiKey}`,"content-type":"application/json"},body:JSON.stringify({apiKey,taskId:record.runninghub_task_id})}),status=normalizeStatus(statusResult?.data??statusResult);
  if(failed(status))throw new Error(String(statusResult?.msg||statusResult?.data?.error||`RunningHub task ended with ${status}.`));
  if(!successful(status)){const count=Number(record.poll_count||0)+1;if(count>60)throw new Error("RunningHub task did not finish within the polling limit.");await db.prepare("UPDATE asset_upscale_jobs SET status='UPSCALE_PROCESSING',poll_count=?,updated_at=? WHERE job_id=?").bind(count,now(),job.id).run();return update(db,job.id,"WAITING_PROVIDER","system:runninghub",{provider:"runninghub",outputPayload:{upscaleStatus:"UPSCALE_PROCESSING",workflowId:RUNNINGHUB_UPSCALE_WORKFLOW_ID,taskId:record.runninghub_task_id,providerStatus:status||"PENDING"},error:null})}
  const outputResult=await providerJson(`${RUNNINGHUB_BASE_URL}/task/openapi/outputs`,{method:"POST",headers:{authorization:`Bearer ${apiKey}`,"content-type":"application/json"},body:JSON.stringify({apiKey,taskId:record.runninghub_task_id})}),outputs=Array.isArray(outputResult?.data)?outputResult.data:[],final=outputs.find((item:any)=>String(item?.nodeId||item?.node_id||"")===RUNNINGHUB_FINAL_NODE_ID),fileUrl=String(final?.fileUrl||final?.file_url||"");if(!fileUrl)throw new Error("RunningHub task succeeded but FF_FINAL_IMAGE (Node 143) was not returned.");
  const download=await fetch(fileUrl);if(!download.ok)throw new Error(`RunningHub final image download returned HTTP ${download.status}.`);const outputBytes=new Uint8Array(await download.arrayBuffer()),reportedType=String(download.headers.get("content-type")||final?.fileType||"image/png").split(";")[0].toLowerCase(),mime=reportedType.startsWith("image/")?reportedType:reportedType.includes("jpeg")||reportedType.includes("jpg")?"image/jpeg":reportedType.includes("webp")?"image/webp":reportedType.includes("png")?"image/png":"";if(!mime)throw new Error("FF_FINAL_IMAGE did not return an image file.");
  const source=await db.prepare("SELECT * FROM visual_asset_revisions WHERE id=?").bind(record.source_asset_id).first<any>();if(!source)throw new Error("Approved source image was removed before upscale completed.");const versionRow=await db.prepare("SELECT COALESCE(MAX(version),0) AS version FROM visual_asset_revisions WHERE project_id=? AND phase=? AND item_key=?").bind(job.projectId,source.phase,source.item_key).first<any>(),version=Number(versionRow?.version||0)+1,ext=extension(mime),storageKey=`projects/${job.projectId}/${source.phase}/${source.item_key}/v${version}-${Date.now()}-runninghub-upscaled.${ext}`,fileName=`${source.item_key}_v${version}_upscaled.${ext}`,stamp=now(),makeCurrent=Number(source.is_current||0)===1;
  await env.BUCKET.put(storageKey,outputBytes,{httpMetadata:{contentType:mime}});if(makeCurrent)await db.prepare("UPDATE visual_asset_revisions SET is_current=0 WHERE project_id=? AND phase=? AND item_key=?").bind(job.projectId,source.phase,source.item_key).run();await db.prepare("INSERT INTO visual_asset_revisions(project_id,phase,item_key,version,storage_key,file_name,mime_type,size_bytes,uploaded_by,is_current,drive_sync_status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,'Pending Drive sync',?)").bind(job.projectId,source.phase,source.item_key,version,storageKey,fileName,mime,outputBytes.byteLength,"system:runninghub",makeCurrent?1:0,stamp).run();const derived=await db.prepare("SELECT id FROM visual_asset_revisions WHERE storage_key=?").bind(storageKey).first<any>(),finalDimensions=imageDimensions(outputBytes,mime);
  await db.prepare("UPDATE asset_upscale_jobs SET derived_asset_id=?,status='UPSCALE_COMPLETED',final_dimensions=?,last_error=NULL,updated_at=?,completed_at=? WHERE job_id=?").bind(derived?.id||null,JSON.stringify(finalDimensions),stamp,stamp,job.id).run();await db.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(job.projectId,"asset_upscale_completed","system:runninghub",JSON.stringify({jobId:job.id,sourceAssetId:source.id,derivedAssetId:derived?.id||null,workflowId:RUNNINGHUB_UPSCALE_WORKFLOW_ID,taskId:record.runninghub_task_id,originalDimensions:record.original_dimensions?JSON.parse(record.original_dimensions):null,finalDimensions,assetPurpose:"UPSCALED_MASTER"}),stamp).run();
  let driveSynced=false;try{const{syncStoredAssetToDrive}=await import("../google-drive/drive");await syncStoredAssetToDrive(job.projectId,source.phase,storageKey,`v${version}_${fileName}`,mime);driveSynced=true;await db.prepare("UPDATE visual_asset_revisions SET drive_sync_status='Synced to Drive' WHERE id=?").bind(derived?.id).run()}catch(error:any){await db.prepare("UPDATE visual_asset_revisions SET drive_sync_status=? WHERE id=?").bind(`Drive retry needed: ${safeMessage(error)}`,derived?.id).run()}
  return update(db,job.id,"SUCCEEDED","system:runninghub",{provider:"runninghub",outputAssets:[{id:derived?.id,storageKey,fileName,mimeType:mime,version,assetPurpose:"UPSCALED_MASTER",sourceAssetId:source.id}],outputPayload:{upscaleStatus:"UPSCALE_COMPLETED",workflowId:RUNNINGHUB_UPSCALE_WORKFLOW_ID,taskId:record.runninghub_task_id,originalDimensions:record.original_dimensions?JSON.parse(record.original_dimensions):null,finalDimensions,driveSynced},error:null});
 }catch(error){return markFailed(db,job,update,error)}
}
