import{activeFormulaFor}from"../../formula-library";
import{buildGenerationContext,ensureAutofillArchitecture}from"../projects/autofill-architecture";
import{loadIntegration}from"../integrations/_lib";
import{lockReelVideoPrompt,normalizeWardrobe,wardrobeValidationIssues}from"../../social-production-formula";
import{normalizeVisualPromptArchitecture,referenceTypesFromSwitches,visualPromptIssues}from"../../visual-prompt-architecture";
import{createSystemJob,recordJobCost,updateSystemJob}from"../orchestrator/service";
import{plannedVisualCount,productionAssetCountIssues}from"../../social-production-plan";
import{parseProviderJsonObject}from"../../provider-json";
import{FRAMEFLOW_I2V_REEL_TYPE,i2vCreativeSimilarityIssues,normalizeI2VPromptItem}from"../../video-prompt-architecture";
import{compactContentProductionRevisionDraft,contentProductionRetakeContentIds,mergeContentProductionRevisionItems}from"../../content-production-revision";

const uiKey=(value:string)=>value.replace(/([a-z0-9])([A-Z])/g,"$1_$2").replace(/[^a-zA-Z0-9]+/g,"_").replace(/^_|_$/g,"").toLowerCase();
const displayValue=(value:any)=>typeof value==="string"?value:JSON.stringify(value,null,2);
const parseJsonOutput=parseProviderJsonObject;
function missingFields(schema:Record<string,unknown>,value:Record<string,unknown>){return Object.keys(schema).filter(key=>{const item=value[key];return item===undefined||item===null||(typeof item==="string"&&!item.trim())||(Array.isArray(item)&&item.length===0)})}
function sourceItems(context:any){const approved=context?.frameflowProjectContext?.approvedStorySource?.content||{},direct=Array.isArray(approved.content_items)?approved.content_items:Array.isArray(approved.items)?approved.items:[];if(direct.length)return direct;const snapshots=context?.frameflowProjectContext?.currentPhaseInputContext||[],batch=snapshots.find((row:any)=>row.phaseKey==="batch-ideas")?.content||{};return Array.isArray(batch.content_items)?batch.content_items:Array.isArray(batch.items)?batch.items:[]}
function sourceFor(item:any,index:number,context:any){const sources=sourceItems(context),id=String(item?.contentId||item?.content_id||"");return sources.find((candidate:any)=>String(candidate.id||candidate.contentId||candidate.content_id)===id)||sources[index]||{}}
export function contextForModel(context:any){const safe=structuredClone(context),root=safe?.frameflowProjectContext||{},manifest=Array.isArray(root.referenceAssetManifest)?root.referenceAssetManifest:[],counts:Record<string,number>={};for(const row of manifest){const category=String(row.category||"");if(category)counts[category]=(counts[category]||0)+1}root.referenceAvailability={authority:"AVAILABLE_NOT_INJECTED",categories:counts,rule:"Approved Project References are only availability metadata here. Reference content and files enter a Content prompt/provider job only after that Content Item explicitly routes the category ON."};root.referenceAssetManifest=[];if(root.approvedReferences)root.approvedReferences={phaseKey:"references",status:"AVAILABLE_NOT_INJECTED",provenance:root.approvedReferences.provenance||null,rule:"The Approved References snapshot is withheld from this generation request until Content-level Reference Routing is ON."};root.currentPhaseInputContext=(Array.isArray(root.currentPhaseInputContext)?root.currentPhaseInputContext:[]).filter((row:any)=>String(row?.phaseKey||"")!=="references");root.currentContinuityRequirements=null;return safe}
function approvedChanges(source:any){const value=source?.approvedWardrobeChanges??source?.approved_wardrobe_changes??[];return(Array.isArray(value)?value:[]).map(Number).filter(Number.isFinite)}
function mergeStructured(base:any,patch:any):any{if(Array.isArray(base)&&Array.isArray(patch)){const key=(row:any)=>String(row?.contentId||row?.content_id||row?.assetNumber||row?.asset_number||"");const merged=base.map((row,index)=>{const match=patch.find(candidate=>key(candidate)&&key(candidate)===key(row))??patch[index];return match===undefined?row:mergeStructured(row,match)});for(const row of patch)if(key(row)&&!base.some(candidate=>key(candidate)===key(row)))merged.push(row);return merged}if(base&&patch&&typeof base==="object"&&typeof patch==="object"&&!Array.isArray(base)&&!Array.isArray(patch))return Object.fromEntries(new Set([...Object.keys(base),...Object.keys(patch)]).values().map(key=>[key,key in patch?mergeStructured(base[key],patch[key]):base[key]]));return patch===undefined?base:patch}
function nestedMissingFields(phaseKey:string,value:Record<string,any>,context:any){const items=Array.isArray(value.items)?value.items:[];if(!["batch-ideas","content-production","reel-video-production"].includes(phaseKey))return[];if(!items.length)return["items"];
 const text=(item:any,...keys:string[])=>keys.map(key=>item?.[key]).find(candidate=>typeof candidate==="string"&&candidate.trim());
 if(phaseKey==="batch-ideas")return items.flatMap((item:any,index:number)=>[["title"],["idea"],["hook"],["story"],["keyMessage","key_message"],["contentType","content_type"]].filter(keys=>!text(item,...keys)).map(keys=>`items[${index}].${keys[0]}`));
 if(phaseKey==="reel-video-production"){const missing=items.flatMap((item:any,index:number)=>{
  const missing=[["contentId","content_id"],["title"],["reelType","reel_type"]].filter(keys=>!text(item,...keys)).map(keys=>`items[${index}].${keys[0]}`),duration=Number(item.durationSeconds??item.duration_seconds),shotCount=Number(item.shotCount??item.shot_count),shots=Array.isArray(item.shots)?item.shots:[];
  if(String(item.reelType||item.reel_type)!==FRAMEFLOW_I2V_REEL_TYPE)missing.push(`items[${index}].reelType (IMAGE_TO_VIDEO only)`);
  if(!Number.isInteger(duration)||duration<8||duration>15)missing.push(`items[${index}].durationSeconds (8–15)`);
  if(!Number.isInteger(shotCount)||shotCount<1||shotCount>3)missing.push(`items[${index}].shotCount (1–3)`);
  if(shots.length!==shotCount)missing.push(`items[${index}].shots (must match shotCount)`);
  const countWords=(value:any)=>String(value||"").trim().split(/\s+/).filter(Boolean).length;
  shots.forEach((shot:any,shotIndex:number)=>{
   const performance=String(shot?.subjectPerformance||shot?.subject_performance||"");
   if(countWords(performance)<12)missing.push(`items[${index}].shots[${shotIndex}].subjectPerformance (specific observable beginning, development and payoff)`);
   if(countWords(shot?.expressionGaze||shot?.expression_gaze)<6)missing.push(`items[${index}].shots[${shotIndex}].expressionGaze (eyeline, motivation and expression progression)`);
   const camera=String(shot?.cameraMovement||shot?.camera_movement||"");
   if(countWords(camera)<8||!/(\d+\s*(?:[–-]|to)?\s*\d*\s*(?:cm|centimet(?:er|re)|m\b|met(?:er|re)|degrees?))/i.test(camera))missing.push(`items[${index}].shots[${shotIndex}].cameraMovement (specific path, numerical amplitude, speed and end position)`);
   if(countWords(shot?.secondaryMotion||shot?.secondary_motion)<5)missing.push(`items[${index}].shots[${shotIndex}].secondaryMotion (visible-scene motion only)`);
  });
  return missing;
 });return[...missing,...i2vCreativeSimilarityIssues(items)]}
 const sourceBatch={content_items:sourceItems(context)},countIssues=productionAssetCountIssues(sourceBatch,{production_items:items});
 return[...countIssues,...items.flatMap((item:any,index:number)=>{const missing:string[]=[];if(!text(item,"caption","finalCaption","final_caption"))missing.push(`items[${index}].caption`);const assets=Array.isArray(item.assets)?item.assets:[],source=sourceFor(item,index,context),anchor=assets[0]?.wardrobe,sourceReferenceTypes=(Array.isArray(source.referenceTypes)?source.referenceTypes:Array.isArray(source.reference_types)?source.reference_types:[]).map(String);let anchorArchitecture:any=null;if(!assets.length)missing.push(`items[${index}].assets`);else assets.forEach((asset:any,assetIndex:number)=>{const row=Object.fromEntries(Object.entries(asset||{}).map(([key,current])=>[uiKey(key),current]))as any,assetNumber=Number(row.asset_number||assetIndex+1),presence=row.subject_presence||source.characterPresence||source.character_presence,structured=row.structured_visual_anchor;if(!structured||typeof structured!=="object")missing.push(`items[${index}].assets[${assetIndex}].structuredVisualAnchor`);wardrobeValidationIssues(row.wardrobe,{assetNumber,subjectPresence:presence,anchorWardrobe:anchor,approvedWardrobeChanges:approvedChanges(source)}).forEach(issue=>missing.push(`items[${index}].assets[${assetIndex}].wardrobe: ${issue}`));if(structured&&typeof structured==="object"){const rawSwitches=row.reference_switches&&typeof row.reference_switches==="object"?row.reference_switches:{},referenceTypes=(Array.isArray(row.reference_types)?row.reference_types:sourceReferenceTypes).map(String),architecture=normalizeVisualPromptArchitecture({structuredAnchor:structured,referenceSwitches:rawSwitches,shotPurpose:row.shot_purpose},{source,contentId:String(item.contentId||item.content_id||source.id||`content_${index+1}`),assetNumber,assetRole:String(row.asset_role||`Visual ${assetNumber}`),subjectPresence:String(presence||"HUMAN_PRESENT"),wardrobe:normalizeWardrobe(row.wardrobe),referenceTypes,approvedAnchor:assetIndex>0&&Boolean(rawSwitches.approvedAnchor??row.continuity_with_first_image??true),anchorArchitecture});if(assetIndex===0)anchorArchitecture=architecture;visualPromptIssues(architecture).forEach(issue=>missing.push(`items[${index}].assets[${assetIndex}].structuredVisualAnchor: ${issue}`))}});return missing})];
}
async function requestLlm(url:string,apiKey:string,payload:Record<string,unknown>){const response=await fetch(url,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${apiKey}`},body:JSON.stringify(payload)});let result:any={};try{result=await response.json()}catch{}const message=String(result?.error?.message||"").toLowerCase(),busy=response.status===429||message.includes("overload")||message.includes("temporarily busy");return{response,result,busy}}
function shapeDraft(phaseKey:string,structured:Record<string,any>,context:any){
 const draft=Object.fromEntries(Object.entries(structured).map(([key,value])=>[uiKey(key),displayValue(value)])) as Record<string,any>;
 if(phaseKey==="batch-ideas"&&Array.isArray(structured.items)){
  const approvedReferences=context?.frameflowProjectContext?.approvedReferences?.content?.categories||{},enabled=Object.entries(approvedReferences).filter(([,value]:any)=>Boolean(value?.enabled)).map(([key])=>key);
  draft.content_items=structured.items.map((item:any)=>Object.fromEntries(Object.entries(item||{}).map(([key,value])=>[uiKey(key),value]))).map((item:any,index:number)=>{const rawType=String(item.content_type||"Image"),contentType=rawType==="Photo"?"Image":rawType==="Threads Article"?"Text Only":rawType;return{...item,id:item.id||`content_${index+1}`,publishingOrder:Number(item.publishing_order||index+1),contentType,visualAssetCount:Math.max(0,Number(item.visual_asset_count??item.asset_count??(contentType==="Text Only"?0:1))),keyMessage:String(item.key_message||""),characterPresence:item.character_presence||"Human Present",approvedWardrobeChanges:(Array.isArray(item.approved_wardrobe_changes)?item.approved_wardrobe_changes:[]).map(Number).filter(Number.isFinite),referenceTypes:(Array.isArray(item.reference_types)?item.reference_types:Array.isArray(item.referenceTypes)?item.referenceTypes:[]).map(String).filter((key:string)=>enabled.includes(key)),platforms:[],publishingSchedule:[],captionDirection:item.caption_direction||"",visualRequirement:item.visual_requirement||"",strategicReason:item.strategic_reason||item.strategic_purpose||"",differenceFromRecentContent:item.difference_from_recent_content||""}});draft.planned_content_quantity=draft.content_items.length;delete draft.items
 }
 if(phaseKey==="content-production"&&Array.isArray(structured.items)){
  const sources=sourceItems(context),manifest=Array.isArray(context?.frameflowProjectContext?.referenceAssetManifest)?context.frameflowProjectContext.referenceAssetManifest:[];
  draft.production_items=structured.items.map((item:any,index:number)=>{
   const normalized=Object.fromEntries(Object.entries(item||{}).map(([key,value])=>[uiKey(key),value]))as any,hashtags=normalized.hashtags??normalized.platform_hashtags??"",source=sources.find((candidate:any)=>String(candidate.id||candidate.contentId||candidate.content_id)===String(normalized.content_id||""))||sources[index]||{},contentId=normalized.content_id||String(source.id||`content_${index+1}`),sourceReferenceTypes=(Array.isArray(source.referenceTypes)?source.referenceTypes:Array.isArray(source.reference_types)?source.reference_types:[]).map(String),assets=Array.isArray(normalized.assets)?normalized.assets:[],anchorWardrobe=normalizeWardrobe(assets[0]?.wardrobe);let anchorArchitecture:any=null;
   const plannedCount=plannedVisualCount(source),orderedAssets=Array.from({length:plannedCount},(_,assetIndex)=>assets.find((asset:any,index:number)=>Number(asset?.assetNumber??asset?.asset_number??index+1)===assetIndex+1)).filter(Boolean),productionAssets=orderedAssets.map((asset:any,assetIndex:number)=>{const row=Object.fromEntries(Object.entries(asset||{}).map(([key,value])=>[uiKey(key),value]))as any,assetNumber=Number(row.asset_number||assetIndex+1),assetRole=row.asset_role||`Visual ${assetIndex+1}`,wardrobe=normalizeWardrobe(row.wardrobe),subjectPresence=String(row.subject_presence||source.characterPresence||source.character_presence||"HUMAN_PRESENT"),rawSwitches=row.reference_switches&&typeof row.reference_switches==="object"?row.reference_switches:{},continuityWithFirstImage=assetIndex>0&&Boolean(rawSwitches.approvedAnchor??row.continuity_with_first_image??true),referenceTypes=(Array.isArray(row.reference_types)?row.reference_types:sourceReferenceTypes).map(String),architecture=normalizeVisualPromptArchitecture({structuredAnchor:row.structured_visual_anchor,referenceSwitches:rawSwitches,shotPurpose:row.shot_purpose},{source,contentId,assetNumber,assetRole,subjectPresence,wardrobe,referenceTypes,approvedAnchor:continuityWithFirstImage,anchorArchitecture,workflowTarget:{provider:"RUNNINGHUB",workflowId:"2102592525269012481",modelTarget:"Qwen Image 2.1"}});if(assetIndex===0)anchorArchitecture=architecture;const routedReferenceTypes=referenceTypesFromSwitches(architecture.referenceSwitches).slice(0,continuityWithFirstImage?1:2),referenceAssets=manifest.filter((reference:any)=>routedReferenceTypes.includes(String(reference.category)));return{assetNumber,assetRole,subjectPresence,wardrobe,shotPurpose:architecture.shotPurpose,visualPrompt:architecture,imageGenerationPrompt:architecture.compiledFinalPrompt,referenceTypes:routedReferenceTypes,referenceAssets,continuityWithFirstImage:architecture.referenceSwitches.approvedAnchor,generationQuality:"low",generationResolution:"1K",maxInputReferences:2}});
   return{contentId,contentType:normalized.content_type||source.contentType||source.content_type||"Photo",title:normalized.title||source.title||`Content ${index+1}`,hook:normalized.hook||source.hook||"",caption:String(normalized.caption||normalized.final_caption||normalized.final_copy||""),hashtags:Array.isArray(hashtags)?hashtags.join(" "):String(hashtags),approvedWardrobeChanges:approvedChanges(source),referenceTypes:sourceReferenceTypes,assets:productionAssets};
  });delete draft.items
 }
 if(phaseKey==="reel-video-production"&&Array.isArray(structured.items)){const snapshots=context?.frameflowProjectContext?.currentPhaseInputContext||[],production=snapshots.find((row:any)=>row.phaseKey==="content-production")?.content||{},batch=snapshots.find((row:any)=>row.phaseKey==="batch-ideas")?.content||{},batchItems=Array.isArray(batch.content_items)?batch.content_items:[],approvedReels=(Array.isArray(production.production_items)?production.production_items:[]).filter((item:any)=>String(item.contentType||item.content_type).toLowerCase()==="reel"),reels=approvedReels.length?approvedReels:structured.items;draft.reel_video_items=reels.map((source:any,index:number)=>{const generated=structured.items.find((item:any)=>String(item.contentId||item.content_id)===String(source.contentId||source.content_id))||structured.items[index]||{},row=Object.fromEntries(Object.entries(generated||{}).map(([key,value])=>[uiKey(key),value])) as any,contentId=String(row.content_id||source.contentId||source.content_id||`content_${index+1}`),batchSource=batchItems.find((candidate:any)=>String(candidate.id||candidate.contentId||candidate.content_id)===contentId)||{},subjectPresence=String(source.assets?.[0]?.subjectPresence||source.assets?.[0]?.subject_presence||batchSource.characterPresence||batchSource.character_presence||"HUMAN_PRESENT"),normalized=normalizeI2VPromptItem(row,{contentId,title:String(row.title||source.title||`Reel ${index+1}`),contentIntent:batchSource,subjectPresence});return{...normalized,compiledVideoPrompt:lockReelVideoPrompt(normalized.compiledVideoPrompt,normalized,batchSource)}});delete draft.items}
 if(phaseKey==="idea-hook-story"&&Array.isArray(structured.reels)){structured.reels.forEach((reel:any,index:number)=>{draft[`reel_${String(index+1).padStart(2,"0")}`]=Object.entries(reel||{}).map(([key,value])=>`${key.replace(/([a-z])([A-Z])/g,"$1 $2").toUpperCase()}: ${Array.isArray(value)?value.join(", "):value||"—"}`).join("\n")});draft.batch_objective=draft.batch_objective||"Coordinated 2-Week Reel batch";delete draft.reels}
 if(phaseKey==="keyshot-set"&&Array.isArray(structured.keyshots)){structured.keyshots.forEach((shot:any,index:number)=>{draft[`keyshot_${String(index+1).padStart(2,"0")}`]=Object.entries(shot||{}).map(([key,value])=>`${key.replace(/([a-z])([A-Z])/g,"$1 $2").toUpperCase()}: ${Array.isArray(value)?value.join(", "):value||"—"}`).join("\n")});delete draft.keyshots}
 if(phaseKey==="strategy-direction"&&draft.current_direction_decision){const decision=String(draft.current_direction_decision).toUpperCase();draft.current_direction_decision=decision.includes("PROPOSE")?"PROPOSE ADJUSTMENT":"KEEP CURRENT DIRECTION"}
 if(phaseKey==="batch-ideas")draft._productionBatchId=Number(context?.frameflowProjectContext?.productionBatch?.id)||null;
 if(phaseKey==="content-production")draft._productionBatchId=Number(context?.frameflowProjectContext?.approvedStorySource?.content?._productionBatchId)||Number(context?.frameflowProjectContext?.productionBatch?.id)||null;
 return draft;
}
async function saveWorkingDraft(db:any,projectId:string,phaseKey:string,structured:Record<string,any>,context:any,revision:any,issues:string[]){const partial=shapeDraft(phaseKey,structured,context),live=await db.prepare("SELECT data FROM phase_records WHERE project_id=? AND phase_key=?").bind(projectId,phaseKey).first<any>();let current:any={};try{current=JSON.parse(live?.data||"{}")}catch{}const base=mergeStructured(current,revision?.currentDraft||{}),draft=mergeStructured(base,partial);if(phaseKey==="reel-video-production"&&Array.isArray(current.reel_video_items)&&current.reel_video_items.length&&(!Array.isArray(draft.reel_video_items)||!draft.reel_video_items.length))draft.reel_video_items=current.reel_video_items;const now=new Date().toISOString(),working={...draft,...(phaseKey==="reel-video-production"?{_reelStage:"style_configured"}:{}),_workingDraftStatus:"Needs Correction",_validationIssues:issues,_workingDraftSavedAt:now};await db.prepare("UPDATE phase_records SET data=?,status=?,updated_at=? WHERE project_id=? AND phase_key=?").bind(JSON.stringify(working),revision?"Retake":"In Progress",now,projectId,phaseKey).run();return working}
export async function generatePhaseDraft(db:any,env:any,projectId:string,phaseKey:string,revision?:{feedback:string;fieldFeedback?:Record<string,string>;currentDraft:Record<string,unknown>;acceptedFields?:string[]},execution?:{agentId:string;agentName:string;parentJobId?:string}){
 await ensureAutofillArchitecture(db);
 const project=await db.prepare("SELECT id,project_type_code AS projectType,is_demo AS isDemo FROM projects WHERE id=?").bind(projectId).first<any>();if(!project)throw Object.assign(new Error("Project not found"),{status:404});
 const phase=await db.prepare("SELECT status FROM phase_records WHERE project_id=? AND phase_key=?").bind(projectId,phaseKey).first<any>();if(!phase||["Locked","Reviewing","Client Reviewing","Approved"].includes(phase.status))throw Object.assign(new Error("This Phase is not editable"),{status:409});
 const formula=activeFormulaFor(phaseKey,project.projectType);if(!formula)throw Object.assign(new Error("No Active Formula is available for this Phase"),{status:404});
 const saved=await loadIntegration(db,env,"llm")||await loadIntegration(db,env,"glm"),apiKey=String(saved?.secret||(env as any).GLM_API_KEY||""),model=String(saved?.config?.model||(env as any).GLM_MODEL||""),providerKey=String(saved?.config?.provider||"gemini"),actor=execution?.agentId||"system:autofill",systemJob=await createSystemJob(db,{projectId,taskId:`${phaseKey}:draft`,jobType:"LLM_TASK",actor,provider:providerKey,model:model||null,inputPayload:{phaseKey,formulaId:formula.id,formulaVersion:formula.version,revision:Boolean(revision)},parentJobId:execution?.parentJobId||null,maxAttempts:1});if(!apiKey||!model){await updateSystemJob(db,systemJob.id,"FAILED",actor,{provider:providerKey,model:model||null,error:"LLM Provider is not configured."});throw Object.assign(new Error("An LLM is not configured. Rule-based Autofill remains available."),{status:503,code:"PROVIDER_NOT_CONFIGURED"})}
 const baseUrl=String(saved?.config?.baseUrl||(env as any).GLM_API_BASE_URL||"https://open.bigmodel.cn/api/paas/v4").replace(/\/$/,""),providerLabel=String(saved?.config?.providerLabel||"LLM"),context=await buildGenerationContext(db,projectId,phaseKey),modelContext=contextForModel(context),startedAt=new Date().toISOString(),revisionContext=context?.frameflowProjectContext?.revisionContext,revisionDraft=revision&&phaseKey==="content-production"?compactContentProductionRevisionDraft(revision.currentDraft):revision?.currentDraft,requiredContentIds=phaseKey==="content-production"?sourceItems(context).map((item:any,index:number)=>String(item?.id||item?.contentId||item?.content_id||`content_${index+1}`)):[],retakeContentIds=revision&&phaseKey==="content-production"?contentProductionRetakeContentIds(revision.fieldFeedback,revision.currentDraft):[],revisionBlock=revision?`\n\nREVISION MODE — AUTHORITY ORDER\n${phaseKey==="content-production"?"CURRENT WORKING VERSION is the only Content Production baseline. Do not copy an older Batch.\n":`LAST APPROVED VERSION — FOR REFERENCE ONLY\n${JSON.stringify(revisionContext?.lastApprovedVersion||null)}\n`}\nREVISION COMMENTS — AUTHORITATIVE REVISION INSTRUCTIONS\n${JSON.stringify(revision.fieldFeedback||revision.feedback)}\n\nCURRENT WORKING VERSION — EDITABLE / NOT APPROVED\n${JSON.stringify(revisionDraft)}${requiredContentIds.length?`\n\nREQUIRED COMPLETE ITEM SET\nReturn exactly one items entry for every ID, in this order: ${requiredContentIds.join(", ")}. Do not return only the first revised item.`:""}\n\nConflict rule: REVISION COMMENTS override the current working version. Change every field named in the Revision Comments. Preserve unaffected fields. A returned Retake field that is identical to the current working value is invalid.`:"",outputTokenLimit=phaseKey==="content-production"?16384:["batch-ideas","reel-video-production"].includes(phaseKey)?8192:4096,makePayload=(block:string,schema:any,maxTokens=outputTokenLimit)=>{const request:any={model,temperature:.55,max_tokens:maxTokens,messages:[{role:"system",content:formula.promptTemplate},{role:"user",content:`APPROVED UPSTREAM PROJECT CONTEXT\n${JSON.stringify(modelContext)}${block}\n\nEXPECTED OUTPUT SCHEMA\n${JSON.stringify(schema)}\n\nReturn one complete valid JSON object only. Use the exact schema field names. Do not wrap it in Markdown. Keep the JSON compact and do not stop before every object and array is closed.`}]};if(saved?.config?.provider!=="gemini"&&model.toLowerCase().startsWith("glm-4.7"))request.thinking={type:"disabled"};return request};
 await updateSystemJob(db,systemJob.id,"RUNNING",actor,{provider:providerKey,model});
 const usageResults:any[]=[];
 const runRequest=async(request:any)=>{const{response,result,busy}=await requestLlm(`${baseUrl}/chat/completions`,apiKey,request);if(busy){await updateSystemJob(db,systemJob.id,"FAILED",actor,{error:"Provider overloaded; automatic retry is disabled."});throw Object.assign(new Error("The LLM provider is temporarily overloaded. Generation stopped after one attempt; no Project data was changed."),{status:503,code:"PROVIDER_BUSY"})}if(!response.ok){const message=result?.error?.message||`LLM request failed (${response.status})`;await updateSystemJob(db,systemJob.id,"FAILED",actor,{error:message});throw Object.assign(new Error(message),{status:502})}usageResults.push(result);const content=String(result?.choices?.[0]?.message?.content||"");try{return parseJsonOutput(content)}catch(firstError:any){const diagnostic=`Provider returned malformed or truncated JSON: ${String(firstError?.message||"parse failure")}. Automatic repair is disabled.`;await updateSystemJob(db,systemJob.id,"FAILED",actor,{error:diagnostic});throw Object.assign(new Error("Agent received an incomplete structured response. Generation stopped after one attempt; no Project data was changed."),{status:502,code:"MALFORMED_PROVIDER_JSON"})}};
 let structured:Record<string,any>;
 if(revision&&phaseKey==="content-production"&&retakeContentIds.length){
  const revisedItems:any[]=[],schema={...formula.outputSchema,items:formula.outputSchema.items};
  for(const targetId of retakeContentIds){
   const comments=Object.fromEntries(Object.entries(revision.fieldFeedback||{}).filter(([key])=>key.startsWith(`production_items.${targetId}.`))),currentItem=(revisionDraft as any)?.items?.find((item:any)=>String(item.contentId)===targetId),block=`\n\nSINGLE CONTENT REVISION MODE\nRevise only ${targetId}. FrameFlow will merge it with the other Content items.\n\nREVISION COMMENTS\n${JSON.stringify(comments)}\n\nCURRENT CONTENT ITEM\n${JSON.stringify(currentItem)}\n\nREQUIRED OUTPUT\nReturn one complete JSON object using the schema, with exactly one items entry whose contentId is ${targetId}. Do not return any other Content item. Every named Retake field must materially change.`;
   const result=await runRequest(makePayload(block,schema,8192)),item=(Array.isArray(result.items)?result.items:[]).find((candidate:any)=>String(candidate?.contentId||candidate?.content_id)===targetId);
   if(!item){const message=`Agent revision for ${targetId} did not return that Content item. Existing Project data was preserved.`;await updateSystemJob(db,systemJob.id,"FAILED",actor,{error:message});throw Object.assign(new Error(message),{status:422,code:"CONTENT_REVISION_ITEM_MISSING"})}revisedItems.push(item)
  }
  structured=mergeContentProductionRevisionItems(revision.currentDraft,revisedItems);
 }else structured=await runRequest(makePayload(revisionBlock,formula.outputSchema));
 if(revision&&phaseKey==="content-production"){
  const baseline=compactContentProductionRevisionDraft(revision.currentDraft);
  if(!String(structured.productionSummary||"").trim()&&baseline.productionSummary)structured.productionSummary=baseline.productionSummary;
  if(!String(structured.technicalNotes||"").trim()&&baseline.technicalNotes)structured.technicalNotes=baseline.technicalNotes;
 }
 let missing=[...missingFields(formula.outputSchema,structured),...nestedMissingFields(phaseKey,structured,context)];
 if(missing.length){await saveWorkingDraft(db,projectId,phaseKey,structured,context,revision,missing);const message=`Working Draft saved with validation issues: ${missing.join(", ")}. Agent can continue correction with Resume Task.`;await updateSystemJob(db,systemJob.id,"FAILED",actor,{error:message,outputPayload:{workingDraftSaved:true,validationIssues:missing}});throw Object.assign(new Error(message),{status:422,code:"WORKING_DRAFT_NEEDS_CORRECTION"})}
 let draft=shapeDraft(phaseKey,structured,context),retakeKeys=Object.keys(revision?.fieldFeedback||{}).filter(key=>!key.includes(".")),unchangedRetakeKeys=retakeKeys.filter(key=>JSON.stringify(draft[key])===JSON.stringify(revision?.currentDraft?.[key]));
 if(unchangedRetakeKeys.length){const message=`Revision not applied: Agent returned unchanged Retake fields (${unchangedRetakeKeys.join(", ")}). The phase remains in Retake and was not resubmitted.`;await updateSystemJob(db,systemJob.id,"FAILED",actor,{error:message});throw Object.assign(new Error(message),{status:502,code:"REVISION_NOT_APPLIED"})}
 const generationMethod=execution?`${execution.agentName} Agent`:`LLM Autofill · ${providerLabel}`,withMeta={...draft,_workingDraftStatus:undefined,_validationIssues:undefined,_workingDraftSavedAt:undefined,_generationMethod:generationMethod,_agentId:execution?.agentId,_agentName:execution?.agentName,_formulaId:formula.id,_formulaVersion:formula.version,_originalGeneratedDraft:draft};
 await db.prepare("INSERT INTO phase_generation_records(project_id,project_type,phase_key,formula_id,formula_version,generation_method,original_generated_draft,created_at,demo_data,learning_status) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(projectId,project.projectType,phaseKey,formula.id,formula.version,generationMethod,JSON.stringify(draft),startedAt,Number(project.isDemo??0),"Pending Review").run();
 const usage=usageResults.map(item=>item?.usage||{}),inputUnits=usage.reduce((sum,item)=>sum+Number(item.prompt_tokens||item.input_tokens||0),0),outputUnits=usage.reduce((sum,item)=>sum+Number(item.completion_tokens||item.output_tokens||0),0);await recordJobCost(db,{jobId:systemJob.id,provider:providerKey,model,inputUnits,outputUnits,pricingStatus:"UNPRICED",metadata:{providerReportedUsage:usage,requestCount:usageResults.length}});await updateSystemJob(db,systemJob.id,"SUCCEEDED",actor,{provider:providerKey,model,outputPayload:{phaseKey,formulaId:formula.id,formulaVersion:formula.version,generationRecordSaved:true,jsonRepairApplied:usageResults.length>1}});return{draft:withMeta,provider:providerLabel,model,formula:{id:formula.id,version:formula.version},jobId:systemJob.id};
}
