import{generatePhaseDraft}from"./engine";
import{requestUserEmail}from"../../chatgpt-auth";

export async function POST(req:Request){
 const{env}=await import("cloudflare:workers"),db=env.DB,email=requestUserEmail(req);if(!email)return Response.json({error:"Authenticated workspace identity required"},{status:401});const member=await db.prepare("SELECT email,tier FROM members WHERE email=?").bind(email).first<any>();if(!member)return Response.json({error:"Workspace membership required"},{status:403});
 const body=await req.json() as any,projectId=String(body.projectId||""),phaseKey=String(body.phaseKey||"");if(!projectId||!phaseKey)return Response.json({error:"Project and Phase are required"},{status:400});
 if(Number(member.tier)>0){const assigned=await db.prepare("SELECT 1 AS ok FROM project_members WHERE project_id=? AND member_email=?").bind(projectId,email).first();if(!assigned)return Response.json({error:"Project access denied"},{status:403})}
 try{const result=await generatePhaseDraft(db,env,projectId,phaseKey),now=new Date().toISOString(),row=await db.prepare("SELECT id,data,status,label FROM phase_records WHERE project_id=? AND phase_key=?").bind(projectId,phaseKey).first<any>();let existing:any={};try{existing=JSON.parse(row?.data||"{}")}catch{}const saved={...existing,...result.draft};await db.prepare("UPDATE phase_records SET data=?,updated_at=? WHERE id=?").bind(JSON.stringify(saved),now,row.id).run();await db.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at,demo_data) VALUES(?,?,?,?,?,COALESCE((SELECT is_demo FROM projects WHERE id=?),0))").bind(projectId,"autofill_draft_saved",String(body.agentId||email),JSON.stringify({phaseKey,phaseLabel:row.label,formula:result.formula,provider:result.provider,model:result.model,autoSaved:true}),now,projectId).run();return Response.json({...result,saved:true})}catch(error:any){return Response.json({error:error.message||"Autofill failed",code:error.code},{status:Number(error.status||500)})}
}
