import{THREADS_SCOPES,appConnection,callbackUrl,cookie,decodeState,origin,runtime}from"../_lib";
import{saveIntegration}from"../../integrations/_lib";
import{socialAccess}from"../../social-connections/_lib";
import{AUTOPOST_ENABLED,autoPostNotFound}from"../../../autopost-mode";

export async function GET(req:Request){
 if(!AUTOPOST_ENABLED)return autoPostNotFound();
 const home=origin(req),redirect=(result:string)=>new Response(null,{status:302,headers:{location:`${home}/?threads=${encodeURIComponent(result)}`,"set-cookie":"ff_threads_oauth=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0"}}),url=new URL(req.url),code=String(url.searchParams.get("code")||""),state=String(url.searchParams.get("state")||""),saved=decodeState(cookie(req,"ff_threads_oauth"));
 if(!code||!state||!saved||saved.state!==state||!saved.projectId)return redirect("invalid-state");
 const env=await runtime();try{await socialAccess(req,env.DB,saved.projectId,true)}catch{return redirect("management-required")}let app:any;try{app=await appConnection(env.DB,env)}catch{return redirect("configuration-required")}
 const tokenResponse=await fetch("https://graph.threads.net/oauth/access_token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:String(app.config.appId),client_secret:String(app.secret),grant_type:"authorization_code",redirect_uri:callbackUrl(req),code})}),short:any=await tokenResponse.json().catch(()=>({}));
 if(!tokenResponse.ok||!short.access_token)return redirect(`token-failed-${short.error?.code||tokenResponse.status}`);
 const exchange=new URL("https://graph.threads.net/access_token");exchange.search=new URLSearchParams({grant_type:"th_exchange_token",client_secret:String(app.secret),access_token:String(short.access_token)}).toString();const longResponse=await fetch(exchange),long:any=await longResponse.json().catch(()=>({}));
 const accessToken=String(long.access_token||short.access_token),expiresIn=Number(long.expires_in||short.expires_in||5184000);if(!accessToken)return redirect("long-token-failed");
 const profileUrl=new URL("https://graph.threads.net/v1.0/me");profileUrl.search=new URLSearchParams({fields:"id,username,threads_profile_picture_url,threads_biography",access_token:accessToken}).toString();const profileResponse=await fetch(profileUrl),profile:any=await profileResponse.json().catch(()=>({}));
 if(!profileResponse.ok||!profile.id||!profile.username)return redirect(`profile-failed-${profile.error?.code||profileResponse.status}`);
 const now=new Date().toISOString(),expiresAt=new Date(Date.now()+Math.max(1,expiresIn)*1000).toISOString(),accountId=String(profile.id),providerKey=`threads-account:${saved.projectId}:${accountId}`,profileLink=`https://www.threads.net/@${profile.username}`,capabilities={autoPublishText:true,autoPublishImage:true,autoPublishVideo:true,autoPublishCarousel:true,readPerformance:true,saveLivePostUrl:true},requestedConnectionId=String(saved.connectionId||""),existing=requestedConnectionId?await env.DB.prepare("SELECT connection_id AS connectionId,external_account_id AS accountId,status,is_default AS isDefault FROM project_social_connections WHERE project_id=? AND platform='Threads' AND connection_id=?").bind(saved.projectId,requestedConnectionId).first<any>():await env.DB.prepare("SELECT connection_id AS connectionId,external_account_id AS accountId,status,is_default AS isDefault FROM project_social_connections WHERE project_id=? AND platform='Threads' AND external_account_id=?").bind(saved.projectId,accountId).first<any>(),defaultRow=await env.DB.prepare("SELECT connection_id FROM project_social_connections WHERE project_id=? AND platform='Threads' AND is_default=1 LIMIT 1").bind(saved.projectId).first<any>(),connectionId=existing?.connectionId||`social_${crypto.randomUUID()}`,isDefault=existing?Number(existing.isDefault||0):defaultRow?0:1;
 await saveIntegration(env.DB,env,providerKey,accessToken,{accountId,username:profile.username,profilePictureUrl:profile.threads_profile_picture_url||"",biography:profile.threads_biography||"",expiresAt,apiVersion:"v1.0",scopes:THREADS_SCOPES},"Connected");
 if(existing)await env.DB.prepare("UPDATE project_social_connections SET provider_key=?,external_account_id=?,profile_url=?,handle=?,account_type='Creator',status='Connected',permissions_json=?,capabilities_json=?,token_expires_at=?,connected_by=?,connected_at=?,last_checked_at=?,disconnected_at=NULL,updated_at=? WHERE connection_id=? AND project_id=?").bind(providerKey,accountId,profileLink,`@${profile.username}`,JSON.stringify(THREADS_SCOPES),JSON.stringify(capabilities),expiresAt,req.headers.get("oai-authenticated-user-email")||"alanloo927@gmail.com",now,now,now,connectionId,saved.projectId).run();else await env.DB.prepare("INSERT INTO project_social_connections(connection_id,project_id,platform,provider_key,external_account_id,profile_url,handle,account_type,status,permissions_json,capabilities_json,token_expires_at,connected_by,connected_at,last_checked_at,disconnected_at,is_default,updated_at) VALUES(?,?,'Threads',?,?,?,?,?,'Connected',?,?,?,?,?,?,NULL,?,?) ON CONFLICT(project_id,platform,external_account_id) DO UPDATE SET provider_key=excluded.provider_key,profile_url=excluded.profile_url,handle=excluded.handle,account_type=excluded.account_type,status='Connected',permissions_json=excluded.permissions_json,capabilities_json=excluded.capabilities_json,token_expires_at=excluded.token_expires_at,connected_by=excluded.connected_by,connected_at=excluded.connected_at,last_checked_at=excluded.last_checked_at,disconnected_at=NULL,updated_at=excluded.updated_at").bind(connectionId,saved.projectId,providerKey,accountId,profileLink,`@${profile.username}`,"Creator",JSON.stringify(THREADS_SCOPES),JSON.stringify(capabilities),expiresAt,req.headers.get("oai-authenticated-user-email")||"alanloo927@gmail.com",now,now,isDefault,now).run();
 await env.DB.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(saved.projectId,existing?"threads_account_reconnected":"threads_account_connected",req.headers.get("oai-authenticated-user-email")||"alanloo927@gmail.com",JSON.stringify({previousAccountId:existing?.accountId||null,accountId,username:profile.username,scopes:THREADS_SCOPES,tokenExpiresAt:expiresAt}),now).run();
 return redirect("connected");
}
