import{dispatchSystemJob,getSystemJob,listSystemJobs}from"../orchestrator/service";
import{apiError,parse,socialAccess}from"../social-connections/_lib";
import{approveBatchLearning,rebuildLearning,syncProfilePerformance,syncRecordPerformance}from"./service";
import{batchDataMaturity,buildBatchTrend,compareBatchTotals,rankBatchContent,selectCurrentBatch,sumBatchMetrics}from"./batch-performance";
import{isAutomaticPublishingPlatform}from"../../social-scheduling-platforms";
import{dateInTimeZone}from"../../social-batch-lifecycle";
import{AUTOPOST_ENABLED,autoPostNotFound}from"../../autopost-mode";

async function runtime(){const{env}=await import("cloudflare:workers");return env as any}
const queueStatus=(jobStatus:string,recordStatus:string,scheduledAt:string|null)=>recordStatus==="PUBLISHED"?"PUBLISHED":recordStatus==="MANUAL_REQUIRED"||jobStatus==="BLOCKED_CAPABILITY"?"MANUAL_REQUIRED":!scheduledAt?"READY":recordStatus==="MANUAL_EXCEPTION"?"MANUAL_EXCEPTION":recordStatus==="PUBLISHING"?"PUBLISHING":recordStatus==="NEEDS_ATTENTION"?"NEEDS_ATTENTION":jobStatus==="SCHEDULED"?"SCHEDULED":jobStatus==="RUNNING"||jobStatus==="WAITING_CALLBACK"?"PUBLISHING":["FAILED","WAITING_PROVIDER","RETRY_PENDING"].includes(jobStatus)?"NEEDS_ATTENTION":"READY";

async function scheduleBatchError(db:any,projectId:string,jobId:string,scheduledAt:string){const row=await db.prepare("SELECT b.batch_number AS batchNumber,b.starts_at AS startsAt,b.ends_at AS endsAt,p.project_config AS projectConfig FROM publishing_records r JOIN production_batches b ON b.id=r.batch_id JOIN projects p ON p.id=r.project_id WHERE r.project_id=? AND r.job_id=? LIMIT 1").bind(projectId,jobId).first<any>();if(!row?.startsAt||!row?.endsAt)return null;const config=parse(row.projectConfig,{}),timeZone=String(config.timezone||"Asia/Kuala_Lumpur"),localDate=dateInTimeZone(new Date(scheduledAt),timeZone);const today=dateInTimeZone(new Date(),timeZone);if(today>row.endsAt&&localDate>=today&&Date.parse(scheduledAt)>Date.now())return null;return localDate<row.startsAt||localDate>row.endsAt?`Choose a time inside Batch ${String(row.batchNumber).padStart(2,"0")} (${row.startsAt} to ${row.endsAt}, ${timeZone}).`:null}

async function repairTemporaryStorageFailures(db:any,projectId:string){if(projectId!=="PRJ-0001")return;const marker=await db.prepare("SELECT id FROM audit_log WHERE project_id=? AND event_type='temporary_publishing_storage_public_repair' LIMIT 1").bind(projectId).first();if(marker)return;const rows=await db.prepare("SELECT r.id,r.content_key AS contentKey,r.job_id AS jobId,r.scheduled_at AS scheduledAt,j.input_payload AS inputPayload FROM publishing_records r JOIN orchestrator_jobs j ON j.id=r.job_id WHERE r.project_id=? AND r.content_key IN ('content_1','content_2') AND r.status!='PUBLISHED'").bind(projectId).all(),now=new Date(),tomorrow=new Date(now);tomorrow.setUTCDate(tomorrow.getUTCDate()+1);tomorrow.setUTCHours(12,0,0,0);const repaired=[] as any[];for(const row of rows.results as any[]){let scheduledAt=String(row.scheduledAt||"");if(row.contentKey==="content_1"&&(!scheduledAt||Date.parse(scheduledAt)<=Date.now()))scheduledAt=tomorrow.toISOString();if(!scheduledAt||!Number.isFinite(Date.parse(scheduledAt)))continue;const payload=parse(row.inputPayload,{});payload.scheduledFor=scheduledAt;await db.batch([db.prepare("UPDATE orchestrator_jobs SET input_payload=?,scheduled_for=?,status='SCHEDULED',attempt_count=0,started_at=NULL,completed_at=NULL,last_error=NULL,updated_at=? WHERE id=?").bind(JSON.stringify(payload),scheduledAt,now.toISOString(),row.jobId),db.prepare("UPDATE publishing_records SET scheduled_at=?,status='SCHEDULED',published_at=NULL,provider_post_id=NULL,provider_media_id=NULL,post_url=NULL,error_code=NULL,error_message=NULL,retry_count=0,requires_human_action=0,updated_at=? WHERE id=?").bind(scheduledAt,now.toISOString(),row.id)]);repaired.push({contentKey:row.contentKey,recordId:row.id,scheduledAt})}await db.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(projectId,"temporary_publishing_storage_public_repair","system:migration",JSON.stringify({reason:"Replace private media URLs with public temporary storage; restore failed live-test records without immediate dispatch.",repaired}),now.toISOString()).run()}

async function repairInstagramContainerPollingFailure(db:any,projectId:string){const marker=await db.prepare("SELECT id FROM audit_log WHERE project_id=? AND event_type='instagram_container_polling_repair' LIMIT 1").bind(projectId).first();if(marker)return;const rows=await db.prepare("SELECT r.id,r.job_id AS jobId,r.content_key AS contentKey,r.scheduled_at AS scheduledAt,j.input_payload AS inputPayload FROM publishing_records r JOIN orchestrator_jobs j ON j.id=r.job_id WHERE r.project_id=? AND r.platform='Instagram' AND r.status!='PUBLISHED' AND (r.error_code='9007' OR r.error_message LIKE '%Media ID is not available%')").bind(projectId).all();if(!(rows.results as any[]).length)return;const now=new Date(),tomorrow=new Date(now);tomorrow.setUTCDate(tomorrow.getUTCDate()+1);tomorrow.setUTCHours(12,0,0,0);const repaired=[] as any[];for(const row of rows.results as any[]){let scheduledAt=String(row.scheduledAt||"");if(!scheduledAt||Date.parse(scheduledAt)<=Date.now())scheduledAt=tomorrow.toISOString();const payload=parse(row.inputPayload,{});payload.scheduledFor=scheduledAt;await db.batch([db.prepare("UPDATE orchestrator_jobs SET input_payload=?,scheduled_for=?,status='SCHEDULED',attempt_count=0,max_attempts=5,started_at=NULL,completed_at=NULL,last_error=NULL,updated_at=? WHERE id=?").bind(JSON.stringify(payload),scheduledAt,now.toISOString(),row.jobId),db.prepare("UPDATE publishing_records SET scheduled_at=?,status='SCHEDULED',published_at=NULL,provider_container_id=NULL,provider_post_id=NULL,provider_media_id=NULL,post_url=NULL,result='{}',error_code=NULL,error_message=NULL,requires_human_action=0,updated_at=? WHERE id=?").bind(scheduledAt,now.toISOString(),row.id)]);repaired.push({contentKey:row.contentKey,recordId:row.id,scheduledAt})}await db.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(projectId,"instagram_container_polling_repair","system:migration",JSON.stringify({reason:"Restore Meta 9007 failures after adding durable Container ID polling. No publish was triggered.",repaired}),now.toISOString()).run()}

const learningView=(row:any)=>row?{id:row.id,batchKey:row.batchKey,keep:parse(row.keepJson,[]),improve:parse(row.improveJson,[]),testNext:parse(row.testNextJson,[]),evidence:parse(row.evidenceJson,{}),sourceWindowStart:row.sourceWindowStart,sourceWindowEnd:row.sourceWindowEnd,approvedBy:row.approvedBy||null,approvedAt:row.approvedAt||null,updatedAt:row.updatedAt}:null;

async function currentBatchPerformance(db:any,projectId:string,requestedBatchId:number|null=null){
 const [batchRows,summaryRows]=await Promise.all([db.prepare("SELECT id,batch_number AS batchNumber,starts_at AS startsAt,ends_at AS endsAt,status,gate_status AS gateStatus,planned_count AS plannedCount FROM production_batches WHERE project_id=? ORDER BY batch_number").bind(projectId).all(),db.prepare("SELECT batch_id AS batchId,COUNT(*) AS recordCount,SUM(CASE WHEN status='PUBLISHED' THEN 1 ELSE 0 END) AS publishedCount,SUM(CASE WHEN status NOT IN ('PUBLISHED','MANUAL_EXCEPTION','CANCELLED') THEN 1 ELSE 0 END) AS unfinishedCount FROM publishing_records WHERE project_id=? GROUP BY batch_id").bind(projectId).all()]),batches=batchRows.results as any[],visibleBatches=batches.filter(batch=>!["Locked","Planning"].includes(String(batch.status))),defaultBatch=selectCurrentBatch(visibleBatches),current=visibleBatches.find(batch=>Number(batch.id)===Number(requestedBatchId))||defaultBatch,summaries=new Map((summaryRows.results as any[]).map(row=>[Number(row.batchId),row])),availableBatches=visibleBatches.map(batch=>{const summary:any=summaries.get(Number(batch.id))||{};return{...batch,isCurrent:Number(batch.id)===Number(defaultBatch?.id),isSelected:Number(batch.id)===Number(current?.id),recordCount:Number(summary.recordCount||0),publishedCount:Number(summary.publishedCount||0),unfinishedCount:Number(summary.unfinishedCount||0)}});
 if(requestedBatchId&&!visibleBatches.some(batch=>Number(batch.id)===requestedBatchId))throw Object.assign(new Error("This Batch is not available for this Project."),{status:404});
 if(!current)return{scope:"PROJECT_BATCH",projectId,currentBatch:null,availableBatches,previousBatch:null,totals:sumBatchMetrics([]),topContent:[],trend:[],comparison:null,dataMaturity:batchDataMaturity([]),agentLearning:null,nextBatchLearningInput:null};
 const previous=visibleBatches.filter(batch=>Number(batch.batchNumber)<Number(current.batchNumber)).at(-1)||null,next=visibleBatches.find(batch=>Number(batch.batchNumber)>Number(current.batchNumber))||null,batchKey=`batch:${current.id}`;
 const [recordRows,previousRows,snapshotRows,approvedRow,candidateRow]=await Promise.all([
  db.prepare("SELECT id,project_id AS projectId,batch_id AS batchId,content_key AS contentKey,publishing_order AS publishingOrder,platform,connected_handle AS connectedHandle,published_at AS publishedAt,status,performance_sync_status AS performanceSyncStatus,normalized_metrics AS normalizedMetrics FROM publishing_records WHERE project_id=? AND batch_id=? ORDER BY publishing_order,content_key,platform,id").bind(projectId,current.id).all(),
  previous?db.prepare("SELECT id,status,published_at AS publishedAt,performance_sync_status AS performanceSyncStatus,normalized_metrics AS normalizedMetrics FROM publishing_records WHERE project_id=? AND batch_id=? ORDER BY id").bind(projectId,previous.id).all():Promise.resolve({results:[]}),
  db.prepare("SELECT publishing_record_id AS publishingRecordId,platform,captured_at AS capturedAt,normalized_metrics AS metrics FROM social_performance_snapshots WHERE project_id=? AND batch_id=? AND scope='CONTENT' ORDER BY captured_at,id").bind(projectId,current.id).all(),
  db.prepare("SELECT id,batch_key AS batchKey,keep_json AS keepJson,improve_json AS improveJson,test_next_json AS testNextJson,evidence_json AS evidenceJson,source_window_start AS sourceWindowStart,source_window_end AS sourceWindowEnd,approved_by AS approvedBy,approved_at AS approvedAt,updated_at AS updatedAt FROM batch_learning_records WHERE project_id=? AND batch_key=? AND status='READY' AND approved_at IS NOT NULL AND approved_by IS NOT NULL AND trim(approved_by)!='' ORDER BY approved_at DESC,id DESC LIMIT 1").bind(projectId,batchKey).first<any>(),
  db.prepare("SELECT id,batch_key AS batchKey,keep_json AS keepJson,improve_json AS improveJson,test_next_json AS testNextJson,evidence_json AS evidenceJson,source_window_start AS sourceWindowStart,source_window_end AS sourceWindowEnd,updated_at AS updatedAt FROM batch_learning_records WHERE project_id=? AND batch_key=? AND status='PENDING_REVIEW' ORDER BY updated_at DESC,id DESC LIMIT 1").bind(projectId,batchKey).first<any>(),
 ]),records=(recordRows.results as any[]).map(row=>({...row,metrics:parse(row.normalizedMetrics,{})})),published=records.filter(row=>row.status==="PUBLISHED"),synced=published.filter(row=>row.performanceSyncStatus==="SYNCED"),previousRecords=(previousRows.results as any[]).filter((row:any)=>row.status==="PUBLISHED").map((row:any)=>({...row,metrics:parse(row.normalizedMetrics,{})})),totals=sumBatchMetrics(published),previousTotals=previous?sumBatchMetrics(previousRecords):null,approved=learningView(approvedRow),candidate=learningView(candidateRow);
 return{scope:"PROJECT_BATCH",projectId,availableBatches,currentBatch:{...current,batchKey,recordCount:records.length,publishedCount:published.length,syncedCount:synced.length},previousBatch:previous?{...previous,totals:previousTotals}:null,nextBatch:next||null,totals,platforms:[...new Set(records.map(row=>row.platform))],topContent:rankBatchContent(published),trend:buildBatchTrend(snapshotRows.results as any[]),comparison:compareBatchTotals(totals,previousTotals),dataMaturity:batchDataMaturity(records),agentLearning:candidate||approved,nextBatchLearningInput:approved,learningCandidate:candidate};
}

async function cumulativeProjectPerformance(db:any,projectId:string){
 const batchRows=await db.prepare("SELECT id,batch_number AS batchNumber,starts_at AS startsAt,ends_at AS endsAt,status FROM production_batches WHERE project_id=? AND status NOT IN ('Locked','Planning') ORDER BY batch_number").bind(projectId).all(),batches=batchRows.results as any[],recordRows=await db.prepare("SELECT r.id,r.batch_id AS batchId,r.content_key AS contentKey,r.platform,r.published_at AS publishedAt,r.status,r.performance_sync_status AS performanceSyncStatus,r.normalized_metrics AS normalizedMetrics FROM publishing_records r JOIN production_batches b ON b.id=r.batch_id AND b.project_id=r.project_id WHERE r.project_id=? AND r.status='PUBLISHED' AND b.status NOT IN ('Locked','Planning') ORDER BY r.published_at,r.id").bind(projectId).all(),records=(recordRows.results as any[]).map(row=>({...row,metrics:parse(row.normalizedMetrics,{})})),learningRows=await db.prepare("SELECT l.id,l.batch_key AS batchKey,l.keep_json AS keepJson,l.improve_json AS improveJson,l.test_next_json AS testNextJson,l.approved_by AS approvedBy,l.approved_at AS approvedAt FROM batch_learning_records l JOIN production_batches b ON l.batch_key='batch:'||b.id AND b.project_id=l.project_id WHERE l.project_id=? AND l.status='READY' AND b.status NOT IN ('Locked','Planning') AND l.approved_at IS NOT NULL AND l.approved_by IS NOT NULL AND trim(l.approved_by)!='' ORDER BY l.approved_at,l.id").bind(projectId).all(),learning=(learningRows.results as any[]).map(learningView),unique=(key:"keep"|"improve"|"testNext")=>Array.from(new Set(learning.flatMap(row=>row?.[key]||[]))).slice(0,20);
 return{available:true,batchCount:batches.length,scope:"PROJECT_ALL_BATCHES",batches,totals:sumBatchMetrics(records),topContent:rankBatchContent(records).slice(0,10),dataMaturity:batchDataMaturity(records),publishedCount:records.length,syncedCount:records.filter(row=>row.performanceSyncStatus==="SYNCED").length,learning:{keep:unique("keep"),improve:unique("improve"),testNext:unique("testNext"),source:"APPROVED_READY_BATCH_LEARNING_ONLY"}};
}

async function publishingData(db:any,projectId:string,rangeDays:number|null=null,selectedBatchId:number|null=null){
 // Reads preserve durable publishing and retry state. Reconciliation belongs to approval and scheduler actions.
 const jobs=await listSystemJobs(db,{projectId,jobType:"PUBLISH_JOB",limit:200});
 const batchPerformance=await currentBatchPerformance(db,projectId,selectedBatchId),effectiveBatchId=Number(batchPerformance.currentBatch?.id)||null;
 const records=effectiveBatchId?await db.prepare("SELECT id,job_id AS jobId,project_id AS projectId,batch_id AS batchId,content_key AS contentKey,publishing_order AS publishingOrder,platform,social_connection_id AS socialConnectionId,connected_account_id AS connectedAccountId,connected_handle AS connectedHandle,caption,assets,scheduled_at AS scheduledAt,published_at AS publishedAt,provider_container_id AS providerContainerId,provider_post_id AS providerPostId,provider_media_id AS providerMediaId,post_url AS postUrl,status,result,error_code AS errorCode,error_message AS errorMessage,retry_count AS retryCount,performance_sync_status AS performanceSyncStatus,normalized_metrics AS normalizedMetrics,requires_human_action AS requiresHumanAction,created_at AS createdAt,updated_at AS updatedAt FROM publishing_records WHERE project_id=? AND batch_id=? AND status!='CANCELLED' ORDER BY publishing_order,content_key,platform,id").bind(projectId,effectiveBatchId).all():{results:[]},byJob=new Map(jobs.map(job=>[job.id,job]));
 const queue=(records.results as any[]).map(record=>{const job:any=record.jobId?byJob.get(record.jobId):null,scheduledAt=record.scheduledAt||job?.scheduledFor||null;return{...record,scheduledAt,assets:parse(record.assets,[]),result:parse(record.result,{}),metrics:parse(record.normalizedMetrics,{}),status:queueStatus(job?.status||"",record.status,scheduledAt),jobStatus:job?.status||null,attemptCount:job?job.attemptCount:record.retryCount,lastError:scheduledAt?(record.errorMessage||job?.lastError||null):null}}),rangeCutoff=rangeDays?new Date(Date.now()-rangeDays*86_400_000).toISOString():null,performanceQueue=queue.filter(item=>item.status==="PUBLISHED"&&(!rangeCutoff||(item.publishedAt&&item.publishedAt>=rangeCutoff)));
 const snapshots=effectiveBatchId?await db.prepare("SELECT platform,normalized_metrics AS metrics,captured_at AS capturedAt FROM social_performance_snapshots WHERE project_id=? AND batch_id=? AND scope='CONTENT' ORDER BY captured_at DESC LIMIT 500").bind(projectId,effectiveBatchId).all():{results:[]},profileRows=await db.prepare("SELECT platform,social_connection_id AS socialConnectionId,normalized_metrics AS metrics,captured_at AS capturedAt FROM social_performance_snapshots WHERE project_id=? AND scope='PROFILE' ORDER BY captured_at DESC LIMIT 50").bind(projectId).all(),totals:any={views:0,reach:0,likes:0,comments:0,shares:0,saves:0,engagement:0};for(const row of performanceQueue){for(const key of Object.keys(totals))totals[key]+=Number(row.metrics?.[key]||0)}const profile:any={};for(const row of profileRows.results as any[]){const key=row.socialConnectionId||row.platform;if(!profile[key])profile[key]={platform:row.platform,socialConnectionId:row.socialConnectionId,...parse(row.metrics,{}),capturedAt:row.capturedAt}};
 const top=performanceQueue.sort((a,b)=>Number(b.metrics.engagement||0)-Number(a.metrics.engagement||0)).slice(0,3);
 return{queue,selectedBatchId:effectiveBatchId,mediaDelivery:{configured:true,mode:"Temporary Publishing Storage",sourceAssets:"Private",temporaryLifetimeHours:6,postPublishRetentionHours:2},scheduler:{automatic:true,requiresScheduledAt:true,cadence:"Every minute",performanceSyncCadence:"Every 30 minutes"},performance:{scope:"PROJECT_BATCH",range:rangeDays?`LAST_${rangeDays}_DAYS`:"ALL_TIME",totals,profile,topContent:top,trend:(snapshots.results as any[]).filter(row=>!rangeCutoff||row.capturedAt>=rangeCutoff).slice(0,14).reverse().map(row=>({platform:row.platform,capturedAt:row.capturedAt,...parse(row.metrics,{})}))},batchPerformance,masterPerformance:await cumulativeProjectPerformance(db,projectId),learning:batchPerformance.nextBatchLearningInput,learningCandidate:batchPerformance.learningCandidate};
}

export async function GET(req:Request){if(!AUTOPOST_ENABLED)return autoPostNotFound();try{const env=await runtime(),url=new URL(req.url),projectId=String(url.searchParams.get("projectId")||""),range=String(url.searchParams.get("range")||"all"),rangeDays=range==="14d"?14:range==="30d"?30:null,batchId=Number(url.searchParams.get("batchId")||0)||null,actor=await socialAccess(req,env.DB,projectId);return Response.json({canManage:actor.tier<=1,canPublishNow:actor.tier<=1,...await publishingData(env.DB,projectId,rangeDays,batchId)})}catch(error){return apiError(error)}}

export async function POST(req:Request){try{
 if(!AUTOPOST_ENABLED)return autoPostNotFound();
	 const env=await runtime(),body=await req.json()as any,projectId=String(body.projectId||""),action=String(body.action||""),requestedBatchId=Number(body.batchId||0)||null,actor=await socialAccess(req,env.DB,projectId,true),now=new Date().toISOString();
	 if(action==="publish_now"){
  if(actor.tier>1)return Response.json({error:"Only Tier 0–1 Management can confirm Publish now."},{status:403});
  const job=await getSystemJob(env.DB,String(body.jobId||""));
  if(!job||job.projectId!==projectId||job.jobType!=="PUBLISH_JOB")return Response.json({error:"Publishing Job not found."},{status:404});
  const record=await env.DB.prepare("SELECT id,status,error_code AS errorCode,scheduled_at AS scheduledAt,platform,content_key AS contentKey,connected_handle AS connectedHandle FROM publishing_records WHERE job_id=? AND project_id=?").bind(job.id,projectId).first<any>();
  if(!record)return Response.json({error:"Publishing Record not found."},{status:404});
  if(record.status==="PUBLISHED"||job.status==="SUCCEEDED")return Response.json({error:"This Publishing Record is already Published. A live test cannot publish it twice."},{status:409});
  if(!job.scheduledFor||!Number.isFinite(Date.parse(job.scheduledFor)))return Response.json({error:"This Content has no scheduledAt. Publish-now cannot bypass the required approved schedule."},{status:409});
  if(!isAutomaticPublishingPlatform(record.platform))return Response.json({error:`${record.platform} is not connected to automatic publishing yet.`},{status:409});
  const missed=record.status==="NEEDS_ATTENTION"&&record.errorCode==="MISSED_SCHEDULE"&&job.status==="WAITING_PROVIDER";
  if(!missed&&(record.status!=="SCHEDULED"||job.status!=="SCHEDULED"))return Response.json({error:`Publish now is available for a Scheduled or Missed-schedule Record. Current status: ${record.status||job.status}.`},{status:409});
  await env.DB.batch([
   env.DB.prepare("UPDATE orchestrator_jobs SET status='QUEUED',last_error=NULL,updated_at=? WHERE id=?").bind(now,job.id),
   env.DB.prepare("UPDATE publishing_records SET status='READY',error_code=NULL,error_message=NULL,requires_human_action=0,updated_at=? WHERE id=?").bind(now,record.id),
   env.DB.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(projectId,"publishing_publish_now_requested",actor.email,JSON.stringify({jobId:job.id,recordId:record.id,contentKey:record.contentKey,platform:record.platform,connectedHandle:record.connectedHandle,scheduledAt:job.scheduledFor,previouslyMissed:missed,mode:"CONFIRMED_PUBLISH_NOW"}),now)
  ]);
  const completed=await dispatchSystemJob(env.DB,env,job.id,new URL(req.url).origin),data=await publishingData(env.DB,projectId,null,requestedBatchId);
  if(completed.status!=="SUCCEEDED")return Response.json({error:completed.lastError||"The live publishing test did not complete.",...data},{status:502});
  await env.DB.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(projectId,"publishing_publish_now_completed",actor.email,JSON.stringify({jobId:job.id,recordId:record.id,contentKey:record.contentKey,platform:record.platform,mode:"CONFIRMED_PUBLISH_NOW"}),new Date().toISOString()).run();
  return Response.json({ok:true,publishedNow:true,...await publishingData(env.DB,projectId,null,requestedBatchId)});
 }
 if(action==="approve_batch_learning"){
  if(actor.tier>1)return Response.json({error:"Only Tier 0–1 Management can approve Learned Memory."},{status:403});
  const approved=await approveBatchLearning(env.DB,projectId,Number(body.learningId||0),actor.email);
  await env.DB.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(projectId,"batch_learning_approved",actor.email,JSON.stringify(approved),now).run();
  return Response.json({ok:true,learningApproved:true,...await publishingData(env.DB,projectId,null,requestedBatchId)});
 }
 if(action==="override_schedule"){
 const job=await getSystemJob(env.DB,String(body.jobId||""));if(!job||job.projectId!==projectId)return Response.json({error:"Publishing Job not found."},{status:404});const scheduledAt=String(body.scheduledAt||"");if(!scheduledAt||!Number.isFinite(Date.parse(scheduledAt)))return Response.json({error:"Choose a valid publishing date and time."},{status:400});const batchError=await scheduleBatchError(env.DB,projectId,job.id,scheduledAt);if(batchError)return Response.json({error:batchError},{status:400});const automatic=isAutomaticPublishingPlatform(job.inputPayload.platform),future=Date.parse(scheduledAt)>Date.now(),status=automatic?(future?"SCHEDULED":"WAITING_PROVIDER"):"BLOCKED_CAPABILITY",recordStatus=automatic?(future?"SCHEDULED":"NEEDS_ATTENTION"):"MANUAL_REQUIRED",errorCode=automatic?(future?null:"MISSED_SCHEDULE"):"LIVE_PUBLISHING_NOT_IMPLEMENTED",errorMessage=automatic?(future?null:"Scheduled time has already passed. Choose a future time or confirm Publish now."):`Live ${job.inputPayload.platform} automatic publishing is not implemented. Publish manually and save the live link.`;await env.DB.batch([env.DB.prepare("UPDATE orchestrator_jobs SET scheduled_for=?,status=?,last_error=?,updated_at=? WHERE id=?").bind(scheduledAt,status,errorMessage,now,job.id),env.DB.prepare("UPDATE publishing_records SET scheduled_at=?,status=?,error_code=?,error_message=?,requires_human_action=?,updated_at=? WHERE job_id=?").bind(scheduledAt,recordStatus,errorCode,errorMessage,errorCode?1:0,now,job.id),env.DB.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(projectId,"publishing_schedule_overridden",actor.email,JSON.stringify({jobId:job.id,scheduledAt,future}),now)]);return Response.json({ok:true,...await publishingData(env.DB,projectId,null,requestedBatchId)});
 }
 if(action==="assign_profile"){
 const job=await getSystemJob(env.DB,String(body.jobId||""));if(!job||job.projectId!==projectId)return Response.json({error:"Publishing Job not found."},{status:404});const connection=await env.DB.prepare("SELECT connection_id AS connectionId,external_account_id AS accountId,handle FROM project_social_connections WHERE project_id=? AND platform=? AND connection_id=? AND status='Connected'").bind(projectId,String(job.inputPayload.platform||""),String(body.socialConnectionId||"")).first<any>();if(!connection)return Response.json({error:"Choose a connected Project Profile for this platform."},{status:400});const inputPayload={...job.inputPayload,socialConnectionId:connection.connectionId,profileHandle:connection.handle},automatic=isAutomaticPublishingPlatform(job.inputPayload.platform),future=Boolean(job.scheduledFor&&Date.parse(job.scheduledFor)>Date.now()),jobStatus=automatic?(future?"SCHEDULED":"WAITING_PROVIDER"):"BLOCKED_CAPABILITY",recordStatus=automatic?(future?"SCHEDULED":"NEEDS_ATTENTION"):"MANUAL_REQUIRED",errorCode=automatic?(future?null:"MISSED_SCHEDULE"):"LIVE_PUBLISHING_NOT_IMPLEMENTED",errorMessage=automatic?(future?null:"Scheduled time has already passed. Choose a future time or confirm Publish now."):`Live ${job.inputPayload.platform} automatic publishing is not implemented. Publish manually and save the live link.`;await env.DB.batch([env.DB.prepare("UPDATE orchestrator_jobs SET input_payload=?,status=?,last_error=?,updated_at=? WHERE id=?").bind(JSON.stringify(inputPayload),jobStatus,errorMessage,now,job.id),env.DB.prepare("UPDATE publishing_records SET social_connection_id=?,connected_account_id=?,connected_handle=?,status=?,error_code=?,error_message=?,requires_human_action=?,updated_at=? WHERE job_id=?").bind(connection.connectionId,connection.accountId,connection.handle,recordStatus,errorCode,errorMessage,errorCode?1:0,now,job.id),env.DB.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(projectId,"publishing_profile_overridden",actor.email,JSON.stringify({jobId:job.id,platform:job.inputPayload.platform,socialConnectionId:connection.connectionId,handle:connection.handle}),now)]);return Response.json({ok:true,...await publishingData(env.DB,projectId,null,requestedBatchId)});
 }
 if(action==="retry"){
  const job=await getSystemJob(env.DB,String(body.jobId||""));if(!job||job.projectId!==projectId)return Response.json({error:"Publishing Job not found."},{status:404});if(!isAutomaticPublishingPlatform(job.inputPayload.platform))return Response.json({error:`${job.inputPayload.platform} automatic publishing is not connected yet. Publish it yourself, then save the live post URL.`},{status:409});if(!job.scheduledFor||!Number.isFinite(Date.parse(job.scheduledFor)))return Response.json({error:"This Content has no scheduledAt. Publishing is blocked until Agent or Management assigns one."},{status:409});await env.DB.prepare("UPDATE orchestrator_jobs SET status='RETRY_PENDING',last_error=NULL,updated_at=? WHERE id=?").bind(now,job.id).run();await env.DB.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(projectId,"publishing_retry_requested",actor.email,JSON.stringify({jobId:job.id}),now).run();await dispatchSystemJob(env.DB,env,job.id,new URL(req.url).origin);return Response.json({ok:true,...await publishingData(env.DB,projectId,null,requestedBatchId)});
 }
 if(action==="mark_manual_published"){
  const recordId=Number(body.recordId||0),record=await env.DB.prepare("SELECT id,job_id AS jobId,platform,status FROM publishing_records WHERE id=? AND project_id=?").bind(recordId,projectId).first<any>();
  if(!record)return Response.json({error:"Publishing Record not found."},{status:404});
  if(!["TikTok","Facebook Page"].includes(record.platform))return Response.json({error:"This platform uses automatic publishing."},{status:409});
  if(["PUBLISHED","PUBLISHING","CANCELLED"].includes(record.status))return Response.json({error:"This record cannot be marked published in its current state."},{status:409});
  let postUrl:URL;try{postUrl=new URL(String(body.postUrl||""))}catch{return Response.json({error:"Enter a valid live post URL."},{status:400})}
  const domain=record.platform==="TikTok"?"tiktok.com":"facebook.com";
  if(postUrl.protocol!=="https:"||postUrl.username||postUrl.password||!(postUrl.hostname===domain||postUrl.hostname.endsWith(`.${domain}`))||postUrl.pathname==="/")return Response.json({error:`Enter an HTTPS ${record.platform} post link.`},{status:400});
  const evidence=JSON.stringify({source:"MANAGEMENT_CONFIRMED_MANUAL_PUBLISH",confirmedBy:actor.email,confirmedAt:now,postUrl:postUrl.href});
  await env.DB.batch([
   env.DB.prepare("UPDATE publishing_records SET status='PUBLISHED',published_at=?,post_url=?,result=?,requires_human_action=0,error_code=NULL,error_message=NULL,performance_sync_status='MANUAL',updated_at=? WHERE id=? AND project_id=?").bind(now,postUrl.href,evidence,now,recordId,projectId),
   record.jobId?env.DB.prepare("UPDATE orchestrator_jobs SET status='SUCCEEDED',completed_at=?,last_error=NULL,updated_at=? WHERE id=? AND project_id=?").bind(now,now,record.jobId,projectId):env.DB.prepare("SELECT 1"),
   env.DB.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(projectId,"publishing_manually_confirmed",actor.email,JSON.stringify({recordId,...JSON.parse(evidence)}),now),
  ]);
  return Response.json({ok:true,...await publishingData(env.DB,projectId,null,requestedBatchId)});
 }
 if(action==="manual_exception"){
  const recordId=Number(body.recordId||0),record=await env.DB.prepare("SELECT id,job_id AS jobId,platform,error_code AS errorCode FROM publishing_records WHERE id=? AND project_id=?").bind(recordId,projectId).first<any>();if(!record)return Response.json({error:"Publishing Record not found."},{status:404});if(["Instagram","Threads"].includes(String(record.platform||"")))return Response.json({error:"A technical Instagram / Threads publishing failure cannot be accepted as a Manual Exception. Fix the connector or media delivery, then retry."},{status:409});await env.DB.batch([env.DB.prepare("UPDATE publishing_records SET status='MANUAL_EXCEPTION',requires_human_action=1,error_code=NULL,error_message=?,post_url=COALESCE(?,post_url),updated_at=? WHERE id=?").bind(String(body.note||"Accepted manual publishing exception."),body.postUrl?String(body.postUrl):null,now,recordId),record.jobId?env.DB.prepare("UPDATE orchestrator_jobs SET status='CANCELLED',last_error='Manual exception accepted',completed_at=?,updated_at=? WHERE id=?").bind(now,now,record.jobId):env.DB.prepare("SELECT 1"),env.DB.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(projectId,"publishing_manual_exception",actor.email,JSON.stringify({recordId,note:body.note||""}),now)]);return Response.json({ok:true,...await publishingData(env.DB,projectId,null,requestedBatchId)});
 }
 if(action==="sync_performance"){
 const records=body.recordId?[await env.DB.prepare("SELECT * FROM publishing_records WHERE id=? AND project_id=?").bind(Number(body.recordId),projectId).first<any>()]:requestedBatchId?(await env.DB.prepare("SELECT * FROM publishing_records WHERE project_id=? AND batch_id=? AND status='PUBLISHED' AND provider_media_id IS NOT NULL ORDER BY published_at DESC LIMIT 100").bind(projectId,requestedBatchId).all()).results as any[]:(await env.DB.prepare("SELECT * FROM publishing_records WHERE project_id=? AND status='PUBLISHED' AND provider_media_id IS NOT NULL ORDER BY published_at DESC LIMIT 100").bind(projectId).all()).results as any[];
 const synced=[];for(const record of records.filter(Boolean)){try{synced.push({id:record.id,metrics:await syncRecordPerformance(env.DB,env,record)})}catch(error:any){await env.DB.prepare("UPDATE publishing_records SET performance_sync_status='NEEDS_ATTENTION',error_message=?,updated_at=? WHERE id=?").bind(String(error.message||error),now,record.id).run()}}
 const connectionRows=await env.DB.prepare("SELECT connection_id AS socialConnectionId,platform FROM project_social_connections WHERE project_id=? AND status='Connected'").bind(projectId).all(),profiles=[];for(const row of connectionRows.results as any[])try{profiles.push({platform:row.platform,socialConnectionId:row.socialConnectionId,metrics:await syncProfilePerformance(env.DB,env,projectId,String(row.platform),String(row.socialConnectionId))})}catch{}
 const learning=await rebuildLearning(env.DB,projectId,requestedBatchId);await env.DB.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(projectId,"performance_synced",actor.email,JSON.stringify({batchId:requestedBatchId,records:synced.length,profiles:profiles.length,learning:learning.evidence}),now).run();return Response.json({ok:true,synced:synced.length,profiles:profiles.length,...await publishingData(env.DB,projectId,null,requestedBatchId)});
 }
 return Response.json({error:"Unknown Publishing action."},{status:400});
}catch(error){return apiError(error)}}
