import{loadIntegration}from"../integrations/_lib";
import{ensureConnectionIds,readProjectConnection}from"../social-connections/_lib";

const stamp=()=>new Date().toISOString();
const parse=(value:any,fallback:any={})=>{try{return JSON.parse(value||"")}catch{return fallback}};
const providerError=(message:string,code:string,status=409,details:any={})=>Object.assign(new Error(message),{code,status,details});
const contentOrder=(value:any)=>Number(String(value||"").match(/(\d+)/)?.[1]||9999);
const TEMPORARY_MEDIA_LIFETIME_MS=6*60*60*1000;
const POST_PUBLISH_RETENTION_MS=2*60*60*1000;
function malaysiaPublishingSlots(startValue:string,count:number){const start=new Date(`${startValue||stamp().slice(0,10)}T12:00:00.000Z`),tomorrow=new Date();tomorrow.setUTCDate(tomorrow.getUTCDate()+1);tomorrow.setUTCHours(12,0,0,0);let cursor=start>tomorrow?start:tomorrow,slots:string[]=[];while(slots.length<count){if([1,3,5].includes(cursor.getUTCDay()))slots.push(cursor.toISOString());cursor=new Date(cursor.getTime()+86400000)}return slots}

export async function repairLegacyHanaPublishingBatch(db:any,projectId:string){
 const prior=await db.prepare("SELECT id FROM audit_log WHERE project_id=? AND event_type='publishing_schedule_v2_backfill' LIMIT 1").bind(projectId).first();if(prior)return{applied:false};const project=await db.prepare("SELECT client FROM projects WHERE id=?").bind(projectId).first<any>(),hana=projectId==="PRJ-0001"&&/hana/i.test(String(project?.client||""));if(!hana)return{applied:false};const published=await db.prepare("SELECT COUNT(*) AS count FROM publishing_records WHERE project_id=? AND status='PUBLISHED'").bind(projectId).first<any>();if(Number(published?.count||0)>0)return{applied:false};
 await ensureConnectionIds(db,projectId);const connection=await db.prepare("SELECT connection_id AS connectionId,external_account_id AS accountId,handle FROM project_social_connections WHERE project_id=? AND platform='Instagram' ORDER BY is_default DESC,connected_at LIMIT 1").bind(projectId).first<any>();if(!connection)return{applied:false};const batch=await db.prepare("SELECT id,starts_at AS startsAt,ends_at AS endsAt FROM production_batches WHERE project_id=? ORDER BY CASE WHEN status='Active' THEN 0 ELSE 1 END,batch_number DESC LIMIT 1").bind(projectId).first<any>(),records=(await db.prepare("SELECT id,job_id AS jobId,content_key AS contentKey,platform FROM publishing_records WHERE project_id=? ORDER BY id").bind(projectId).all()).results as any[];if(!records.length)return{applied:false};const keys=[...new Set(records.map(row=>String(row.contentKey||"")).filter(Boolean))].sort((a,b)=>contentOrder(a)-contentOrder(b)),slots=malaysiaPublishingSlots(String(batch?.startsAt||""),keys.length),kept:any[]=[],removed:any[]=[];
 for(let index=0;index<keys.length;index++){const key=keys[index],rows=records.filter(row=>row.contentKey===key),keep=rows.find(row=>row.platform==="Instagram")||rows[0],duplicates=rows.filter(row=>row.id!==keep.id),scheduledAt=slots[index],job=keep.jobId?await db.prepare("SELECT input_payload AS inputPayload FROM orchestrator_jobs WHERE id=?").bind(keep.jobId).first<any>():null,payload=parse(job?.inputPayload,{});payload.platform="Instagram";payload.scheduledFor=scheduledAt;payload.batchId=batch?.id||null;payload.publishingOrder=index+1;payload.socialConnectionId=connection.connectionId;for(const duplicate of duplicates){if(duplicate.jobId){await db.prepare("DELETE FROM orchestrator_job_tokens WHERE job_id=?").bind(duplicate.jobId).run();await db.prepare("DELETE FROM orchestrator_job_events WHERE job_id=?").bind(duplicate.jobId).run();await db.prepare("DELETE FROM orchestrator_jobs WHERE id=?").bind(duplicate.jobId).run()}await db.prepare("DELETE FROM publishing_attempts WHERE publishing_record_id=? OR job_id=?").bind(duplicate.id,duplicate.jobId||"").run();await db.prepare("DELETE FROM publishing_records WHERE id=?").bind(duplicate.id).run();removed.push(duplicate.id)}if(keep.jobId)await db.prepare("UPDATE orchestrator_jobs SET provider='connector:instagram',input_payload=?,status='SCHEDULED',attempt_count=0,scheduled_for=?,started_at=NULL,completed_at=NULL,last_error=NULL,updated_at=? WHERE id=?").bind(JSON.stringify(payload),scheduledAt,stamp(),keep.jobId).run();await db.prepare("UPDATE publishing_records SET batch_id=?,publishing_order=?,platform='Instagram',social_connection_id=?,connected_account_id=?,connected_handle=?,scheduled_at=?,status='SCHEDULED',error_code=NULL,error_message=NULL,retry_count=0,requires_human_action=0,updated_at=? WHERE id=?").bind(batch?.id||null,index+1,connection.connectionId,connection.accountId,connection.handle,scheduledAt,stamp(),keep.id).run();kept.push({contentKey:key,recordId:keep.id,scheduledAt})}
 const snapshot=await db.prepare("SELECT id,approved_content AS content FROM approved_phase_snapshots WHERE project_id=? AND phase_key='batch-ideas' ORDER BY version DESC LIMIT 1").bind(projectId).first<any>();if(snapshot){const content=parse(snapshot.content,{}),items=Array.isArray(content.content_items)?content.content_items:[];content.content_items=items.map((item:any,index:number)=>({...item,platforms:["Instagram"],plannedPlatforms:["Instagram"],planned_platforms:["Instagram"],publishingSchedule:[{platform:"Instagram",scheduledAt:slots[index]||slots.at(-1),order:1,socialConnectionId:connection.connectionId}],publishing_schedule:[{platform:"Instagram",scheduled_at:slots[index]||slots.at(-1),order:1,social_connection_id:connection.connectionId}]}));content.batch_gate_notes=`${String(content.batch_gate_notes||"")} Legacy destination repair: this approved Batch publishes to Instagram only; Agent schedule backfilled at 3 posts/week.`.trim();await db.prepare("UPDATE approved_phase_snapshots SET approved_content=? WHERE id=?").bind(JSON.stringify(content),snapshot.id).run()}
 const now=stamp();await db.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(projectId,"publishing_schedule_v2_backfill","system:migration",JSON.stringify({batchId:batch?.id||null,cadence:"3 posts/week",timezone:"Asia/Kuala_Lumpur",destination:"Instagram",socialConnectionId:connection.connectionId,kept,removed}),now).run();return{applied:true,kept,removed};
}

async function graph(url:string,token:string,options:RequestInit={}){
 const target=new URL(url);if((options.method||"GET")==="GET")target.searchParams.set("access_token",token);
 const headers:any={...(options.headers||{})};if((options.method||"GET")!=="GET")headers.authorization=`Bearer ${token}`;
 const response=await fetch(target,{...options,headers}),result:any=await response.json().catch(()=>({}));
 if(!response.ok||result?.error)throw providerError(result?.error?.message||`Provider returned HTTP ${response.status}.`,String(result?.error?.code||"PROVIDER_REJECTED"),response.status>=500?502:409,result);
 return result;
}

async function postForm(url:string,token:string,data:Record<string,any>){const body=new URLSearchParams();for(const[key,value]of Object.entries(data))if(value!==undefined&&value!==null&&value!=="")body.set(key,Array.isArray(value)?value.join(","):String(value));return graph(url,token,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body})}

function safeFileName(value:string){return(value||"asset").replace(/[^a-zA-Z0-9._-]/g,"-").slice(-180)||"asset"}
function externalStorage(env:any){const base=String(env.PUBLISHING_STORAGE_URL||"").replace(/\/$/,""),secret=String(env.PUBLISHING_STORAGE_SECRET||"");if(!/^https:\/\//.test(base)||!secret)throw providerError("Temporary Publishing Storage is not configured.","PUBLISHING_STORAGE_NOT_CONFIGURED",503);return{base,secret}}
async function externalStorageRequest(env:any,path:string,options:RequestInit={}){const storage=externalStorage(env),headers=new Headers(options.headers||{});headers.set("authorization",`Bearer ${storage.secret}`);const response=await fetch(`${storage.base}${path}`,{...options,headers}),result:any=await response.json().catch(()=>({}));if(!response.ok)throw providerError(result?.error||`Temporary Publishing Storage returned HTTP ${response.status}.`,"PUBLISHING_STORAGE_FAILED",response.status>=500?502:409,result);return result}
export async function cleanupTemporaryPublishingAssets(db:any,env:any){const now=stamp(),rows=await db.prepare("SELECT id,access_token AS accessToken,temporary_storage_key AS temporaryStorageKey FROM temporary_publishing_assets WHERE status='ACTIVE' AND (expires_at<=? OR (delete_after IS NOT NULL AND delete_after<=?)) ORDER BY id LIMIT 100").bind(now,now).all(),deleted=[] as number[];for(const row of rows.results as any[]){if(String(row.temporaryStorageKey||"").startsWith("external:")){try{await externalStorageRequest(env,`/api/assets/${row.accessToken}`,{method:"DELETE"})}catch{}}else await env.BUCKET.delete(String(row.temporaryStorageKey));await db.prepare("UPDATE temporary_publishing_assets SET status='DELETED',deleted_at=?,updated_at=? WHERE id=?").bind(now,now,row.id).run();deleted.push(Number(row.id))}try{await externalStorageRequest(env,"/api/cleanup",{method:"POST"})}catch{}return deleted}
async function retainTemporaryPublishingAssets(db:any,env:any,recordId:number){const now=stamp(),deleteAfter=new Date(Date.now()+POST_PUBLISH_RETENTION_MS).toISOString(),rows=await db.prepare("SELECT access_token AS accessToken,temporary_storage_key AS temporaryStorageKey FROM temporary_publishing_assets WHERE publishing_record_id=? AND status='ACTIVE'").bind(recordId).all();await db.prepare("UPDATE temporary_publishing_assets SET delete_after=CASE WHEN delete_after IS NULL OR delete_after>? THEN ? ELSE delete_after END,updated_at=? WHERE publishing_record_id=? AND status='ACTIVE'").bind(deleteAfter,deleteAfter,now,recordId).run();for(const row of rows.results as any[])if(String(row.temporaryStorageKey||"").startsWith("external:"))try{await externalStorageRequest(env,`/api/assets/${row.accessToken}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({deleteAfter})})}catch{}}
async function publishingUrl(db:any,env:any,job:any,record:any,asset:any){
 const storageKey=String(asset.storageKey||asset.storage_key||"");if(!storageKey){const direct=String(asset.publicUrl||asset.url||"");if(/^https:\/\//.test(direct))return direct;throw providerError("Approved media is missing its storage key.","MEDIA_NOT_FOUND")}
 const now=stamp(),existing=await db.prepare("SELECT access_token AS accessToken FROM temporary_publishing_assets WHERE publishing_record_id=? AND original_storage_key=? AND status='ACTIVE' AND expires_at>? AND temporary_storage_key LIKE 'external:%' ORDER BY id DESC LIMIT 1").bind(record.id,storageKey,now).first<any>();if(existing?.accessToken)return`${externalStorage(env).base}/media/${existing.accessToken}`;
 const object=await env.BUCKET.get(storageKey);if(!object)throw providerError("Approved media could not be read from private Project storage.","MEDIA_DOWNLOAD_FAILED");
 let fileName=safeFileName(String(asset.fileName||asset.file_name||storageKey.split("/").pop()||"asset")),mimeType=String(asset.mimeType||asset.mime_type||object.httpMetadata?.contentType||"application/octet-stream");const uploaded=await externalStorageRequest(env,"/api/assets",{method:"POST",headers:{"content-type":mimeType,"x-file-name":fileName,"x-frameflow-project":job.projectId,"x-frameflow-job":job.id,"x-expires-seconds":String(TEMPORARY_MEDIA_LIFETIME_MS/1000),"x-convert-to-jpeg":String(job.inputPayload.platform||"")==="Instagram"&&mimeType.startsWith("image/")?"1":"0"},body:object.body as any});const accessToken=String(uploaded.token||""),publicUrl=String(uploaded.url||""),expiresAt=String(uploaded.expiresAt||"");if(!/^[a-f0-9]{64}$/.test(accessToken)||!/^https:\/\//.test(publicUrl)||!Number.isFinite(Date.parse(expiresAt)))throw providerError("Temporary Publishing Storage returned an invalid media reference.","PUBLISHING_STORAGE_FAILED",502);mimeType=String(uploaded.mimeType||mimeType);fileName=String(uploaded.fileName||fileName);const probe=await fetch(publicUrl,{method:"HEAD"});if(!probe.ok||!String(probe.headers.get("content-type")||"").toLowerCase().startsWith(mimeType.split("/")[0]+"/"))throw providerError("Temporary publishing media is not publicly readable by Meta.","PUBLISHING_MEDIA_NOT_PUBLIC",502);await db.prepare("INSERT INTO temporary_publishing_assets(project_id,publishing_record_id,job_id,access_token,original_storage_key,temporary_storage_key,file_name,mime_type,status,expires_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,'ACTIVE',?,?,?)").bind(job.projectId,record.id,job.id,accessToken,storageKey,`external:${accessToken}`,fileName,mimeType,expiresAt,now,now).run();return publicUrl;
}

async function saveInstagramProgress(db:any,record:any,update:any,primaryContainerId?:string){const now=stamp(),root=parse(record.result,{}),progress={...(root.instagramPublishing||{}),...update,updatedAt:now};root.instagramPublishing=progress;await db.prepare("UPDATE publishing_records SET provider_container_id=COALESCE(?,provider_container_id),result=?,updated_at=? WHERE id=?").bind(primaryContainerId||null,JSON.stringify(root),now,record.id).run();record.result=JSON.stringify(root);if(primaryContainerId)record.provider_container_id=primaryContainerId;return progress}
async function waitInstagramContainer(db:any,record:any,containerId:string,token:string,base:string,stage:string,primary=false){let state:any={};for(let i=0;i<10;i++){state=await graph(`${base}/${containerId}?fields=status_code,status`,token);const statusCode=String(state.status_code||state.status||"").toUpperCase();await saveInstagramProgress(db,record,{stage,lastContainerId:containerId,lastStatusCode:statusCode,lastStatus:state.status||null,lastStatusResponse:state},primary?containerId:undefined);if(statusCode==="FINISHED"||statusCode==="PUBLISHED")return{...state,statusCode};if(statusCode==="ERROR"||statusCode==="EXPIRED")throw providerError(String(state.status||`Instagram container ${statusCode}.`),`INSTAGRAM_CONTAINER_${statusCode}`,409,{containerId,stage,...state});await new Promise(resolve=>setTimeout(resolve,2000))}throw providerError("Instagram media container is still IN_PROGRESS. FrameFlow saved the Container ID and will continue polling without creating another post.","MEDIA_PROCESSING_PENDING",429,{containerId,stage,...state})}

async function publishInstagram(db:any,env:any,job:any,record:any,connection:any,assets:any[]){
 const base=`https://graph.instagram.com/${connection.tokenConfig.apiVersion||"v26.0"}`,caption=[job.inputPayload.caption,job.inputPayload.hashtags].filter(Boolean).join("\n\n");
 if(record.status==="PUBLISHED"&&record.provider_media_id&&record.post_url)return{platform:"Instagram",providerPostId:String(record.provider_post_id||record.provider_media_id),providerMediaId:String(record.provider_media_id),providerContainerId:String(record.provider_container_id||""),postUrl:String(record.post_url),publishedAt:String(record.published_at||stamp()),raw:parse(record.result,{})};
 if(record.provider_media_id){const mediaId=String(record.provider_media_id),media=await graph(`${base}/${mediaId}?fields=id,permalink`,connection.token);if(!media.permalink)throw providerError("Instagram published the media but its permalink is not available yet. FrameFlow will retry the permalink lookup without publishing again.","PERMALINK_PENDING",429,{mediaId});return{platform:"Instagram",providerPostId:String(record.provider_post_id||mediaId),providerMediaId:mediaId,providerContainerId:String(record.provider_container_id||""),postUrl:String(media.permalink),publishedAt:String(record.published_at||stamp()),raw:{containerId:record.provider_container_id||null,media}}}
 if(!assets.length)throw providerError("Instagram publishing requires at least one approved image or video.","MEDIA_REQUIRED");
 const root=parse(record.result,{}),saved=root.instagramPublishing||{},childContainerIds:Array<string>=[...(Array.isArray(saved.childContainerIds)?saved.childContainerIds:[])];let containerId=String(record.provider_container_id||saved.containerId||"");
 if(!containerId&&assets.length>1){for(let index=0;index<assets.length;index++){let childId=String(childContainerIds[index]||"");if(!childId){const url=await publishingUrl(db,env,job,record,assets[index]),video=String(assets[index]?.mimeType||"").startsWith("video/"),child=await postForm(`${base}/${connection.accountId}/media`,connection.token,{...(video?{media_type:"VIDEO",video_url:url}:{image_url:url}),is_carousel_item:true});childId=String(child.id||"");if(!childId)throw providerError("Instagram did not return a child Container ID.","CONTAINER_ID_MISSING",502,child);childContainerIds[index]=childId;await saveInstagramProgress(db,record,{stage:"CHILD_CONTAINER_CREATED",childContainerIds})}await waitInstagramContainer(db,record,childId,connection.token,base,`CHILD_${index+1}`)}const parent=await postForm(`${base}/${connection.accountId}/media`,connection.token,{media_type:"CAROUSEL",children:childContainerIds,caption});containerId=String(parent.id||"");if(!containerId)throw providerError("Instagram did not return a Carousel Container ID.","CONTAINER_ID_MISSING",502,parent);await saveInstagramProgress(db,record,{stage:"CONTAINER_CREATED",containerId,childContainerIds},containerId)}
 if(!containerId){const url=await publishingUrl(db,env,job,record,assets[0]),video=String(assets[0]?.mimeType||"").startsWith("video/")||String(job.inputPayload.contentType||"").toLowerCase()==="reel",created=await postForm(`${base}/${connection.accountId}/media`,connection.token,video?{media_type:"REELS",video_url:url,caption,share_to_feed:true}:{image_url:url,caption});containerId=String(created.id||"");if(!containerId)throw providerError("Instagram did not return a Container ID.","CONTAINER_ID_MISSING",502,created);await saveInstagramProgress(db,record,{stage:"CONTAINER_CREATED",containerId},containerId)}
 const containerState=await waitInstagramContainer(db,record,containerId,connection.token,base,"PRIMARY_CONTAINER",true);if(containerState.statusCode==="PUBLISHED")throw providerError("Instagram reports this Container as already PUBLISHED. FrameFlow stopped before /media_publish to prevent a duplicate post; the existing post requires Media ID recovery.","CONTAINER_ALREADY_PUBLISHED",409,{containerId,containerState});
 await saveInstagramProgress(db,record,{stage:"PUBLISH_REQUESTED",containerId,publishRequestedAt:stamp()},containerId);const published=await postForm(`${base}/${connection.accountId}/media_publish`,connection.token,{creation_id:containerId}),mediaId=String(published.id||"");if(!mediaId)throw providerError("Instagram /media_publish did not return the final Media ID.","MEDIA_ID_MISSING",502,published);const now=stamp();await db.prepare("UPDATE publishing_records SET provider_post_id=?,provider_media_id=?,result=?,updated_at=? WHERE id=?").bind(mediaId,mediaId,JSON.stringify({instagramPublishing:{...(parse(record.result,{}).instagramPublishing||{}),stage:"MEDIA_PUBLISHED",containerId,providerMediaId:mediaId,publishResponse:published,updatedAt:now}}),now,record.id).run();record.provider_post_id=mediaId;record.provider_media_id=mediaId;
 const media=await graph(`${base}/${mediaId}?fields=id,permalink`,connection.token);if(!media.permalink)throw providerError("Instagram returned a Media ID but the Live Post URL is not available yet. FrameFlow will retry the permalink lookup without publishing again.","PERMALINK_PENDING",429,{containerId,mediaId,media});return{platform:"Instagram",providerPostId:mediaId,providerMediaId:mediaId,providerContainerId:containerId,postUrl:String(media.permalink),publishedAt:stamp(),raw:{containerId,publishResponse:published,media}};
}

async function publishThreads(db:any,env:any,job:any,record:any,connection:any,assets:any[]){
 const base="https://graph.threads.net/v1.0",text=[job.inputPayload.caption,job.inputPayload.hashtags].filter(Boolean).join("\n\n"),urls=[];for(const asset of assets)urls.push(await publishingUrl(db,env,job,record,asset));let creationId="";
 if(urls.length>1){const children=[];for(let index=0;index<urls.length;index++){const video=String(assets[index]?.mimeType||"").startsWith("video/"),child=await postForm(`${base}/${connection.accountId}/threads`,connection.token,{media_type:video?"VIDEO":"IMAGE",...(video?{video_url:urls[index]}:{image_url:urls[index]}),is_carousel_item:true});children.push(child.id)}const parent=await postForm(`${base}/${connection.accountId}/threads`,connection.token,{media_type:"CAROUSEL",children,text});creationId=String(parent.id)}else if(urls.length===1){const video=String(assets[0]?.mimeType||"").startsWith("video/"),created=await postForm(`${base}/${connection.accountId}/threads`,connection.token,{media_type:video?"VIDEO":"IMAGE",...(video?{video_url:urls[0]}:{image_url:urls[0]}),text});creationId=String(created.id)}else{const created=await postForm(`${base}/${connection.accountId}/threads`,connection.token,{media_type:"TEXT",text});creationId=String(created.id)}
 const published=await postForm(`${base}/${connection.accountId}/threads_publish`,connection.token,{creation_id:creationId}),postId=String(published.id),post=await graph(`${base}/${postId}?fields=id,permalink`,connection.token);
 return{platform:"Threads",providerPostId:postId,providerMediaId:postId,postUrl:String(post.permalink||`https://www.threads.net/@${String(connection.handle||"").replace(/^@/,"")}`),publishedAt:stamp(),raw:published};
}

export async function ensurePublishingRecord(db:any,job:any){
 await ensureConnectionIds(db,job.projectId);const requestedId=String(job.inputPayload.socialConnectionId||""),connection=requestedId?await db.prepare("SELECT connection_id AS connectionId,external_account_id AS accountId,handle FROM project_social_connections WHERE project_id=? AND platform=? AND connection_id=?").bind(job.projectId,String(job.inputPayload.platform||""),requestedId).first<any>():await db.prepare("SELECT connection_id AS connectionId,external_account_id AS accountId,handle FROM project_social_connections WHERE project_id=? AND platform=? ORDER BY is_default DESC,CASE WHEN status='Connected' THEN 0 ELSE 1 END,connected_at LIMIT 1").bind(job.projectId,String(job.inputPayload.platform||"")).first<any>(),now=stamp(),status=job.scheduledFor&&job.status==="SCHEDULED"?"SCHEDULED":"READY";
 await db.prepare("INSERT INTO publishing_records(job_id,project_id,batch_id,content_key,publishing_order,platform,social_connection_id,connected_account_id,connected_handle,caption,assets,scheduled_at,status,result,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(job_id) DO UPDATE SET batch_id=COALESCE(excluded.batch_id,publishing_records.batch_id),publishing_order=excluded.publishing_order,scheduled_at=excluded.scheduled_at,caption=excluded.caption,assets=excluded.assets,social_connection_id=COALESCE(excluded.social_connection_id,publishing_records.social_connection_id),connected_account_id=COALESCE(excluded.connected_account_id,publishing_records.connected_account_id),connected_handle=COALESCE(excluded.connected_handle,publishing_records.connected_handle),status=CASE WHEN publishing_records.status IN ('PUBLISHED','MANUAL_EXCEPTION','MANUAL_REQUIRED') OR publishing_records.error_code IN ('CONNECTOR_NOT_SUPPORTED','LIVE_PUBLISHING_NOT_IMPLEMENTED','ACCOUNT_NOT_CONNECTED','MISSED_SCHEDULE') THEN publishing_records.status WHEN excluded.scheduled_at IS NOT NULL THEN 'SCHEDULED' ELSE 'READY' END,updated_at=excluded.updated_at").bind(job.id,job.projectId,job.inputPayload.batchId||null,job.contentId||null,Number(job.inputPayload.publishingOrder||0),String(job.inputPayload.platform||"Social"),connection?.connectionId||job.inputPayload.socialConnectionId||null,connection?.accountId||null,connection?.handle||null,String(job.inputPayload.caption||""),JSON.stringify(job.inputAssets||[]),job.scheduledFor||null,status,"{}",now,now).run();
 return db.prepare("SELECT * FROM publishing_records WHERE job_id=?").bind(job.id).first<any>();
}

export async function executePublishJob(db:any,env:any,job:any){
 const platform=String(job.inputPayload.platform||"");if(!job.scheduledFor||!Number.isFinite(Date.parse(job.scheduledFor)))throw providerError("Publishing is blocked until Agent assigns a valid scheduledAt in the approved Two-week Batch.","SCHEDULE_REQUIRED",400);const connection=await readProjectConnection(db,env,job.projectId,platform,String(job.inputPayload.socialConnectionId||"")||null);if(!["Instagram","Threads"].includes(platform))throw providerError(`${platform||"This platform"} is manual / not supported in Publishing v1.`,"CONNECTOR_NOT_SUPPORTED");if(!connection?.connected)throw providerError(`${platform} is not connected to this Project or its token needs reconnection.`,"ACCOUNT_NOT_CONNECTED");
 const record=await ensurePublishingRecord(db,job);if(record.status==="PUBLISHED"&&record.provider_media_id&&record.post_url)return{platform,providerPostId:String(record.provider_post_id||record.provider_media_id),providerMediaId:String(record.provider_media_id),providerContainerId:String(record.provider_container_id||""),postUrl:String(record.post_url),publishedAt:String(record.published_at||stamp()),raw:parse(record.result,{})};const attempt=Number(record.retry_count||0)+1,startedAt=stamp();await db.prepare("UPDATE publishing_records SET status='PUBLISHING',connected_account_id=?,connected_handle=?,error_code=NULL,error_message=NULL,updated_at=? WHERE id=?").bind(connection.accountId,connection.handle,startedAt,record.id).run();await db.prepare("INSERT INTO publishing_attempts(publishing_record_id,job_id,project_id,platform,attempt_number,status,started_at) VALUES(?,?,?,?,?,'PUBLISHING',?)").bind(record.id,job.id,job.projectId,platform,attempt,startedAt).run();
 try{const result=platform==="Instagram"?await publishInstagram(db,env,job,record,connection,job.inputAssets||[]):await publishThreads(db,env,job,record,connection,job.inputAssets||[]),completed=stamp();await db.prepare("UPDATE publishing_records SET status='PUBLISHED',published_at=?,provider_container_id=COALESCE(?,provider_container_id),provider_post_id=?,provider_media_id=?,post_url=?,result=?,performance_sync_status='PENDING',telegram_notification_status='PENDING',telegram_notified_at=NULL,telegram_notification_error=NULL,error_code=NULL,error_message=NULL,requires_human_action=0,updated_at=? WHERE id=?").bind(result.publishedAt,result.providerContainerId||null,result.providerPostId,result.providerMediaId,result.postUrl,JSON.stringify(result.raw||{}),completed,record.id).run();await db.prepare("UPDATE publishing_attempts SET status='PUBLISHED',provider_response=?,completed_at=? WHERE publishing_record_id=? AND attempt_number=?").bind(JSON.stringify(result.raw||{}),completed,record.id,attempt).run();await retainTemporaryPublishingAssets(db,env,record.id);return result}catch(error:any){const retryable=[429,500,502,503,504].includes(Number(error.status||0))||["MEDIA_PROCESSING_PENDING","PERMALINK_PENDING","RATE_LIMIT"].includes(String(error.code||"")),completed=stamp();await db.prepare("UPDATE publishing_records SET status='NEEDS_ATTENTION',error_code=?,error_message=?,retry_count=?,requires_human_action=?,updated_at=? WHERE id=?").bind(error.code||"PUBLISH_FAILED",String(error.message||error),attempt,retryable?0:1,completed,record.id).run();await db.prepare("UPDATE publishing_attempts SET status='FAILED',error_code=?,error_message=?,provider_response=?,completed_at=? WHERE publishing_record_id=? AND attempt_number=?").bind(error.code||"PUBLISH_FAILED",String(error.message||error),JSON.stringify(error.details||{}),completed,record.id,attempt).run();throw error}
}

export async function syncRecordPerformance(db:any,env:any,record:any){
 const platform=String(record.platform),connection=await readProjectConnection(db,env,record.project_id,platform,record.social_connection_id||null);if(!connection?.connected||!record.provider_media_id)throw providerError("A connected account and Provider Media ID are required for Performance Sync.","PERFORMANCE_NOT_READY");
 let raw:any={};if(platform==="Instagram"){const base=`https://graph.instagram.com/${connection.tokenConfig.apiVersion||"v26.0"}`;try{raw=await graph(`${base}/${record.provider_media_id}/insights?metric=views,reach,saved,shares,total_interactions`,connection.token)}catch{raw=await graph(`${base}/${record.provider_media_id}?fields=id,like_count,comments_count`,connection.token)}}else raw=await graph(`https://graph.threads.net/v1.0/${record.provider_media_id}/insights?metric=views,likes,replies,reposts,quotes,shares`,connection.token);
 const flattened:any={};for(const item of raw.data||[])flattened[item.name]=Number(item.values?.[0]?.value??item.total_value?.value??0);for(const key of["like_count","comments_count"])if(raw[key]!=null)flattened[key]=Number(raw[key]);const normalized={views:Number(flattened.views||0),reach:Number(flattened.reach||0),likes:Number(flattened.likes||flattened.like_count||0),comments:Number(flattened.replies||flattened.comments_count||0),shares:Number(flattened.shares||flattened.reposts||0),saves:Number(flattened.saved||0),engagement:Number(flattened.total_interactions||0)};if(!normalized.engagement)normalized.engagement=normalized.likes+normalized.comments+normalized.shares+normalized.saves;
 const capturedAt=stamp();await db.batch([db.prepare("UPDATE publishing_records SET raw_metrics=?,normalized_metrics=?,performance_sync_status='SYNCED',updated_at=? WHERE id=?").bind(JSON.stringify(raw),JSON.stringify(normalized),capturedAt,record.id),db.prepare("INSERT INTO social_performance_snapshots(project_id,batch_id,platform,social_connection_id,connected_account_id,publishing_record_id,scope,captured_at,raw_metrics,normalized_metrics) VALUES(?,?,?,?,?,?,'CONTENT',?,?,?)").bind(record.project_id,record.batch_id||null,platform,connection.connectionId,connection.accountId,record.id,capturedAt,JSON.stringify(raw),JSON.stringify(normalized))]);return normalized;
}

export async function syncProfilePerformance(db:any,env:any,projectId:string,platform:string,connectionId?:string|null){
 const connection=await readProjectConnection(db,env,projectId,platform,connectionId);if(!connection?.connected)throw providerError(`${platform} is not connected for Profile Performance Sync.`,"ACCOUNT_NOT_CONNECTED");let raw:any={};
 if(platform==="Instagram")raw=await graph(`https://graph.instagram.com/${connection.tokenConfig.apiVersion||"v26.0"}/me?fields=user_id,username,followers_count,media_count`,connection.token);else try{raw=await graph("https://graph.threads.net/v1.0/me/threads_insights?metric=followers_count,views,likes,replies,reposts,quotes",connection.token)}catch{raw=await graph("https://graph.threads.net/v1.0/me?fields=id,username",connection.token)}
 const values:any={};for(const item of raw.data||[])values[item.name]=Number(item.values?.[0]?.value??item.total_value?.value??0);const normalized={followers:Number(raw.followers_count||values.followers_count||0),views:Number(values.views||0),reach:Number(values.reach||0),engagement:Number(values.likes||0)+Number(values.replies||0)+Number(values.reposts||0)+Number(values.quotes||0)},capturedAt=stamp();await db.prepare("INSERT INTO social_performance_snapshots(project_id,platform,social_connection_id,connected_account_id,publishing_record_id,scope,captured_at,raw_metrics,normalized_metrics) VALUES(?,?,?,?,NULL,'PROFILE',?,?,?)").bind(projectId,platform,connection.connectionId,connection.accountId,capturedAt,JSON.stringify(raw),JSON.stringify(normalized)).run();return normalized;
}

function projectTime(value:string){try{return new Intl.DateTimeFormat("en-MY",{timeZone:"Asia/Kuala_Lumpur",dateStyle:"medium",timeStyle:"short",hour12:true}).format(new Date(value))}catch{return value}}

export async function sendPublishedTelegramNotification(db:any,env:any,recordId:number){
 const record=await db.prepare("SELECT r.id,r.project_id AS projectId,r.content_key AS contentKey,r.platform,r.connected_handle AS connectedHandle,r.published_at AS publishedAt,r.post_url AS postUrl,r.telegram_notification_status AS notificationStatus,p.client,o.input_payload AS inputPayload FROM publishing_records r JOIN projects p ON p.id=r.project_id LEFT JOIN orchestrator_jobs o ON o.id=r.job_id WHERE r.id=? AND r.status='PUBLISHED' AND r.post_url IS NOT NULL").bind(recordId).first<any>();
 if(!record||["SENT","LEGACY_SKIPPED","SENDING"].includes(String(record.notificationStatus||"")))return{sent:false,skipped:true,status:record?.notificationStatus||"NOT_READY"};
 const claimed=await db.prepare("UPDATE publishing_records SET telegram_notification_status='SENDING',telegram_notification_error=NULL,updated_at=? WHERE id=? AND telegram_notification_status IN ('PENDING','FAILED')").bind(stamp(),recordId).run();
 if(!Number(claimed?.meta?.changes||0))return{sent:false,skipped:true,status:"ALREADY_CLAIMED"};
 try{
  const telegram=await loadIntegration(db,env,"telegram");if(!telegram?.secret||String(telegram.status||"").toLowerCase()==="disconnected")throw new Error("Telegram is not connected in System Connections.");
  const config=telegram.config||{},chatId=String(config.chatId||config.chat_id||"8009020714"),payload=parse(record.inputPayload,{}),title=String(payload.title||record.contentKey||`Publishing Record ${record.id}`),handle=String(record.connectedHandle||payload.profileHandle||"");
  const message=["Agent publishing update ✅","",`Project: ${record.client} (${record.projectId})`,`Content: ${title}`,`Platform: ${record.platform}${handle?` · ${handle.startsWith("@")?handle:`@${handle}`}`:""}`,record.publishedAt?`Published: ${projectTime(record.publishedAt)} MYT`:"","",`Open live post: ${record.postUrl}`].filter(Boolean).join("\n");
  const response=await fetch(`https://api.telegram.org/bot${telegram.secret}/sendMessage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:chatId,text:message,disable_web_page_preview:false})}),result:any=await response.json().catch(()=>({}));
  if(!response.ok||result?.ok===false)throw new Error(String(result?.description||`Telegram returned HTTP ${response.status}.`));
  const sentAt=stamp();await db.batch([db.prepare("UPDATE publishing_records SET telegram_notification_status='SENT',telegram_notified_at=?,telegram_notification_error=NULL,updated_at=? WHERE id=?").bind(sentAt,sentAt,recordId),db.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(record.projectId,"publishing_telegram_notification_sent","system:agent",JSON.stringify({recordId,platform:record.platform,postUrl:record.postUrl,telegramMessageId:result?.result?.message_id||null}),sentAt)]);return{sent:true,sentAt};
 }catch(error:any){const failedAt=stamp(),message=String(error?.message||error);await db.batch([db.prepare("UPDATE publishing_records SET telegram_notification_status='FAILED',telegram_notification_error=?,updated_at=? WHERE id=?").bind(message,failedAt,recordId),db.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(record.projectId,"publishing_telegram_notification_failed","system:agent",JSON.stringify({recordId,error:message}),failedAt)]);return{sent:false,error:message};}
}

export async function deliverPendingPublishingNotifications(db:any,env:any,limit=20){
 const retryBefore=new Date(Date.now()-5*60*1000).toISOString();await db.prepare("UPDATE publishing_records SET telegram_notification_status='FAILED',telegram_notification_error='Notification claim expired before completion.',updated_at=? WHERE telegram_notification_status='SENDING' AND updated_at<=?").bind(stamp(),retryBefore).run();const rows=await db.prepare("SELECT id FROM publishing_records WHERE status='PUBLISHED' AND post_url IS NOT NULL AND (telegram_notification_status='PENDING' OR (telegram_notification_status='FAILED' AND updated_at<=?)) ORDER BY published_at,id LIMIT ?").bind(retryBefore,Math.max(1,Math.min(100,limit))).all(),results=[];
 for(const row of rows.results as any[])results.push({recordId:Number(row.id),...await sendPublishedTelegramNotification(db,env,Number(row.id))});return results;
}

export async function rebuildLearning(db:any,projectId:string,requestedBatchId:number|null=null){
 const rows=requestedBatchId===null?await db.prepare("SELECT id,batch_id AS batchId,platform,caption,published_at AS publishedAt,normalized_metrics AS metrics FROM publishing_records WHERE project_id=? AND status='PUBLISHED' AND performance_sync_status='SYNCED' AND published_at IS NOT NULL ORDER BY published_at DESC,id DESC LIMIT 100").bind(projectId).all():await db.prepare("SELECT id,batch_id AS batchId,platform,caption,published_at AS publishedAt,normalized_metrics AS metrics FROM publishing_records WHERE project_id=? AND batch_id=? AND status='PUBLISHED' AND performance_sync_status='SYNCED' AND published_at IS NOT NULL ORDER BY published_at DESC,id DESC LIMIT 100").bind(projectId,requestedBatchId).all(),all=(rows.results as any[]).map(x=>({...x,metrics:parse(x.metrics,{})})),latestBatchId=requestedBatchId??all.find(x=>x.batchId!==null&&x.batchId!==undefined)?.batchId??null,items=latestBatchId===null?all:all.filter(x=>String(x.batchId)===String(latestBatchId));
 if(!items.length)return{keep:[],improve:[],testNext:[],evidence:{sampleSize:0,verified:false},status:"INSUFFICIENT_EVIDENCE",saved:false};
 const times=items.map(x=>Date.parse(String(x.publishedAt||""))).filter(Number.isFinite).sort((a,b)=>a-b);
 if(!times.length)return{keep:[],improve:[],testNext:[],evidence:{sampleSize:items.length,verified:false,reason:"Missing valid publishedAt evidence window"},status:"INVALID_EVIDENCE_WINDOW",saved:false};
 const sourceWindowStart=new Date(times[0]).toISOString(),sourceWindowEnd=new Date(times.at(-1)!).toISOString();
 if(Date.parse(sourceWindowEnd)<Date.parse(sourceWindowStart))return{keep:[],improve:[],testNext:[],evidence:{sampleSize:items.length,verified:false,reason:"source_window_end precedes source_window_start"},status:"INVALID_EVIDENCE_WINDOW",saved:false};
 const scored=items.map(x=>({...x,score:Number(x.metrics.engagement||0)+Number(x.metrics.saves||0)*2+Number(x.metrics.shares||0)*2})).sort((a,b)=>b.score-a.score),top=scored[0],low=scored.at(-1),keep=top?[`${top.platform} content with strong saves / shares / engagement should inform the next Batch.`]:[],improve=low&&scored.length>1?[`Review the lowest-performing ${low.platform} post before repeating its hook, format or timing.`]:["Collect more verified posts before treating one result as a stable pattern."],testNext=["Test one controlled change in format or publishing time; keep the approved creative direction stable."],now=stamp(),batchKey=latestBatchId===null?`project:${sourceWindowStart.slice(0,10)}`:`batch:${latestBatchId}`,evidence={sampleSize:items.length,topScore:top?.score||0,platforms:[...new Set(items.map(x=>x.platform))],verified:true,batchId:latestBatchId,source:"provider-synced publishing records",authority:"EVIDENCE_ONLY_UNTIL_APPROVED"};
 const candidate=await db.prepare("SELECT id FROM batch_learning_records WHERE project_id=? AND batch_key=? AND status='PENDING_REVIEW' ORDER BY id DESC LIMIT 1").bind(projectId,batchKey).first<any>();
 if(candidate)await db.prepare("UPDATE batch_learning_records SET source_window_start=?,source_window_end=?,keep_json=?,improve_json=?,test_next_json=?,evidence_json=?,approved_by=NULL,approved_at=NULL,updated_at=? WHERE id=?").bind(sourceWindowStart,sourceWindowEnd,JSON.stringify(keep),JSON.stringify(improve),JSON.stringify(testNext),JSON.stringify(evidence),now,candidate.id).run();
 else await db.prepare("INSERT INTO batch_learning_records(project_id,batch_key,source_window_start,source_window_end,keep_json,improve_json,test_next_json,evidence_json,status,approved_by,approved_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,'PENDING_REVIEW',NULL,NULL,?,?)").bind(projectId,batchKey,sourceWindowStart,sourceWindowEnd,JSON.stringify(keep),JSON.stringify(improve),JSON.stringify(testNext),JSON.stringify(evidence),now,now).run();
 return{learningId:Number(candidate?.id||0)||Number((await db.prepare("SELECT id FROM batch_learning_records WHERE project_id=? AND batch_key=? AND status='PENDING_REVIEW' ORDER BY id DESC LIMIT 1").bind(projectId,batchKey).first<any>())?.id||0),keep,improve,testNext,evidence,status:"PENDING_REVIEW",saved:true,batchKey,updatedExisting:Boolean(candidate)}
}

export async function approveBatchLearning(db:any,projectId:string,learningId:number,approvedBy:string){
 const candidate=await db.prepare("SELECT id,batch_key AS batchKey,source_window_start AS sourceWindowStart,source_window_end AS sourceWindowEnd,status FROM batch_learning_records WHERE id=? AND project_id=?").bind(learningId,projectId).first<any>();
 if(!candidate)throw Object.assign(new Error("Batch Learning candidate not found."),{status:404});
 if(candidate.status!=="PENDING_REVIEW")throw Object.assign(new Error(`Only PENDING_REVIEW Learning can be approved. Current status: ${candidate.status}.`),{status:409});
 if(!candidate.sourceWindowStart||!candidate.sourceWindowEnd||Date.parse(candidate.sourceWindowEnd)<Date.parse(candidate.sourceWindowStart))throw Object.assign(new Error("Batch Learning evidence window is invalid."),{status:409});
 const now=stamp();await db.batch([
  db.prepare("UPDATE batch_learning_records SET status='SUPERSEDED',updated_at=? WHERE project_id=? AND batch_key=? AND status='READY' AND approved_at IS NOT NULL AND id!=?").bind(now,projectId,candidate.batchKey,learningId),
  db.prepare("UPDATE batch_learning_records SET status='READY',approved_by=?,approved_at=?,updated_at=? WHERE id=? AND project_id=? AND status='PENDING_REVIEW'").bind(approvedBy,now,now,learningId,projectId),
 ]);
 return{id:learningId,batchKey:candidate.batchKey,status:"READY",approvedBy,approvedAt:now}
}
