"use client";
import{FormEvent}from"react";

type InputProps={name:string;label:string;value?:string;area?:boolean;placeholder?:string;disabled?:boolean};
function Input({name,label,value,area=false,placeholder="",disabled=false}:InputProps){return <label className="field">{label}<em>Required before approval</em>{area?<textarea disabled={disabled} required name={name} defaultValue={value||""} placeholder={placeholder}/>:<input disabled={disabled} required name={name} defaultValue={value||""} placeholder={placeholder}/>}</label>}

export default function FilmSeriesScript({p,data,save}:{p:any;data:any;save:(value:any)=>void}){
 const count=Math.max(2,Math.min(12,Number(p.frequencyCount)||5)),films=Array.isArray(data.films)?data.films:[],submitted=p.scriptStatus==="Submitted",approved=p.scriptStatus==="Approved",reviews=Array.isArray(data.reviews)?data.reviews:[];
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),next=Array.from({length:count},(_,i)=>{const old=films[i]||{},locked=reviews[i]?.status==="approved";if(locked)return old;return{filmNumber:i+1,title:String(f.get(`filmTitle${i}`)||""),duration:String(f.get(`filmDuration${i}`)||p.projectDuration||""),objective:String(f.get(`filmObjective${i}`)||""),storyPremise:String(f.get(`filmPremise${i}`)||""),storyFlow:String(f.get(`filmFlow${i}`)||""),ending:String(f.get(`filmEnding${i}`)||""),meaning:String(f.get(`filmMeaning${i}`)||""),designReason:String(f.get(`filmReason${i}`)||"")}});save({seriesMode:true,filmCount:count,films:next})}
 return <section className={`panel form-card film-series-script ${submitted||approved?"series-readonly":""}`}><div className="form-card-head"><p className="eyebrow">04 · COMMERCIAL FILM SERIES</p><h3>{count} Films · One Shared Campaign Foundation</h3><p>{approved?"All approved film scripts are protected and ready for their individual Storyboards.":submitted?"Submitted to management. Open Approvals to review every film separately.":"The approved Client Brief and Foundation are inherited by every film. Each film keeps its own objective, story, duration and approval decision."}</p></div><div className="series-inheritance"><b>MASTER CONTEXT IS LOCKED IN</b><span>{p.client} · {p.projectDuration||"Individual"}s base duration · {count} film deliverables</span><small>Change the shared Brief or Foundation once; every film continues from the latest approved version. Film-specific fields below override only that film.</small></div><form onSubmit={submit}><div className="film-unit-list">{Array.from({length:count},(_,i)=>{const x=films[i]||{},review=reviews[i],locked=submitted||approved||review?.status==="approved";return <article className={`film-unit ${review?.status||""}`} key={i}><header><span>{String(i+1).padStart(2,"0")}</span><div><b>Commercial Film {i+1}</b><small>{review?.status==="approved"?"✓ Approved and locked":review?.status==="refine"?"✕ Revision requested":"Independent script and approval package"}</small></div></header><div className="form-grid"><Input disabled={locked} name={`filmTitle${i}`} label="Film title / concept" value={x.title}/><Input disabled={locked} name={`filmDuration${i}`} label="Duration / seconds" value={x.duration||p.projectDuration}/></div><Input disabled={locked} area name={`filmObjective${i}`} label="Film-specific objective" value={x.objective} placeholder="What unique job does this film perform inside the campaign?"/><Input disabled={locked} area name={`filmPremise${i}`} label="Story premise" value={x.storyPremise}/><Input disabled={locked} area name={`filmFlow${i}`} label="Complete story flow" value={x.storyFlow}/><div className="form-grid"><Input disabled={locked} area name={`filmEnding${i}`} label="Ending / brand close" value={x.ending}/><Input disabled={locked} area name={`filmMeaning${i}`} label="Storytelling meaning" value={x.meaning}/></div><Input disabled={locked} area name={`filmReason${i}`} label="Why this film works in the series" value={x.designReason}/>{review?.status==="refine"&&<div className="attached-review"><b>Management refinement comment</b><p>{review.note||"Please revise this film script."}</p></div>}</article>})}</div>{!submitted&&!approved&&<div className="form-footer"><span>Every film appears as a separate item during management review. Partial approval is allowed.</span><button type="submit">{p.scriptStatus==="Revision Requested"?"Resubmit revised films":"Submit all film scripts for approval"} →</button></div>}</form></section>}
