export function productionAssetPrompt(kind:string,data:any,item?:any){
  const theme=data.theme||"Approved Film / Commercial";
  const premise=data.storyPremise||"Follow the approved premise.";
  const flow=data.storyFlow||"Follow the approved story flow.";
  const ending=data.ending||"Follow the approved ending.";
  const meaning=data.meaning||data.designReason||"Preserve the approved storytelling intention.";
  const visualScript=(data.visualScript||[]).map((x:any,i:number)=>`SHOT ${i+1}: ${x.visualIntent||""} PERFORMANCE: ${x.performance||""} ART: ${x.artDirection||""} LIGHT/COLOR: ${x.lightColor||""} CONTINUITY: ${x.continuity||""}`).join(" ");
  const foundation=data.foundationContext||{};
  const variation=Number(item?.variant||0)+1;
  const variationDirections=[
    "Precision-led presentation: clean orthographic hierarchy, cool controlled studio light, restrained technical annotations and highly legible material callouts.",
    "Cinematic presentation: stronger hero image, deeper tonal contrast, motivated practical lighting and editorial supporting modules while retaining technical clarity.",
    "Premium campaign presentation: elegant negative space, refined typography hierarchy, tactile luxury materials and warmer controlled highlights.",
    "Documentary production presentation: naturalistic light, believable wear and imperfections, functional callouts and grounded real-world scale.",
  ];
  const variationBrief=variationDirections[(variation-1)%variationDirections.length];
  const continuity=`CONTINUITY LOCK: Use all supplied approved character, wardrobe, prop and environment references as the primary visual source. Preserve the same recognizable identities, facial structure, age, body proportions, hair, costume construction, exact palette, materials, prop geometry and location geography across every deliverable. Do not redesign an approved element between views or shots. PROJECT: ${theme}. PREMISE: ${premise} STORY FLOW: ${flow} ENDING: ${ending} MEANING: ${meaning}. APPROVED FOUNDATION: concept ${foundation.creativeConcept||"approved concept"}; objective ${foundation.creativeObjective||"approved objective"}; visual style ${foundation.visualStyle||"approved visual style"}; tone ${foundation.toneMood||"approved tone and pacing"}; format ${foundation.formatDirection||"approved format"}. APPROVED PHASE 07 VISUAL SCRIPT: ${visualScript||"Follow the approved Storyboard and Foundation direction."} ASSET NOTES: ${item?.note||"Follow the approved production plan."} CREATIVE VARIATION ${variation}: ${variationBrief} Never break story or visual continuity. Premium cinematic commercial quality, realistic materials, physically believable lighting, clean typography, no watermark, no invented logos or brand text, no malformed anatomy, duplicated details or fake labels.`;

  if(kind==="Character")return `Create a professional CHARACTER DESIGN TURNAROUND SHEET for ${item?.name||"the approved character"}.\n${continuity}\nPRESENTATION SYSTEM: one polished 16:9 production design sheet, visually comparable to a studio character reference package. Use a restrained cinematic layout with clear hierarchy and generous safe margins.\nREQUIRED VIEWS: full-body FRONT, 3/4, SIDE and BACK at identical scale and neutral pose; one large identity portrait; three story-useful expressions; hair, face, wardrobe, footwear, accessories and material close-ups; exact color palette; height and human scale reference.\nDESIGN DETAIL: define the role-specific silhouette, garment cut and construction, exact colors, fabric weave, patterns, seams, stitching, fasteners, wear, jewellery, bag, footwear and approved story accessories. Every view must depict the same person and same outfit without drift. Neutral studio background only. Do not create action scenes, environment panoramas or storyboard panels.`;

  if(kind==="Environment")return `Create a professional ENVIRONMENT DESIGN SHEET for “${item?.name||"Approved Environment"}”.\n${continuity}\nPRESENTATION SYSTEM: one polished 16:9 production design sheet with one dominant unobstructed hero location image and smaller technical reference modules. Keep a readable cinematic layout, clear labels and generous safe margins.\nREQUIRED MODULES: entrance/threshold; primary action zone; secondary/background zone; spatial flow and screen-direction plan; practical-light-source diagram; architecture and set-dressing callouts; material, surface and weathering close-ups; exact color palette; atmosphere states; human silhouette for scale.\nPRODUCTION LOGIC: establish fixed geography, doors, windows, reflective surfaces, usable camera positions, foreground/midground/background separation and story-relevant objects so later storyboard frames reproduce the same place consistently. No character turnaround and no storyboard sequence.`;

  if(kind==="Props")return `Create a professional PROP / PRODUCT DESIGN SHEET for “${item?.name||"Approved Story Props"}”.\n${continuity}\nPRESENTATION SYSTEM: one polished 16:9 technical design sheet on a neutral background with isolated objects and clean callouts.\nREQUIRED VIEWS: FRONT, 3/4, SIDE, BACK and TOP where useful; open/closed or active/inactive states; hand interaction points; scale reference; construction breakdown; exact dimensions when known; colors; material swatches; surface finish, wear and story-specific detail close-ups. Include only approved props and products. Preserve exact geometry between every view. Do not invent logos, labels or extra objects. No environment panorama and no storyboard.`;

  const shots=item?.shots||[];
  const shotPlan=shots.map((s:any,j:number)=>`PANEL ${j+1} / SHOT ${s.number}: ${s.duration||"timing TBC"} · ${s.framing||"system chooses the clearest cinematic framing"} · ${s.camera||"camera follows the approved intention"} · ${s.movement||"movement follows the approved action"} · ${s.lighting||"lighting follows the approved direction"}. STORY BEAT: ${s.description||"Follow the approved shot."} PERFORMANCE: ${s.characterMotion||"Natural performance matching the beat."}${s.dialogue?` DIALOGUE / VO: ${s.dialogue}`:""}`).join("\n");
  return `Create ONE professional STORYBOARD CONTACT SHEET for ${item?.name||"this sequence"}.\n${continuity}\nCONTACT-SHEET SYSTEM: this sheet covers only the supplied consecutive shots. The delivery frame is 16:9, therefore use an exact 3 × 3 grid with a maximum of nine numbered 16:9 panels. If the sequence exceeds nine shots, it belongs on the next separate sheet. Use clean gutters, consistent borders, short shot labels and a restrained production footer for project, sequence and continuity notes.\nCOMPOSITION RULE: compose every panel natively for 16:9. The system must choose the clearest cinematic shot scale and subject placement for the stated story beat while honoring any approved framing. Keep faces, complete gestures, important hands, props and essential architecture inside safe margins; never solve layout by cropping critical information. Preserve screen direction, eyelines, spatial geography, time of day, wardrobe, character identity, prop state, lighting direction and color continuity from one panel to the next. Show a coherent visual progression with a strong opening hook, readable development, climax/payoff and resolved ending exactly as supplied. Never merge, reorder or invent story beats.\nSHOT PLAN:\n${shotPlan}\nIf fewer than nine shots are supplied, leave unused cells clean and neutral. The result must read as one consistent film photographed in the same approved world—not nine unrelated images.`;
}
