import{TIKTOK_SCOPES,appConnection,callbackUrl,cookie,credentialSecret,decodeState,oauthErrorResult,origin,projectRedirect,recordOAuthError,runtime}from"../_lib";
import{saveIntegration}from"../../integrations/_lib";
import{socialAccess}from"../../social-connections/_lib";
import{AUTOPOST_ENABLED,autoPostNotFound}from"../../../autopost-mode";

export async function GET(req:Request){
 if(!AUTOPOST_ENABLED)return autoPostNotFound();
 const home=origin(req),clearCookie="ff_tiktok_oauth=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0",url=new URL(req.url),code=String(url.searchParams.get("code")||""),state=String(url.searchParams.get("state")||""),providerError=String(url.searchParams.get("error")||""),providerDescription=String(url.searchParams.get("error_description")||""),saved=decodeState(cookie(req,"ff_tiktok_oauth")),fallback=(result:string)=>new Response(null,{status:302,headers:{location:`${home}/?tiktok=${encodeURIComponent(result)}`,"set-cookie":clearCookie}}),redirect=(projectId:string,result:string)=>new Response(null,{status:302,headers:{location:projectRedirect(req,projectId,result),"set-cookie":clearCookie}});
 if(!state||!saved||saved.state!==state||!saved.projectId){try{const invalidEnv=await runtime();await recordOAuthError(invalidEnv.DB,"",String(req.headers.get("oai-authenticated-user-email")||"system"),"INVALID_STATE","TikTok OAuth state or Project binding was missing or invalid.")}catch{}return fallback("invalid-state")}
 const env=await runtime(),projectId=String(saved.projectId),actorEmail=String(req.headers.get("oai-authenticated-user-email")||"system");
 try{await socialAccess(req,env.DB,projectId,true)}catch(error:any){await recordOAuthError(env.DB,projectId,actorEmail,"MANAGEMENT_REQUIRED",String(error?.message||"Management access required"));return redirect(projectId,"management-required")}
 if(providerError){await recordOAuthError(env.DB,projectId,actorEmail,providerError,providerDescription||"TikTok authorization was not completed.");return redirect(projectId,`oauth-error-${providerError}`)}
 if(!code){await recordOAuthError(env.DB,projectId,actorEmail,"CODE_MISSING","TikTok did not return an authorization code.");return redirect(projectId,"code-missing")}
 let app:any;try{app=await appConnection(env.DB,env)}catch(error:any){await recordOAuthError(env.DB,projectId,actorEmail,"CONFIGURATION_REQUIRED",String(error?.message||"TikTok Login Kit is not configured."));return redirect(projectId,"configuration-required")}
 try{
  const tokenResponse=await fetch("https://open.tiktokapis.com/v2/oauth/token/",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded","cache-control":"no-cache"},body:new URLSearchParams({client_key:String(app.config.clientKey),client_secret:String(app.secret),code,grant_type:"authorization_code",redirect_uri:callbackUrl(req)})}),token:any=await tokenResponse.json().catch(()=>({}));
  if(!tokenResponse.ok||!token.access_token||!token.refresh_token||!token.open_id){const failure=oauthErrorResult(token,tokenResponse.status);await recordOAuthError(env.DB,projectId,actorEmail,failure.code,failure.message,{providerLogId:failure.logId,httpStatus:tokenResponse.status});return redirect(projectId,`token-failed-${failure.code}`)}
  const grantedScopes=String(token.scope||url.searchParams.get("scopes")||"").split(",").map((scope:string)=>scope.trim()).filter(Boolean),profileUrl=new URL("https://open.tiktokapis.com/v2/user/info/");profileUrl.searchParams.set("fields","open_id,union_id,avatar_url,display_name,username,profile_deep_link");
  const profileResponse=await fetch(profileUrl,{headers:{authorization:`Bearer ${String(token.access_token)}`}}),profileResult:any=await profileResponse.json().catch(()=>({})),user=profileResult?.data?.user||{};
  if(!profileResponse.ok||!user.open_id){const failure=oauthErrorResult(profileResult,profileResponse.status);await recordOAuthError(env.DB,projectId,actorEmail,failure.code,failure.message,{providerLogId:failure.logId,httpStatus:profileResponse.status,stage:"profile"});return redirect(projectId,`profile-failed-${failure.code}`)}
  const now=new Date().toISOString(),accessTokenExpiresAt=new Date(Date.now()+Math.max(1,Number(token.expires_in||86400))*1000).toISOString(),refreshTokenExpiresAt=new Date(Date.now()+Math.max(1,Number(token.refresh_expires_in||31536000))*1000).toISOString(),accountId=String(user.open_id||token.open_id),username=String(user.username||""),displayName=String(user.display_name||username||"TikTok Profile"),profileLink=String(user.profile_deep_link||username&&`https://www.tiktok.com/@${username}`||""),providerKey=`tiktok-account:${projectId}:${accountId}`,requestedConnectionId=String(saved.connectionId||""),existing=requestedConnectionId?await env.DB.prepare("SELECT connection_id AS connectionId,external_account_id AS accountId,is_default AS isDefault FROM project_social_connections WHERE project_id=? AND platform='TikTok' AND connection_id=?").bind(projectId,requestedConnectionId).first<any>():await env.DB.prepare("SELECT connection_id AS connectionId,external_account_id AS accountId,is_default AS isDefault FROM project_social_connections WHERE project_id=? AND platform='TikTok' AND external_account_id=?").bind(projectId,accountId).first<any>(),defaultRow=await env.DB.prepare("SELECT connection_id FROM project_social_connections WHERE project_id=? AND platform='TikTok' AND is_default=1 LIMIT 1").bind(projectId).first<any>(),connectionId=existing?.connectionId||`social_${crypto.randomUUID()}`,isDefault=existing?Number(existing.isDefault||0):defaultRow?0:1,capabilities={loginKit:true,identityRead:true,autoPublish:false,publishingStatus:"NOT_IMPLEMENTED",requestedScopes:TIKTOK_SCOPES};
  await saveIntegration(env.DB,env,providerKey,credentialSecret(String(token.access_token),String(token.refresh_token)),{accountId,openId:accountId,unionId:String(user.union_id||""),username,displayName,avatarUrl:String(user.avatar_url||""),profileUrl:profileLink,accessTokenExpiresAt,refreshTokenExpiresAt,expiresAt:accessTokenExpiresAt,scopes:grantedScopes,tokenType:String(token.token_type||"Bearer")},"Connected");
  if(existing)await env.DB.prepare("UPDATE project_social_connections SET provider_key=?,external_account_id=?,profile_url=?,handle=?,account_type='Creator',status='Connected',permissions_json=?,capabilities_json=?,token_expires_at=?,connected_by=?,connected_at=?,last_checked_at=?,disconnected_at=NULL,updated_at=? WHERE connection_id=? AND project_id=?").bind(providerKey,accountId,profileLink,username?`@${username}`:displayName,JSON.stringify(grantedScopes),JSON.stringify(capabilities),accessTokenExpiresAt,actorEmail,now,now,now,connectionId,projectId).run();else await env.DB.prepare("INSERT INTO project_social_connections(connection_id,project_id,platform,provider_key,external_account_id,profile_url,handle,account_type,status,permissions_json,capabilities_json,token_expires_at,connected_by,connected_at,last_checked_at,disconnected_at,is_default,updated_at) VALUES(?,?,'TikTok',?,?,?,?,?,'Connected',?,?,?,?,?,?,NULL,?,?) ON CONFLICT(project_id,platform,external_account_id) DO UPDATE SET provider_key=excluded.provider_key,profile_url=excluded.profile_url,handle=excluded.handle,account_type=excluded.account_type,status='Connected',permissions_json=excluded.permissions_json,capabilities_json=excluded.capabilities_json,token_expires_at=excluded.token_expires_at,connected_by=excluded.connected_by,connected_at=excluded.connected_at,last_checked_at=excluded.last_checked_at,disconnected_at=NULL,updated_at=excluded.updated_at").bind(connectionId,projectId,providerKey,accountId,profileLink,username?`@${username}`:displayName,"Creator",JSON.stringify(grantedScopes),JSON.stringify(capabilities),accessTokenExpiresAt,actorEmail,now,now,isDefault,now).run();
  await env.DB.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(projectId,existing?"tiktok_account_reconnected":"tiktok_account_connected",actorEmail,JSON.stringify({previousAccountId:existing?.accountId||null,accountId,username:username||null,displayName,scopes:grantedScopes,accessTokenExpiresAt,refreshTokenExpiresAt,publishingEnabled:false}),now).run();
  return redirect(projectId,"connected");
 }catch(error:any){await recordOAuthError(env.DB,projectId,actorEmail,String(error?.code||"CALLBACK_FAILED"),String(error?.message||"TikTok OAuth callback failed."));return redirect(projectId,"callback-failed")}
}
