import{loadIntegration}from"../integrations/_lib";

const now=()=>new Date().toISOString();
const safe=(value:any)=>String(value?.message||value||"Generation failed.").slice(0,1200);

export const FAIL_FAST_GENERATION_JOB_TYPES=new Set(["AGENT_TASK","LLM_TASK","IMAGE_GENERATION","IMAGE_UPSCALE","VIDEO_GENERATION"]);

async function telegramRecipients(db:any,projectId:string,configuredChatId:string){
 const recipients=new Map<string,{email:string;name:string;tier:number;role:string}>();
 if(configuredChatId)recipients.set(configuredChatId,{email:"tier0:configured",name:"Tier 0 Management",tier:0,role:"Tier 0"});
 const rows=await db.prepare(`SELECT DISTINCT m.email,m.name,m.tier,COALESCE(NULLIF(m.telegram_chat_id,''),ti.telegram_user_id) AS chatId,CASE WHEN m.tier=0 THEN 'Tier 0' WHEN t.lead_email=m.email THEN 'Project Lead' ELSE 'Tier 1 Project Manager' END AS recipientRole FROM members m LEFT JOIN member_telegram_identities ti ON ti.member_email=m.email LEFT JOIN projects p ON p.id=? LEFT JOIN teams t ON t.id=p.team_id WHERE m.member_kind='human' AND m.status='Active' AND (m.tier=0 OR (m.tier=1 AND (EXISTS (SELECT 1 FROM project_members pm WHERE pm.project_id=? AND pm.member_email=m.email) OR t.lead_email=m.email)))`).bind(projectId,projectId).all();
 for(const row of rows.results as any[]){const chatId=String(row.chatId||"").trim();if(chatId)recipients.set(chatId,{email:String(row.email),name:String(row.name||row.email),tier:Number(row.tier),role:String(row.recipientRole)})}
 return recipients;
}

export async function notifyGenerationIncident(db:any,env:any,jobId:string,error:any){
 const job=await db.prepare("SELECT id,parent_job_id AS parentJobId,project_id AS projectId,content_id AS contentId,task_id AS taskId,job_type AS jobType,provider,model,status FROM orchestrator_jobs WHERE id=?").bind(jobId).first<any>();
 if(!job||!FAIL_FAST_GENERATION_JOB_TYPES.has(String(job.jobType)))return{notified:false,reason:"Not a generation job."};
 const existing=await db.prepare("SELECT 1 AS sent FROM orchestrator_job_events WHERE job_id=? AND event_type='GENERATION_INCIDENT_NOTIFIED' LIMIT 1").bind(job.id).first();if(existing)return{notified:false,reason:"Already notified."};
 const stamp=now(),message=safe(error),project=await db.prepare("SELECT client FROM projects WHERE id=?").bind(job.projectId).first<any>(),cancelled:any[]=[];
 if(job.parentJobId){const queued=await db.prepare("SELECT id FROM orchestrator_jobs WHERE parent_job_id=? AND id!=? AND job_type IN ('LLM_TASK','IMAGE_GENERATION','IMAGE_UPSCALE','VIDEO_GENERATION') AND status IN ('QUEUED','SCHEDULED','RETRY_PENDING')").bind(job.parentJobId,job.id).all();for(const row of queued.results as any[])cancelled.push(String(row.id));if(cancelled.length){const marks=cancelled.map(()=>"?").join(",");await db.prepare(`UPDATE orchestrator_jobs SET status='CANCELLED',last_error='Stopped after another generation job failed; no automatic retry.',completed_at=?,updated_at=? WHERE id IN (${marks})`).bind(stamp,stamp,...cancelled).run()}}
 const telegram=await loadIntegration(db,env,"telegram"),configuredChatId=String(telegram?.config?.chatId||"").trim(),recipients=await telegramRecipients(db,job.projectId,configuredChatId),deliveries:any[]=[];
 const text=`FrameFlow generation stopped · Needs Attention\n\nProject: ${project?.client||job.projectId} (${job.projectId})\nTask: ${job.jobType}${job.contentId?` · ${job.contentId}`:""}\nProvider: ${job.provider||"Not assigned"}${job.model?` · ${job.model}`:""}\nReason: ${message}\n\nAutomatic retry: OFF${cancelled.length?`\nQueued sibling tasks stopped: ${cancelled.length}`:""}\nTier 0–1 / Project Lead must review before a manual retry.`;
 if(telegram?.secret){for(const[chatId,recipient]of recipients){try{const response=await fetch(`https://api.telegram.org/bot${telegram.secret}/sendMessage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:chatId,text})});const result:any=await response.json().catch(()=>({}));deliveries.push({...recipient,chatId,status:response.ok&&result?.ok!==false?"SENT":"FAILED",error:response.ok&&result?.ok!==false?null:String(result?.description||`HTTP ${response.status}`)})}catch(sendError:any){deliveries.push({...recipient,chatId,status:"FAILED",error:safe(sendError)})}}}
 const recipientRows=await db.prepare(`SELECT DISTINCT m.email,m.name,m.tier,CASE WHEN m.tier=0 THEN 'Tier 0' WHEN t.lead_email=m.email THEN 'Project Lead' ELSE 'Tier 1 Project Manager' END AS recipientRole FROM members m LEFT JOIN projects p ON p.id=? LEFT JOIN teams t ON t.id=p.team_id WHERE m.member_kind='human' AND m.status='Active' AND (m.tier=0 OR (m.tier=1 AND (EXISTS (SELECT 1 FROM project_members pm WHERE pm.project_id=? AND pm.member_email=m.email) OR t.lead_email=m.email)))`).bind(job.projectId,job.projectId).all();
 const eventData={jobId:job.id,parentJobId:job.parentJobId,contentId:job.contentId,taskId:job.taskId,jobType:job.jobType,provider:job.provider,model:job.model,error:message,automaticRetry:false,cancelledQueuedSiblingJobIds:cancelled,recipients:recipientRows.results,telegramDeliveries:deliveries};
 await db.batch([db.prepare("UPDATE agent_project_controls SET active=0,status='Needs Attention · Generation stopped',last_error=?,updated_at=? WHERE project_id=?").bind(message,stamp,job.projectId),db.prepare("UPDATE projects SET assignment_status='Needs Attention' WHERE id=?").bind(job.projectId),db.prepare("INSERT INTO orchestrator_job_events(job_id,event_type,actor,event_data,created_at) VALUES(?,'GENERATION_INCIDENT_NOTIFIED','system:orchestrator',?,?)").bind(job.id,JSON.stringify(eventData),stamp),db.prepare("INSERT INTO production_events(project_id,event_type,actor_email,actor_name,actor_tier,event_data,created_at) VALUES(?,'generation_incident_alert','system:orchestrator','FrameFlow OS',0,?,?)").bind(job.projectId,JSON.stringify(eventData),stamp),db.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,'generation_incident_alert','system:orchestrator',?,?)").bind(job.projectId,JSON.stringify(eventData),stamp)]);
 return{notified:true,recipientCount:Number((recipientRows.results as any[]).length),telegramDeliveryCount:deliveries.filter(row=>row.status==="SENT").length,cancelledQueuedSiblingJobs:cancelled.length};
}
