import{ensurePublishingRecord,executePublishJob,sendPublishedTelegramNotification}from"../publishing/service";
import{ensureConnectionIds}from"../social-connections/_lib";
import{ACTIVE_JOB_STATUSES,JOB_TYPES,JobType,ORCHESTRATOR_POLICY,PROVIDER_ROUTES}from"./policy";
import{approveVisualAnchor,normalizeVisualPromptArchitecture}from"../../visual-prompt-architecture";
import{dispatchRunningHubUpscale,RUNNINGHUB_UPSCALE_WORKFLOW_ID}from"../runninghub/upscale";
import{dispatchRunningHubH3Video}from"../runninghub/video";
import{dispatchRunningHubQwenImage}from"../runninghub/image";
import{productionAssetCountIssues}from"../../social-production-plan";
import{FAIL_FAST_GENERATION_JOB_TYPES,notifyGenerationIncident}from"./generation-incidents";
import{socialBatchAssetKey,socialBatchAssetPrefixFromKey,socialBatchContentId}from"../../social-batch-assets";
import{canonicalSocialPlatform,configuredSchedulePlatforms,isAutomaticPublishingPlatform,resolvePlannedBatchItem}from"../../social-scheduling-platforms";
import{AUTOPOST_ENABLED}from"../../autopost-mode";

const parse=(value:any,fallback:any={})=>{try{return JSON.parse(value||"")}catch{return fallback}};
const now=()=>new Date().toISOString();
const activeMarks=()=>ACTIVE_JOB_STATUSES.map(()=>"?").join(",");
const contentOrder=(value:any)=>Number(String(value||"").match(/(\d+)/)?.[1]||9999);

export type CreateJobInput={
 projectId:string;contentId?:string|null;taskId:string;jobType:JobType;actor:string;
 provider?:string|null;model?:string|null;inputAssets?:any[];inputPayload?:Record<string,any>;
 scheduledFor?:string|null;idempotencyKey?:string;parentJobId?:string|null;maxAttempts?:number;
};

export async function appendJobEvent(db:any,jobId:string,eventType:string,actor:string,eventData:any={}){
 await db.prepare("INSERT INTO orchestrator_job_events(job_id,event_type,actor,event_data,created_at) VALUES(?,?,?,?,?)").bind(jobId,eventType,actor,JSON.stringify(eventData||{}),now()).run();
}

export async function createSystemJob(db:any,input:CreateJobInput):Promise<any>{
 if(!AUTOPOST_ENABLED&&input.jobType==="PUBLISH_JOB")throw Object.assign(new Error("Not found"),{status:404});
 if(!JOB_TYPES.includes(input.jobType))throw Object.assign(new Error("Unsupported System Orchestrator Job type."),{status:400});
 if(input.jobType==="PUBLISH_JOB"&&input.maxAttempts==null)input.maxAttempts=5;
 if(FAIL_FAST_GENERATION_JOB_TYPES.has(input.jobType)&&input.maxAttempts==null)input.maxAttempts=1;
 const project=await db.prepare("SELECT id FROM projects WHERE id=?").bind(input.projectId).first();if(!project)throw Object.assign(new Error("Project not found."),{status:404});
 const idempotencyKey=input.idempotencyKey||[input.jobType,input.projectId,input.contentId||"project",input.taskId,crypto.randomUUID()].join(":"),existing=await db.prepare("SELECT * FROM orchestrator_jobs WHERE idempotency_key=?").bind(idempotencyKey).first<any>();if(existing)return normalizeJob(existing);
 const id="job_"+crypto.randomUUID(),stamp=now(),status=input.scheduledFor&&Date.parse(input.scheduledFor)>Date.now()?"SCHEDULED":"QUEUED",route=PROVIDER_ROUTES[input.jobType];
 await db.prepare("INSERT INTO orchestrator_jobs(id,idempotency_key,parent_job_id,project_id,content_id,task_id,job_type,actor,provider,model,input_assets,output_assets,input_payload,output_payload,status,attempt_count,max_attempts,scheduled_for,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,idempotencyKey,input.parentJobId||null,input.projectId,input.contentId||null,input.taskId,input.jobType,input.actor,input.provider||route.primary,input.model||null,JSON.stringify(input.inputAssets||[]),"[]",JSON.stringify(input.inputPayload||{}),"{}",status,0,Math.max(1,Math.min(5,Number(input.maxAttempts||3))),input.scheduledFor||null,stamp,stamp).run();
 await appendJobEvent(db,id,"JOB_CREATED",input.actor,{status,route,policyVersion:ORCHESTRATOR_POLICY.version});
 return getSystemJob(db,id);
}

export async function getSystemJob(db:any,jobId:string){const row=await db.prepare("SELECT * FROM orchestrator_jobs WHERE id=?").bind(jobId).first<any>(),job=row?normalizeJob(row):null;return!AUTOPOST_ENABLED&&job?.jobType==="PUBLISH_JOB"?null:job}
export async function listSystemJobs(db:any,filters:{projectId?:string;status?:string;jobType?:string;excludePublishMode?:string;limit?:number}={}){const conditions:string[]=[],values:any[]=[];if(filters.projectId){conditions.push("project_id=?");values.push(filters.projectId)}if(filters.status){conditions.push("status=?");values.push(filters.status)}if(filters.jobType){conditions.push("job_type=?");values.push(filters.jobType)}if(filters.excludePublishMode){conditions.push("COALESCE(json_extract(input_payload,'$.publishMode'),'live')!=?");values.push(filters.excludePublishMode)}const sql="SELECT * FROM orchestrator_jobs"+(conditions.length?" WHERE "+conditions.join(" AND "):"")+" ORDER BY created_at DESC LIMIT ?",rows=await db.prepare(sql).bind(...values,Math.max(1,Math.min(200,Number(filters.limit||50)))).all();return(rows.results as any[]).map(normalizeJob)}

function normalizeJob(row:any){return{id:row.id,idempotencyKey:row.idempotency_key,parentJobId:row.parent_job_id,projectId:row.project_id,contentId:row.content_id,taskId:row.task_id,jobType:row.job_type,actor:row.actor,provider:row.provider,model:row.model,inputAssets:parse(row.input_assets,[]),outputAssets:parse(row.output_assets,[]),inputPayload:parse(row.input_payload,{}),outputPayload:parse(row.output_payload,{}),status:row.status,attemptCount:Number(row.attempt_count||0),maxAttempts:Number(row.max_attempts||0),scheduledFor:row.scheduled_for,startedAt:row.started_at,completedAt:row.completed_at,lastError:row.last_error,createdAt:row.created_at,updatedAt:row.updated_at}}

export async function updateSystemJob(db:any,jobId:string,status:string,actor:string,update:{provider?:string|null;model?:string|null;outputAssets?:any[];outputPayload?:any;error?:string|null}={}){const stamp=now(),terminal=["SUCCEEDED","FAILED","CANCELLED"].includes(status),started=status==="RUNNING"?stamp:null;await db.prepare("UPDATE orchestrator_jobs SET status=?,provider=COALESCE(?,provider),model=COALESCE(?,model),output_assets=COALESCE(?,output_assets),output_payload=COALESCE(?,output_payload),last_error=?,started_at=COALESCE(started_at,?),completed_at=CASE WHEN ? THEN ? ELSE completed_at END,attempt_count=CASE WHEN ?='RUNNING' THEN attempt_count+1 ELSE attempt_count END,updated_at=? WHERE id=?").bind(status,update.provider||null,update.model||null,update.outputAssets?JSON.stringify(update.outputAssets):null,update.outputPayload?JSON.stringify(update.outputPayload):null,update.error||null,started,terminal?1:0,terminal?stamp:null,status,stamp,jobId).run();await appendJobEvent(db,jobId,"STATUS_"+status,actor,{...update,error:update.error||null});return getSystemJob(db,jobId)}

export async function failLatestRunningJob(db:any,projectId:string,jobType:JobType,actor:string,error:string){const row=await db.prepare("SELECT id FROM orchestrator_jobs WHERE project_id=? AND job_type=? AND status='RUNNING' ORDER BY created_at DESC LIMIT 1").bind(projectId,jobType).first<any>();if(row)await updateSystemJob(db,row.id,"FAILED",actor,{error})}

export async function recordJobCost(db:any,input:{jobId:string;provider:string;model?:string|null;amountMicros?:number;inputUnits?:number;outputUnits?:number;pricingStatus?:string;metadata?:any}){await db.prepare("INSERT INTO orchestrator_costs(job_id,provider,model,currency,amount_micros,input_units,output_units,pricing_status,metadata,created_at) VALUES(?,?,?,'USD',?,?,?,?,?,?)").bind(input.jobId,input.provider,input.model||null,Math.max(0,Number(input.amountMicros||0)),Math.max(0,Number(input.inputUnits||0)),Math.max(0,Number(input.outputUnits||0)),input.pricingStatus||"UNPRICED",JSON.stringify(input.metadata||{}),now()).run()}

async function sha(value:string){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(digest)).map(x=>x.toString(16).padStart(2,"0")).join("")}
export async function issueJobToken(db:any,jobId:string,scope="CALLBACK_WRITE",ttlMinutes=120){const job=await getSystemJob(db,jobId);if(!job)throw Object.assign(new Error("Job not found."),{status:404});const raw="ffj_"+crypto.randomUUID().replaceAll("-","")+crypto.randomUUID().replaceAll("-",""),id="token_"+crypto.randomUUID(),stamp=now(),expiresAt=new Date(Date.now()+Math.max(15,Math.min(1440,ttlMinutes))*60000).toISOString();await db.prepare("UPDATE orchestrator_job_tokens SET status='Revoked',revoked_at=? WHERE job_id=? AND scope=? AND status='Active'").bind(stamp,jobId,scope).run();await db.prepare("INSERT INTO orchestrator_job_tokens(id,job_id,token_hash,scope,status,expires_at,created_at) VALUES(?,?,?,?,'Active',?,?)").bind(id,jobId,await sha(raw),scope,expiresAt,stamp).run();await appendJobEvent(db,jobId,"TOKEN_ISSUED","system:orchestrator",{scope,expiresAt});return{token:raw,expiresAt,scope}}
export async function authorizeJobToken(db:any,req:Request,scope="CALLBACK_WRITE"){const auth=req.headers.get("authorization")||"",raw=auth.toLowerCase().startsWith("bearer ")?auth.slice(7).trim():req.headers.get("x-frameflow-job-token")||"";if(!raw)throw Object.assign(new Error("Job callback token is required."),{status:401});const row=await db.prepare("SELECT t.id,t.job_id AS jobId,t.status,t.expires_at AS expiresAt FROM orchestrator_job_tokens t WHERE t.token_hash=? AND t.scope=?").bind(await sha(raw),scope).first<any>();if(!row||row.status!=="Active"||Date.parse(row.expiresAt)<=Date.now())throw Object.assign(new Error("Job callback token is invalid or expired."),{status:403});return row}

export async function cancelProjectJobs(db:any,projectId:string,actor:string,reason:string,contentId?:string|null){const marks=activeMarks(),values:any[]=[now(),reason,projectId,...ACTIVE_JOB_STATUSES],contentClause=contentId?" AND content_id=?":"";if(contentId)values.push(contentId);const rows=await db.prepare(`SELECT id FROM orchestrator_jobs WHERE project_id=? AND status IN (${marks})${contentClause}`).bind(projectId,...ACTIVE_JOB_STATUSES,...(contentId?[contentId]:[])).all();await db.prepare(`UPDATE orchestrator_jobs SET status='CANCELLED',last_error=?,completed_at=?,updated_at=? WHERE project_id=? AND status IN (${marks})${contentClause}`).bind(reason,values[0],values[0],projectId,...ACTIVE_JOB_STATUSES,...(contentId?[contentId]:[])).run();for(const row of rows.results as any[]){await db.prepare("UPDATE orchestrator_job_tokens SET status='Revoked',revoked_at=? WHERE job_id=? AND status='Active'").bind(values[0],row.id).run();await appendJobEvent(db,row.id,"JOB_CANCELLED",actor,{reason})}return Number(rows.results.length)}

function selectedPlatforms(item:any):string[]{const values:any[]=Array.isArray(item.platforms)?item.platforms:Array.isArray(item.plannedPlatforms)?item.plannedPlatforms:Array.isArray(item.planned_platforms)?item.planned_platforms:[];return[...new Set<string>(values.map(String).map((x:string)=>x.trim()).filter(Boolean))]}
function platformSchedule(item:any,platform:string){const schedules=Array.isArray(item.publishingSchedule)?item.publishingSchedule:Array.isArray(item.publishing_schedule)?item.publishing_schedule:[],match=schedules.find((entry:any)=>String(entry.platform||"").toLowerCase()===platform.toLowerCase())||{};return{scheduledFor:String(match.scheduledAt||match.scheduled_at||item.scheduledFor||item.scheduled_for||item.publishDate||item.publish_date||"")||null,socialConnectionId:String(match.socialConnectionId||match.social_connection_id||""),profileHandle:String(match.profileHandle||match.profile_handle||""),platformOrder:Number(match.order||1)}}
async function lockApprovedContentAnchors(db:any,projectId:string){
 const phase=await db.prepare("SELECT id,data FROM phase_records WHERE project_id=? AND phase_key='content-production' AND status='Approved' ORDER BY id DESC LIMIT 1").bind(projectId).first<any>();if(!phase)return;
 const data=parse(phase.data,{}),recordedBatchId=Number(data._productionBatchId||0),batch=recordedBatchId?{id:recordedBatchId}:await db.prepare("SELECT id FROM production_batches WHERE project_id=? ORDER BY CASE WHEN status='Planning' THEN 0 WHEN status='Active' THEN 1 ELSE 2 END,batch_number DESC LIMIT 1").bind(projectId).first<any>(),batchId=Number(batch?.id)||null,approvedAt=now();let changed=false;
 for(const item of Array.isArray(data.production_items)?data.production_items:[]){
  const contentId=String(item.contentId||item.content_id||""),asset=(Array.isArray(item.assets)?item.assets:[]).find((row:any)=>Number(row.assetNumber||row.asset_number)===1);if(!contentId||!asset)continue;
  const architecture=normalizeVisualPromptArchitecture(asset.visualPrompt,{source:item,contentId,assetNumber:1,assetRole:String(asset.assetRole||"Content Anchor"),subjectPresence:asset.subjectPresence||asset.subject_presence,wardrobe:asset.wardrobe,referenceTypes:asset.referenceTypes,approvedAnchor:false}),image=await db.prepare("SELECT id,item_key AS itemKey,storage_key AS storageKey,file_name AS fileName,mime_type AS mimeType,version,created_at AS createdAt FROM visual_asset_revisions WHERE project_id=? AND phase='content-production' AND item_key=? AND is_current=1 ORDER BY version DESC LIMIT 1").bind(projectId,socialBatchAssetKey(batchId,`${contentId}-asset-1`)).first<any>();if(!image)continue;
  const approvedId=Number(architecture.approvedAnchorImage?.id)||0;if(architecture.structuredAnchor.status==="APPROVED"&&approvedId===Number(image.id))continue;
  const approved=approveVisualAnchor(architecture,image,approvedAt);asset.visualPrompt=approved;asset.imageGenerationPrompt=approved.compiledFinalPrompt;changed=true;
 }
 if(!changed)return;const serialized=JSON.stringify(data);await db.batch([db.prepare("UPDATE phase_records SET data=?,updated_at=? WHERE id=?").bind(serialized,approvedAt,phase.id),db.prepare("UPDATE approved_phase_snapshots SET approved_content=? WHERE id=(SELECT id FROM approved_phase_snapshots WHERE project_id=? AND phase_key='content-production' ORDER BY version DESC LIMIT 1)").bind(serialized,projectId)])
}

export async function queueApprovedImageUpscales(db:any,_env:any,projectId:string,actor:string,itemKeys?:string[],_origin=""){
 const values:any[]=[projectId],filter=itemKeys?.length?` AND item_key IN (${itemKeys.map(()=>"?").join(",")})`:"";if(itemKeys?.length)values.push(...itemKeys);
 const rows=await db.prepare(`SELECT id,project_id AS projectId,phase,item_key AS itemKey,storage_key AS storageKey,file_name AS fileName,mime_type AS mimeType,size_bytes AS sizeBytes,version FROM visual_asset_revisions WHERE project_id=? AND phase='content-production' AND is_current=1 AND mime_type LIKE 'image/%'${filter} ORDER BY item_key`).bind(...values).all(),created:any[]=[];
 for(const asset of rows.results as any[]){const existing=await db.prepare("SELECT job_id AS jobId,status FROM asset_upscale_jobs WHERE source_asset_id=? OR derived_asset_id=? LIMIT 1").bind(asset.id,asset.id).first<any>();if(existing)continue;const contentId=socialBatchContentId(asset.itemKey),job=await createSystemJob(db,{projectId,contentId,taskId:`upscale:${asset.id}`,jobType:"IMAGE_UPSCALE",actor,provider:"runninghub",inputAssets:[asset],inputPayload:{sourceAssetId:asset.id,phase:asset.phase,itemKey:asset.itemKey,workflowId:RUNNINGHUB_UPSCALE_WORKFLOW_ID,assetPurpose:"UPSCALED_MASTER"},idempotencyKey:`upscale:${projectId}:${asset.id}:${RUNNINGHUB_UPSCALE_WORKFLOW_ID}`,maxAttempts:1}),stamp=now();await db.prepare("INSERT OR IGNORE INTO asset_upscale_jobs(id,job_id,project_id,source_asset_id,content_id,phase,item_key,runninghub_workflow_id,status,asset_purpose,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,'UPSCALE_PENDING','UPSCALED_MASTER',?,?)").bind("upscale_"+crypto.randomUUID(),job.id,projectId,asset.id,contentId,asset.phase,asset.itemKey,RUNNINGHUB_UPSCALE_WORKFLOW_ID,stamp,stamp).run();created.push(job)}return created;
}

export async function queueApprovedSocialPublishJobs(db:any,projectId:string,approvedPhaseKey:string,actor:string){
 if(!AUTOPOST_ENABLED)return[];
 if(!["content-production","reel-video-production"].includes(approvedPhaseKey))return[];
 if(approvedPhaseKey==="content-production")await lockApprovedContentAnchors(db,projectId);
 const project=await db.prepare("SELECT project_type_code AS projectType FROM projects WHERE id=?").bind(projectId).first<any>();if(!["Internal Social Account","Client Social Account"].includes(project?.projectType))return[];
 const [productionRow,batchRow,reelRow]=await Promise.all([db.prepare("SELECT approved_content AS content,version FROM approved_phase_snapshots WHERE project_id=? AND phase_key='content-production' ORDER BY version DESC LIMIT 1").bind(projectId).first<any>(),db.prepare("SELECT approved_content AS content FROM approved_phase_snapshots WHERE project_id=? AND phase_key='batch-ideas' ORDER BY version DESC LIMIT 1").bind(projectId).first<any>(),db.prepare("SELECT approved_content AS content,version FROM approved_phase_snapshots WHERE project_id=? AND phase_key='reel-video-production' ORDER BY version DESC LIMIT 1").bind(projectId).first<any>()]);
 await ensureConnectionIds(db,projectId);const production=parse(productionRow?.content,{}),batch=parse(batchRow?.content,{}),reel=parse(reelRow?.content,{}),recordedBatchId=Number(production._productionBatchId||0),activeBatch=recordedBatchId?await db.prepare("SELECT id FROM production_batches WHERE id=? AND project_id=?").bind(recordedBatchId,projectId).first<any>():await db.prepare("SELECT id FROM production_batches WHERE project_id=? ORDER BY CASE WHEN status='Planning' THEN 0 WHEN status='Active' THEN 1 ELSE 2 END,batch_number DESC LIMIT 1").bind(projectId).first<any>();if(productionAssetCountIssues(batch,production).length)return[];const productionItems=Array.isArray(production.production_items)?production.production_items:[],batchItems=Array.isArray(batch.content_items)?batch.content_items:[],reelItems=Array.isArray(reel.reel_video_items)?reel.reel_video_items:[],created:any[]=[];
 for(const [index,item] of productionItems.entries()){
  const contentId=String(item.contentId||item.content_id||"");if(!contentId)continue;
  const isReel=String(item.contentType||item.content_type).toLowerCase()==="reel";
  if((approvedPhaseKey==="content-production"&&isReel)||(approvedPhaseKey==="reel-video-production"&&!isReel))continue;
  if(isReel&&!reelItems.some((x:any)=>String(x.contentId||x.content_id)===contentId))continue;
  const source=resolvePlannedBatchItem(batchItems,contentId,index),publishingOrder=Number(source.publishingOrder||source.publishing_order||contentOrder(source.id||contentId)),allowed=configuredSchedulePlatforms([]),platforms=[...new Set(selectedPlatforms(source).map(canonicalSocialPlatform).filter(platform=>allowed.includes(platform)))],assetPhase=isReel?"reel-video-production":"content-production",assetKeyPrefix=socialBatchAssetKey(activeBatch?.id||null,contentId),assets=await db.prepare("SELECT v.id,v.storage_key AS storageKey,v.file_name AS fileName,v.mime_type AS mimeType,v.version,u.status AS upscaleStatus,u.asset_purpose AS assetPurpose FROM visual_asset_revisions v LEFT JOIN asset_upscale_jobs u ON u.derived_asset_id=v.id WHERE v.project_id=? AND v.phase=? AND v.item_key LIKE ? AND v.is_current=1 ORDER BY v.item_key").bind(projectId,assetPhase,assetKeyPrefix+"%").all(),assetRows=assets.results as any[];
  if(!isReel&&assetRows.some(asset=>String(asset.mimeType).startsWith("image/")&&asset.upscaleStatus!=="UPSCALE_COMPLETED"))continue;
  for(const platform of platforms){
   const schedule=platformSchedule(source,platform);if(!schedule.scheduledFor||!Number.isFinite(Date.parse(schedule.scheduledFor)))continue;
   const connection=schedule.socialConnectionId?await db.prepare("SELECT connection_id AS connectionId,handle FROM project_social_connections WHERE project_id=? AND platform=? AND connection_id=? AND status='Connected'").bind(projectId,platform,schedule.socialConnectionId).first<any>():await db.prepare("SELECT connection_id AS connectionId,handle FROM project_social_connections WHERE project_id=? AND platform=? AND status='Connected' ORDER BY is_default DESC,connected_at LIMIT 1").bind(projectId,platform).first<any>(),connectionKey=connection?.connectionId||schedule.socialConnectionId||"unassigned";
   const job=await createSystemJob(db,{projectId,contentId,taskId:`publish:${contentId}:${platform}:${connectionKey}`,jobType:"PUBLISH_JOB",actor,provider:`connector:${platform.toLowerCase().replaceAll(" ","-")}`,inputAssets:assetRows,inputPayload:{platform,batchId:activeBatch?.id||null,publishingOrder,socialConnectionId:connection?.connectionId||schedule.socialConnectionId||null,profileHandle:connection?.handle||schedule.profileHandle||"",title:item.title||source.title||contentId,contentType:item.contentType||source.contentType||"",caption:item.caption||"",hashtags:item.hashtags||"",scheduledFor:schedule.scheduledFor,sourcePhase:assetPhase,finalApproved:true},scheduledFor:schedule.scheduledFor,idempotencyKey:`publish:${projectId}:${activeBatch?.id||"batch"}:${contentId}:${platform}:${connectionKey}:${assetPhase}:${isReel?reelRow?.version:productionRow?.version}`});
   const record=await ensurePublishingRecord(db,job),automatic=isAutomaticPublishingPlatform(platform),capabilityBlocked=Boolean(connection&&!automatic),errorCode=connection?(automatic?null:"LIVE_PUBLISHING_NOT_IMPLEMENTED"):"ACCOUNT_NOT_CONNECTED",errorMessage=connection?(automatic?null:`Live ${platform} automatic publishing is not implemented. Publish manually and save the live link.`):`${platform} is approved for this Content but no connected Project Profile is available.`,jobStatus=capabilityBlocked?"BLOCKED_CAPABILITY":"WAITING_PROVIDER",recordStatus=capabilityBlocked?"MANUAL_REQUIRED":"NEEDS_ATTENTION";
   if(errorCode){await db.batch([db.prepare("UPDATE orchestrator_jobs SET status=?,last_error=?,updated_at=? WHERE id=? AND status!='SUCCEEDED'").bind(jobStatus,errorMessage,now(),job.id),db.prepare("UPDATE publishing_records SET status=?,error_code=?,error_message=?,requires_human_action=1,updated_at=? WHERE id=? AND status NOT IN ('PUBLISHED','MANUAL_EXCEPTION')").bind(recordStatus,errorCode,errorMessage,now(),record.id)]);job.status=jobStatus;job.lastError=errorMessage}
   created.push(job);
  }
 }
 return created;
}

export async function dispatchSystemJob(db:any,env:any,jobId:string,origin:string){const job=await getSystemJob(db,jobId);if(!job)throw Object.assign(new Error("Job not found."),{status:404});if(job.jobType==="PUBLISH_JOB"&&(!job.scheduledFor||!Number.isFinite(Date.parse(job.scheduledFor))))return job;if(["SCHEDULED","RETRY_PENDING"].includes(job.status)&&job.scheduledFor&&Date.parse(job.scheduledFor)>Date.now())return job;if(!["QUEUED","RETRY_PENDING","WAITING_PROVIDER","SCHEDULED"].includes(job.status))return job;if(job.jobType==="IMAGE_GENERATION"){const result=await dispatchRunningHubQwenImage(db,env,job,updateSystemJob);if(result?.status==="FAILED")await notifyGenerationIncident(db,env,job.id,result.lastError||"Qwen image generation failed.");return result}
 if(job.jobType==="IMAGE_UPSCALE"){const result=await dispatchRunningHubUpscale(db,env,job,updateSystemJob);if(result?.status==="FAILED")await notifyGenerationIncident(db,env,job.id,result.lastError||"Image upscale failed.");if(result?.status==="SUCCEEDED"){await queueApprovedSocialPublishJobs(db,job.projectId,"content-production","system:runninghub");const batchPrefix=socialBatchAssetPrefixFromKey(String(job.inputPayload?.itemKey||"")),remaining=await db.prepare("SELECT COUNT(*) AS count FROM visual_asset_revisions v LEFT JOIN asset_upscale_jobs u ON u.derived_asset_id=v.id WHERE v.project_id=? AND v.phase='content-production' AND v.item_key LIKE ? AND v.is_current=1 AND v.mime_type LIKE 'image/%' AND COALESCE(u.status,'')!='UPSCALE_COMPLETED'").bind(job.projectId,`${batchPrefix}%`).first<any>(),reelPhase=await db.prepare("SELECT 1 AS ready FROM phase_records WHERE project_id=? AND phase_key='reel-video-production' AND status IN ('In Progress','Reopened','Retake')").bind(job.projectId).first<any>();if(Number(remaining?.count||0)===0&&reelPhase){try{const{resumeAgent}=await import("../agent-runner/service");await resumeAgent(db,env,job.projectId)}catch{}}}return result}
 if(job.jobType==="VIDEO_GENERATION"){const result=await dispatchRunningHubH3Video(db,env,job,updateSystemJob);if(result?.status==="FAILED")await notifyGenerationIncident(db,env,job.id,result.lastError||"Reel generation failed.");return result}
	 if(job.jobType==="PUBLISH_JOB"){
	  if(job.attemptCount>=job.maxAttempts){await db.prepare("UPDATE publishing_records SET status='NEEDS_ATTENTION',error_code=COALESCE(error_code,'MAX_ATTEMPTS_REACHED'),error_message=COALESCE(error_message,?),updated_at=? WHERE job_id=? AND status!='PUBLISHED'").bind(job.lastError||"Maximum publishing attempts reached.",now(),job.id).run();return updateSystemJob(db,jobId,"FAILED","system:publishing",{error:job.lastError||"Maximum publishing attempts reached."})}
  await updateSystemJob(db,jobId,"RUNNING","system:publishing");
  try{const result=await executePublishJob(db,env,{...job,requestOrigin:origin,attemptCount:job.attemptCount+1});await db.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(job.projectId,"social_content_published","system:publishing",JSON.stringify({jobId:job.id,contentId:job.contentId,platform:result.platform,publishedAt:result.publishedAt,postUrl:result.postUrl,providerPostId:result.providerPostId}),now()).run();const record=await db.prepare("SELECT id FROM publishing_records WHERE job_id=?").bind(job.id).first<any>();if(record?.id)await sendPublishedTelegramNotification(db,env,Number(record.id));return updateSystemJob(db,jobId,"SUCCEEDED","system:publishing",{outputPayload:result,error:null})}
  catch(error:any){const next=job.attemptCount+1>=job.maxAttempts?"FAILED":"RETRY_PENDING",code=String(error.code||"PUBLISH_FAILED"),message=String(error.message||error),processing=["MEDIA_PROCESSING_PENDING","PERMALINK_PENDING"].includes(code)&&next==="RETRY_PENDING";await db.prepare("UPDATE publishing_records SET status=?,error_code=?,error_message=?,retry_count=MAX(retry_count,?),requires_human_action=CASE WHEN ? IN ('ACCOUNT_NOT_CONNECTED','CONNECTOR_NOT_SUPPORTED') THEN 1 ELSE requires_human_action END,updated_at=? WHERE job_id=?").bind(processing?"PUBLISHING":"NEEDS_ATTENTION",code,message,job.attemptCount+1,code,now(),job.id).run();await db.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(job.projectId,processing?"publishing_container_processing":"publishing_failure","system:publishing",JSON.stringify({jobId:job.id,contentId:job.contentId,platform:job.inputPayload.platform,code,message,nextStatus:next}),now()).run();return updateSystemJob(db,jobId,next,"system:publishing",{error:`${code}: ${message}`})}
 }
 return updateSystemJob(db,jobId,"WAITING_PROVIDER","system:orchestrator",{error:`${job.jobType} is registered but its production Adapter is not configured.`})}

export async function completePublishJob(db:any,env:any,job:any,result:any){if(job.jobType!=="PUBLISH_JOB")return;const platform=String(result.platform||job.inputPayload.platform||"Social"),postUrl=String(result.post_url||result.postUrl||""),publishedAt=String(result.published_at||result.publishedAt||now()),providerId=String(result.platform_post_id||result.platformPostId||result.providerPostId||"");if(!postUrl)throw Object.assign(new Error("A successful Publish callback must include post_url."),{status:400});await ensurePublishingRecord(db,job);await db.prepare("UPDATE publishing_records SET status='PUBLISHED',published_at=?,provider_post_id=?,provider_media_id=?,post_url=?,result=?,performance_sync_status='PENDING',telegram_notification_status='PENDING',telegram_notified_at=NULL,telegram_notification_error=NULL,requires_human_action=0,updated_at=? WHERE job_id=?").bind(publishedAt,providerId,providerId,postUrl,JSON.stringify(result),now(),job.id).run();await db.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(job.projectId,"social_content_published",job.actor,JSON.stringify({jobId:job.id,contentId:job.contentId,platform,publishedAt,postUrl,providerId}),now()).run();const record=await db.prepare("SELECT id FROM publishing_records WHERE job_id=?").bind(job.id).first<any>();if(record?.id)await sendPublishedTelegramNotification(db,env,Number(record.id))}
