import{cookie,hash,loginConnection,randomToken,runtime,verifyTelegramIdToken}from"../_lib";

function redirect(req:Request,status:string,reason?:string){const url=new URL("/telegram-login",req.url);url.searchParams.set("status",status);if(reason)url.searchParams.set("reason",reason);return new Response(null,{status:302,headers:{location:url.toString(),"set-cookie":"ff_tg_login_state=; Path=/api/telegram-login/callback; HttpOnly; Secure; SameSite=Lax; Max-Age=0"}})}
export async function GET(req:Request){
 const env=await runtime(),url=new URL(req.url),code=String(url.searchParams.get("code")||""),state=String(url.searchParams.get("state")||"");if(!code||!state||cookie(req,"ff_tg_login_state")!==state)return redirect(req,"error","invalid-state");
 const pending=await env.DB.prepare("SELECT member_email AS memberEmail,code_verifier AS codeVerifier,expires_at AS expiresAt FROM member_telegram_login_requests WHERE state_hash=?").bind(await hash(state)).first<any>();if(!pending||Date.parse(pending.expiresAt)<=Date.now())return redirect(req,"error","expired");
 try{
  const connection=await loginConnection(env.DB,env),clientId=String(connection.config.clientId),redirectUri=String(connection.config.redirectUri||new URL("/api/telegram-login/callback",req.url)),authorization=btoa(`${clientId}:${connection.secret}`),tokenResponse=await fetch("https://oauth.telegram.org/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded",authorization:`Basic ${authorization}`},body:new URLSearchParams({grant_type:"authorization_code",code,redirect_uri:redirectUri,client_id:clientId,code_verifier:pending.codeVerifier})}),tokens:any=await tokenResponse.json();if(!tokenResponse.ok||!tokens.id_token)throw new Error("token-exchange");
  const claims=await verifyTelegramIdToken(String(tokens.id_token),clientId),telegramUserId=String(claims.id||claims.sub||""),username=String(claims.preferred_username||"").replace(/^@/,"").toLowerCase(),identity=await env.DB.prepare("SELECT expected_username AS expectedUsername,telegram_user_id AS telegramUserId FROM member_telegram_identities WHERE member_email=?").bind(pending.memberEmail).first<any>();if(!telegramUserId||!identity)throw new Error("identity-missing");if(identity.telegramUserId&&String(identity.telegramUserId)!==telegramUserId)throw new Error("identity-mismatch");if(!identity.telegramUserId&&String(identity.expectedUsername||"").replace(/^@/,"").toLowerCase()!==username)throw new Error("username-mismatch");
  const now=new Date().toISOString(),session=randomToken(48),sessionHash=await hash(session),expiresAt=new Date(Date.now()+7*24*60*60*1000).toISOString();await env.DB.batch([env.DB.prepare("UPDATE member_telegram_identities SET telegram_user_id=?,username=?,display_name=?,picture_url=?,status='Linked',linked_at=COALESCE(linked_at,?),last_login_at=?,updated_at=? WHERE member_email=?").bind(telegramUserId,username,String(claims.name||""),String(claims.picture||""),now,now,now,pending.memberEmail),env.DB.prepare("INSERT INTO member_telegram_sessions(token_hash,member_email,telegram_user_id,expires_at,created_at) VALUES(?,?,?,?,?)").bind(sessionHash,pending.memberEmail,telegramUserId,expiresAt,now),env.DB.prepare("DELETE FROM member_telegram_login_requests WHERE state_hash=?").bind(await hash(state))]);
  const target=new URL("/telegram-login",req.url);target.searchParams.set("status","success");target.searchParams.set("member",pending.memberEmail);return new Response(null,{status:302,headers:{location:target.toString(),"set-cookie":`ff_telegram_session=${encodeURIComponent(session)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800`}});
 }catch{return redirect(req,"error","verification-failed")}
}

