import{requestUserEmail}from"../../chatgpt-auth";
const MAX_BYTES=40*1024*1024;

async function context(req:Request,projectId:string){const{env}=await import("cloudflare:workers");const db=env.DB;await db.prepare(`CREATE TABLE IF NOT EXISTS visual_asset_revisions (id INTEGER PRIMARY KEY AUTOINCREMENT,project_id TEXT NOT NULL,phase TEXT NOT NULL,item_key TEXT NOT NULL,version INTEGER NOT NULL,storage_key TEXT NOT NULL,file_name TEXT NOT NULL,mime_type TEXT NOT NULL,size_bytes INTEGER NOT NULL,uploaded_by TEXT NOT NULL,is_current INTEGER NOT NULL DEFAULT 1,drive_sync_status TEXT NOT NULL DEFAULT 'Pending Drive sync',created_at TEXT NOT NULL)`).run();const email=requestUserEmail(req);if(!email)throw new Error("Authenticated workspace identity required");const member=await db.prepare("SELECT email,tier FROM members WHERE email=?").bind(email).first<any>();if(!member)throw new Error("Workspace membership required");if(member.tier>1){const ok=await db.prepare("SELECT 1 ok FROM project_members WHERE project_id=? AND member_email=?").bind(projectId,email).first();if(!ok)throw new Error("Project access denied")}return{env,db,email}}

export async function POST(req:Request){try{const u=new URL(req.url),action=u.searchParams.get("action")||"",projectId=u.searchParams.get("projectId")||"",uploadId=(u.searchParams.get("uploadId")||"").replace(/[^a-zA-Z0-9_-]/g,"");if(!projectId||!uploadId)return Response.json({error:"Missing upload details"},{status:400});const{env,db,email}=await context(req,projectId),prefix=`temporary-song-uploads/${projectId}/${uploadId}`;
 if(action==="chunk"){const index=Number(u.searchParams.get("index"));if(!Number.isInteger(index)||index<0)return Response.json({error:"Invalid chunk"},{status:400});const bytes=await req.arrayBuffer();if(!bytes.byteLength||bytes.byteLength>700*1024)return Response.json({error:"Invalid chunk size"},{status:400});await env.BUCKET.put(`${prefix}/${index}`,bytes,{httpMetadata:{contentType:"application/octet-stream"}});return Response.json({ok:true,index})}
 if(action==="finish"){const chunks=Math.max(1,Number(u.searchParams.get("chunks"))||0),size=Math.max(0,Number(u.searchParams.get("size"))||0),fileName=u.searchParams.get("fileName")||"song.mp3",mimeType=u.searchParams.get("mimeType")||"audio/mpeg";if(size<=0||size>MAX_BYTES)return Response.json({error:"Song must be 40 MB or smaller"},{status:400});const assembled=new Uint8Array(size);let offset=0;for(let i=0;i<chunks;i++){const part=await env.BUCKET.get(`${prefix}/${i}`);if(!part)return Response.json({error:`Upload part ${i+1} is missing. Please retry.`},{status:400});const bytes=new Uint8Array(await part.arrayBuffer());assembled.set(bytes,offset);offset+=bytes.length}if(offset!==size)return Response.json({error:"Uploaded size does not match the song file"},{status:400});const previous=await db.prepare("SELECT COALESCE(MAX(version),0) version FROM visual_asset_revisions WHERE project_id=? AND phase='mv-song' AND item_key='master-song'").bind(projectId).first<any>(),version=Number(previous?.version||0)+1,safe=fileName.replace(/[^a-zA-Z0-9._-]/g,"-"),key=`projects/${projectId}/mv-song/master-song/v${version}-${Date.now()}-${safe}`;await env.BUCKET.put(key,assembled,{httpMetadata:{contentType:mimeType}});await db.batch([db.prepare("UPDATE visual_asset_revisions SET is_current=0 WHERE project_id=? AND phase='mv-song' AND item_key='master-song'").bind(projectId),db.prepare("INSERT INTO visual_asset_revisions(project_id,phase,item_key,version,storage_key,file_name,mime_type,size_bytes,uploaded_by,is_current,drive_sync_status,created_at) VALUES(?,?,?,?,?,?,?,?,?,1,'Pending Drive sync',?)").bind(projectId,"mv-song","master-song",version,key,fileName,mimeType,size,email,new Date().toISOString())]);try{const{syncStoredAssetToDrive}=await import("../google-drive/drive");await syncStoredAssetToDrive(projectId,"mv-song",key,`v${version}_${fileName}`,mimeType)}catch{}for(let i=0;i<chunks;i++)await env.BUCKET.delete(`${prefix}/${i}`);return Response.json({ok:true,version})}
 return Response.json({error:"Unknown upload action"},{status:400})}catch(e:any){return Response.json({error:e?.message||"Song upload failed"},{status:/access|membership/i.test(e?.message||"")?403:500})}}
