import{FACEBOOK_SCOPES,apiVersion,appConnection,callbackUrl,cookie,decodeState,inspectPageToken,oauthErrorResult,origin,parseSelectionSecret,projectRedirect,recordOAuthError,runtime,savePageConnection,selectionSecret}from"../_lib";
import{loadIntegration,saveIntegration}from"../../integrations/_lib";
import{socialAccess}from"../../social-connections/_lib";
import{AUTOPOST_ENABLED,autoPostNotFound}from"../../../autopost-mode";

const OAUTH_COOKIE="ff_fb_oauth",SELECTION_COOKIE="ff_fb_selection";
const clearCookie=(name:string)=>`${name}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`;
const redirect=(req:Request,projectId:string,result:string,cookieName=OAUTH_COOKIE)=>new Response(null,{status:302,headers:{location:projectRedirect(req,projectId,result),"set-cookie":clearCookie(cookieName)}});
const escapeHtml=(value:unknown)=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]||char));

function selectionPage(req:Request,selectionId:string,pages:any[]){const cards=pages.map((page,index)=>`<label class="page"><input type="radio" name="pageId" value="${escapeHtml(page.id)}" ${index===0?"checked":""}><span><strong>${escapeHtml(page.name)}</strong><small>Page ID · ${escapeHtml(page.id)}${page.category?` · ${escapeHtml(page.category)}`:""}</small>${page.link?`<em>${escapeHtml(page.link)}</em>`:""}</span></label>`).join("");const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Select Facebook Page · FrameFlow</title><style>body{margin:0;background:#f6f5f2;color:#19212b;font-family:Arial,sans-serif}.wrap{max-width:720px;margin:7vh auto;padding:24px}.card{background:#fff;border:1px solid #e3e6e8;border-radius:18px;padding:28px;box-shadow:0 18px 60px #19212b12}h1{font:500 32px Georgia,serif;margin:8px 0 10px}p{color:#6e7882;line-height:1.55}.eyebrow{font-size:10px;letter-spacing:.16em;color:#b5122f;font-weight:800}.page{display:flex;gap:12px;padding:16px;margin:10px 0;border:1px solid #e4e7e9;border-radius:12px;cursor:pointer}.page:has(input:checked){border-color:#b5122f;background:#fff7f8}.page input{margin-top:4px}.page span{display:grid;gap:4px}.page small,.page em{color:#74808d;font-size:12px;font-style:normal;overflow-wrap:anywhere}button{width:100%;margin-top:18px;border:0;border-radius:11px;padding:14px;background:#b5122f;color:#fff;font-weight:800;cursor:pointer}.note{margin-top:14px;font-size:12px}</style></head><body><main class="wrap"><section class="card"><div class="eyebrow">FRAMEFLOW · FACEBOOK PAGE</div><h1>Choose the Page for this Project</h1><p>Your Facebook account manages more than one Page. Select exactly which Page FrameFlow should connect. Personal Profiles are never added as publishing destinations.</p><form method="post" action="/api/facebook/callback"><input type="hidden" name="selectionId" value="${escapeHtml(selectionId)}">${cards}<button type="submit">Connect selected Facebook Page →</button></form><p class="note">Page Access Tokens remain encrypted server-side and are not included in this page.</p></section></main></body></html>`;return new Response(html,{status:200,headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","content-security-policy":"default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'","referrer-policy":"no-referrer","set-cookie":`${SELECTION_COOKIE}=${encodeURIComponent(selectionId)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=600`}})}

async function connectSelectedPage(req:Request,env:any,app:any,input:{projectId:string;page:any;grantedScopes:string[];actorEmail:string;requestedConnectionId?:string|null}){const version=apiVersion(app.config),identityUrl=new URL(`https://graph.facebook.com/${version}/${encodeURIComponent(String(input.page.id||""))}`);identityUrl.searchParams.set("fields","id,name,link,category");const identityResponse=await fetch(identityUrl,{headers:{authorization:`Bearer ${String(input.page.accessToken||"")}`,"cache-control":"no-store"}}),identity:any=await identityResponse.json().catch(()=>({}));if(!identityResponse.ok||String(identity.id||"")!==String(input.page.id||"")){const failure=oauthErrorResult(identity,identityResponse.status);throw Object.assign(new Error(failure.message),{code:failure.code,status:409,stage:"page-verify",traceId:failure.traceId})}const tokenStatus=await inspectPageToken(app,String(input.page.accessToken));if(!tokenStatus.isValid)throw Object.assign(new Error("Facebook Page Access Token could not be validated."),{code:"FACEBOOK_PAGE_TOKEN_INVALID",status:409,stage:"token-debug"});return savePageConnection(env.DB,env,{...input,page:{...input.page,...identity},tokenStatus})}

export async function GET(req:Request){
 if(!AUTOPOST_ENABLED)return autoPostNotFound();
 const home=origin(req),url=new URL(req.url),code=String(url.searchParams.get("code")||""),state=String(url.searchParams.get("state")||""),providerError=String(url.searchParams.get("error")||""),providerDescription=String(url.searchParams.get("error_description")||""),saved=decodeState(cookie(req,OAUTH_COOKIE)),fallback=(result:string)=>new Response(null,{status:302,headers:{location:`${home}/?facebook=${encodeURIComponent(result)}`,"set-cookie":clearCookie(OAUTH_COOKIE)}});
 if(!state||!saved||saved.state!==state||!saved.projectId){try{const invalidEnv=await runtime();await recordOAuthError(invalidEnv.DB,"",String(req.headers.get("oai-authenticated-user-email")||"system"),"INVALID_STATE","Facebook OAuth state or Project binding was missing or invalid.")}catch{}return fallback("invalid-state")}
 const env=await runtime(),projectId=String(saved.projectId),actorEmail=String(req.headers.get("oai-authenticated-user-email")||"system");
 try{await socialAccess(req,env.DB,projectId,true)}catch(error:any){await recordOAuthError(env.DB,projectId,actorEmail,"MANAGEMENT_REQUIRED",String(error?.message||"Management access required"));return redirect(req,projectId,"management-required")}
 if(providerError){await recordOAuthError(env.DB,projectId,actorEmail,providerError,providerDescription||"Facebook authorization was not completed.");return redirect(req,projectId,`oauth-error-${providerError}`)}
 if(!code){await recordOAuthError(env.DB,projectId,actorEmail,"CODE_MISSING","Facebook did not return an authorization code.");return redirect(req,projectId,"code-missing")}
 let app:any;try{app=await appConnection(env.DB,env)}catch(error:any){await recordOAuthError(env.DB,projectId,actorEmail,"CONFIGURATION_REQUIRED",String(error?.message||"Facebook App is not configured."));return redirect(req,projectId,"configuration-required")}
 try{
  const version=apiVersion(app.config),tokenUrl=new URL(`https://graph.facebook.com/${version}/oauth/access_token`),tokenResponse=await fetch(tokenUrl,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded","cache-control":"no-store"},body:new URLSearchParams({client_id:String(app.config.appId),client_secret:String(app.secret),redirect_uri:callbackUrl(req),code})}),short:any=await tokenResponse.json().catch(()=>({}));if(!tokenResponse.ok||!short.access_token){const failure=oauthErrorResult(short,tokenResponse.status);await recordOAuthError(env.DB,projectId,actorEmail,failure.code,failure.message,{subcode:failure.subcode,traceId:failure.traceId,httpStatus:tokenResponse.status,stage:"token"});return redirect(req,projectId,`token-failed-${failure.code}`)}
  const longUrl=new URL(`https://graph.facebook.com/${version}/oauth/access_token`),longResponse=await fetch(longUrl,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded","cache-control":"no-store"},body:new URLSearchParams({grant_type:"fb_exchange_token",client_id:String(app.config.appId),client_secret:String(app.secret),fb_exchange_token:String(short.access_token)})}),long:any=await longResponse.json().catch(()=>({}));if(!longResponse.ok||!long.access_token){const failure=oauthErrorResult(long,longResponse.status);await recordOAuthError(env.DB,projectId,actorEmail,failure.code,failure.message,{subcode:failure.subcode,traceId:failure.traceId,httpStatus:longResponse.status,stage:"long-lived-token"});return redirect(req,projectId,`long-token-failed-${failure.code}`)}const userToken=String(long.access_token),userTokenExpiresAt=new Date(Date.now()+Math.max(1,Number(long.expires_in||3600))*1000).toISOString();
  const permissionsUrl=new URL(`https://graph.facebook.com/${version}/me/permissions`),permissionsResponse=await fetch(permissionsUrl,{headers:{authorization:`Bearer ${userToken}`,"cache-control":"no-store"}}),permissions:any=await permissionsResponse.json().catch(()=>({}));if(!permissionsResponse.ok){const failure=oauthErrorResult(permissions,permissionsResponse.status);await recordOAuthError(env.DB,projectId,actorEmail,failure.code,failure.message,{traceId:failure.traceId,httpStatus:permissionsResponse.status,stage:"permissions"});return redirect(req,projectId,`permissions-failed-${failure.code}`)}
  const grantedScopes=(Array.isArray(permissions.data)?permissions.data:[]).filter((item:any)=>item.status==="granted").map((item:any)=>String(item.permission)),missingScopes=FACEBOOK_SCOPES.filter(scope=>!grantedScopes.includes(scope));if(missingScopes.length){await recordOAuthError(env.DB,projectId,actorEmail,"PERMISSIONS_MISSING","Required Facebook Page permissions were not granted.",{missingScopes,grantedScopes});return redirect(req,projectId,"permissions-missing")}
  const pagesUrl=new URL(`https://graph.facebook.com/${version}/me/accounts`);pagesUrl.search=new URLSearchParams({fields:"id,name,access_token,category,tasks,link",limit:"100"}).toString();const pagesResponse=await fetch(pagesUrl,{headers:{authorization:`Bearer ${userToken}`,"cache-control":"no-store"}}),pagesResult:any=await pagesResponse.json().catch(()=>({}));if(!pagesResponse.ok){const failure=oauthErrorResult(pagesResult,pagesResponse.status);await recordOAuthError(env.DB,projectId,actorEmail,failure.code,failure.message,{traceId:failure.traceId,httpStatus:pagesResponse.status,stage:"pages"});return redirect(req,projectId,`pages-failed-${failure.code}`)}
  const pages=(Array.isArray(pagesResult.data)?pagesResult.data:[]).filter((page:any)=>page?.id&&page?.name&&page?.access_token).map((page:any)=>({id:String(page.id),name:String(page.name),link:String(page.link||`https://www.facebook.com/${page.id}`),category:String(page.category||""),tasks:Array.isArray(page.tasks)?page.tasks.map(String):[],accessToken:String(page.access_token)}));if(!pages.length){await recordOAuthError(env.DB,projectId,actorEmail,"NO_MANAGED_PAGES","Facebook returned no Pages with a Page Access Token.");return redirect(req,projectId,"no-managed-pages")}
  if(pages.length===1){await connectSelectedPage(req,env,app,{projectId,page:pages[0],grantedScopes,actorEmail,requestedConnectionId:String(saved.connectionId||"")});return redirect(req,projectId,"connected")}
  const selectionId=crypto.randomUUID().replaceAll("-",""),provider=`facebook-selection:${selectionId}`,expiresAt=new Date(Date.now()+10*60*1000).toISOString();await saveIntegration(env.DB,env,provider,selectionSecret(pages),{projectId,requestedConnectionId:String(saved.connectionId||""),actorEmail,grantedScopes,userTokenExpiresAt,expiresAt,pages:pages.map(({accessToken,...page}:any)=>page)},"Pending Page selection");await env.DB.prepare("INSERT INTO audit_log(project_id,event_type,actor_email,event_data,created_at) VALUES(?,?,?,?,?)").bind(projectId,"facebook_page_selection_required",actorEmail,JSON.stringify({selectionId,pageCount:pages.length,pageIds:pages.map((page:any)=>page.id),expiresAt}),new Date().toISOString()).run();return selectionPage(req,selectionId,pages);
 }catch(error:any){await recordOAuthError(env.DB,projectId,actorEmail,String(error?.code||"CALLBACK_FAILED"),String(error?.message||"Facebook OAuth callback failed."),{stage:error?.stage||"callback",traceId:error?.traceId||""});return redirect(req,projectId,"callback-failed")}
}

export async function POST(req:Request){
 if(!AUTOPOST_ENABLED)return autoPostNotFound();
 const env=await runtime(),form=await req.formData(),selectionId=String(form.get("selectionId")||""),pageId=String(form.get("pageId")||""),cookieSelection=cookie(req,SELECTION_COOKIE),pending=selectionId&&cookieSelection===selectionId?await loadIntegration(env.DB,env,`facebook-selection:${selectionId}`):null,projectId=String(pending?.config?.projectId||""),actorEmail=String(req.headers.get("oai-authenticated-user-email")||pending?.config?.actorEmail||"system");
 if(!pending||!projectId||Date.parse(String(pending.config?.expiresAt||""))<=Date.now()){if(projectId)await recordOAuthError(env.DB,projectId,actorEmail,"SELECTION_EXPIRED","Facebook Page selection expired or was invalid.");return redirect(req,projectId,"selection-expired",SELECTION_COOKIE)}
 try{await socialAccess(req,env.DB,projectId,true);const app=await appConnection(env.DB,env),pages=parseSelectionSecret(pending.secret).pages,page=pages.find(item=>item.id===pageId);if(!page)throw Object.assign(new Error("Select one of the Facebook Pages returned for this authorization."),{code:"INVALID_PAGE_SELECTION",status:400});await connectSelectedPage(req,env,app,{projectId,page,grantedScopes:Array.isArray(pending.config.grantedScopes)?pending.config.grantedScopes:[],actorEmail,requestedConnectionId:String(pending.config.requestedConnectionId||"")});await env.DB.prepare("DELETE FROM integration_connections WHERE provider=?").bind(`facebook-selection:${selectionId}`).run();return redirect(req,projectId,"connected",SELECTION_COOKIE)}catch(error:any){await recordOAuthError(env.DB,projectId,actorEmail,String(error?.code||"PAGE_SELECTION_FAILED"),String(error?.message||"Facebook Page selection failed."),{stage:error?.stage||"selection",traceId:error?.traceId||""});return redirect(req,projectId,"selection-failed",SELECTION_COOKIE)}
}
